ClusterHQ/flocker

- docs/gettinginvolved/infrastructure/release-process.rst
> Suggest the necessary change.

- flocker/node/script.py
- flocker/node/test/test_script.py
- flocker/volume/httpapi.py
- flocker/volume/test/test_httpapi.py
https://clusterhq.atlassian.net/browse/FLOC-887 design review.
> [FLOC-887] Connect HTTP server to flocker-serve

- docs/gettinginvolved/infrastructure/release-process.rst
> Misc release doc fixes

- admin/acceptance.py
- docs/gettinginvolved/acceptance-testing.rst
- docs/gettingstarted/installation.rst
- flocker/provision/__init__.py
- flocker/provision/_aws.py
- flocker/provision/_install.py
- flocker/provision/_libcloud.py
- flocker/provision/_rackspace.py
- flocker/provision/_sphinx.py
- flocker/provision/_tasks.py
https://clusterhq.atlassian.net/browse/FLOC-957
> [FLOC-957] Add AWS acceptance test runner.

- flocker/node/_deploy.py
- flocker/node/test/test_deploy.py
- flocker/volume/_ipc.py
- flocker/volume/filesystems/memory.py
- flocker/volume/filesystems/zfs.py
- flocker/volume/functional/test_filesystems_zfs.py
- flocker/volume/functional/test_service.py
- flocker/volume/script.py
- flocker/volume/service.py
- flocker/volume/test/filesystemtests.py
- flocker/volume/test/test_ipc.py
- flocker/volume/test/test_service.py
https://clusterhq.atlassian.net/browse/FLOC-1182
> [FLOC-1182] New terminology

- admin/build_targets/centos-7/Dockerfile
- admin/build_targets/fedora-20/Dockerfile
- admin/build_targets/ubuntu-14.04/Dockerfile
- admin/packaging.py
- admin/test/test_packaging.py
https://clusterhq.atlassian.net/browse/FLOC-1153
> [FLOC-1153] Move package linting to during build.

- docs/gettinginvolved/infrastructure/release-process.rst
- tox.ini
Note that the dev-box build should be passing after this lands.
https://clusterhq.atlassian.net/browse/FLOC-1225
> [FLOC-1125] Disable linkcheck.

- CONTRIBUTING.rst
- docs/faq/index.rst
Fixes https://clusterhq.atlassian.net/browse/FLOC-1183
Note: This can't be merged until security email address has been set up. Part of parent task:
* https://clusterhq.atlassian.net/browse/FLOC-307
> [FLOC-1183] Public security policy

- flocker/node/test/test_deploy.py
> Add a test for ResizeVolume.run.

- docs/_themes/bootstrap/static/sphinx-bootstrap.css
- docs/advanced/api.rst
- docs/advanced/api_examples.yml
- docs/advanced/index.rst
- docs/conf.py
- flocker/control/httpapi.py
- flocker/restapi/docs/publicapi.py
- flocker/restapi/docs/test/test_publicapi.py
https://clusterhq.atlassian.net/browse/FLOC-1219
> [FLOC-1219] Include REST API docs

- docs/faq/index.rst
https://clusterhq.atlassian.net/browse/FLOC-1239
> [FLOC-1239] Use ASCII apostrophe to make spelling happy.

- flocker/acceptance/test_deployment.py
- flocker/acceptance/test_environment_variables.py
- flocker/acceptance/test_linking.py
- flocker/acceptance/test_postgres.py
- flocker/acceptance/testtools.py
- flocker/node/__init__.py
- flocker/node/_config.py
- flocker/node/_deploy.py
- flocker/node/_model.py
- flocker/node/functional/test_deploy.py
- flocker/node/test/test_config.py
- flocker/node/test/test_deploy.py
- flocker/node/test/test_model.py
- flocker/node/test/test_script.py
- setup.py
Fixes FLOC-697.
Depends on #1061.
> Dataset model floc 697

- flocker/node/_docker.py
- flocker/node/functional/test_docker.py
- setup.py
https://clusterhq.atlassian.net/browse/FLOC-1186
Skipped design review phase since there's nothing else left to do.
> [FLOC-1186] New docker-py

- admin/acceptance.py
https://clusterhq.atlassian.net/browse/FLOC-1202
> [FLOC-1202] Clean up, if the acceptance runner receives a signal.

- docs/gettinginvolved/contributing.rst
- docs/gettinginvolved/infrastructure/release-schedule-versioning.rst
https://clusterhq.atlassian.net/browse/FLOC-1253
> [FLOC-1253] Document how to fix bugs in releases.

- flocker/cli/_sshconfig.py
Not tested on the Mac since not sure how to access it.
> [FLOC-1184] Fix other reference to GSS-API

- flocker/restapi/testtools.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-1218
> [FLOC-1218] Fix docstring markup

- docs/gettinginvolved/infrastructure/release-process.rst
> yumdownloader and createrepo and gsutil are all Software requirements.

- docs/gettinginvolved/infrastructure/release-process.rst
> [FLOC-1277] Release improvements

- docs/conf.py
- docs/gettinginvolved/contributing.rst
> [FLOC-1274] Broken markup

- admin/packaging.py
- admin/test/test_packaging.py
- setup.py
> Make more CLI tools available from omnibus package

- docs/gettinginvolved/contributing.rst
https://clusterhq.atlassian.net/browse/FLOC-1298
> [FLOC-1298] Don't delete maintence branches until everything is merged.

- docs/gettinginvolved/infrastructure/release-process.rst
Fixes FLOC-1193 and changes another occurrence of the same push command which caused the issue.
> [FLOC-1193] Changed push commands

- setup.py
https://clusterhq.atlassian.net/browse/FLOC-1302
> [FLOC-1302] Increase Twisted version

- flocker/control/_persistence.py
- flocker/control/_protocol.py
- flocker/control/script.py
- flocker/control/test/test_persistence.py
- flocker/control/test/test_protocol.py
- flocker/control/test/test_script.py
https://clusterhq.atlassian.net/browse/FLOC-1281
> [FLOC-1281] Control service AMP server

- docs/gettingstarted/index.rst
Fixes FLOC-1322
Fixes FLOC-1323
Fixes FLOC-1324
Fixes FLOC-1325
> Several last-minute bug fixes to the instructions in the quickstart guide

- docs/indepth/installation.rst
Fixes https://clusterhq.atlassian.net/browse/FLOC-1344
See https://github.com/ClusterHQ/flocker/pull/1030
> [FLOC-1344] Backport AWS Fedora AMI selection instructions

- README.rst
fixes https://clusterhq.atlassian.net/browse/FLOC-1351
> fix broken links to docs

- flocker/node/__init__.py
- flocker/node/_deploy.py
- flocker/node/functional/test_deploy.py
- flocker/node/script.py
- flocker/node/test/test_deploy.py
- flocker/node/test/test_script.py
https://clusterhq.atlassian.net/browse/FLOC-1321
> [FLOC-1321] New interface for Deployers

- docs/_themes/clusterhq/layout_docs.html
Fixes https://clusterhq.atlassian.net/browse/FLOC-1349
> [FLOC-1349] Use the correct solutions link

- docs/gettingstarted/index.rst
Fixes https://clusterhq.atlassian.net/browse/FLOC-1356
This could / should also be merged into #1118
> [FLOC-1356] Quickstart version numbers

- admin/packaging.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-1365
> [FLOC-1365] Ignore new-package-should-close-itp-bug lintian warnings

- flocker/control/_clusterstate.py
- flocker/control/_model.py
- flocker/control/_protocol.py
- flocker/control/test/test_clusterstate.py
- flocker/control/test/test_config.py
- flocker/control/test/test_httpapi.py
- flocker/control/test/test_protocol.py
- flocker/node/_deploy.py
- flocker/node/test/test_deploy.py
https://clusterhq.atlassian.net/browse/FLOC-1350
Depends on #1119.
> [FLOC-1350] NodeState gets hostname attribute

- flocker/control/_clusterstate.py
- flocker/control/_model.py
- flocker/control/test/test_model.py
- flocker/node/_deploy.py
- flocker/node/test/test_deploy.py
https://clusterhq.atlassian.net/browse/FLOC-389
> [FLOC-389] Make convergence loop take into account local state

- docs/advanced/api_examples.yml
- flocker/control/httpapi.py
- flocker/control/test/test_httpapi.py
https://clusterhq.atlassian.net/browse/FLOC-1387
> Get dataset configuration

- admin/test/test_packaging.py
https://clusterhq.atlassian.net/browse/FLOC-1366
https://github.com/ClusterHQ/flocker/pull/1137#issuecomment-73492624
> [FLOC-1366] Add missing test from #1137.

- docs/advanced/api.rst
- docs/advanced/architecture.rst
- docs/advanced/index.rst
- docs/spelling_wordlist.txt
https://clusterhq.atlassian.net/browse/FLOC-1371
Note this talks about datasets, which aren't yet documented anywhere - this is covered by separate issue, https://clusterhq.atlassian.net/browse/FLOC-1165
> [FLOC-1371] Document the architecture

- docs/gettingstarted/index.rst
> Release maintenance/flocker 0.3.2/quickstart cli to client floc 1399

- admin/vagrant.py
- docs/gettinginvolved/infrastructure/release-process.rst
- docs/gettinginvolved/infrastructure/vagrant.rst
> Atlas floc 1289

- docs/gettinginvolved/infrastructure/vagrant.rst
> Fix incorrect Vagrant ACL

- docs/gettinginvolved/infrastructure/release-process.rst
> Reject pre tag floc 1377

- docs/gettinginvolved/infrastructure/release-process.rst
Newer versions of setuptools PEP440 normalise package version numbers.
> [FLOC-1405] Modify documented command to work with old and new setuptools.

- docs/gettinginvolved/infrastructure/release-process.rst
Fixes https://clusterhq.atlassian.net/browse/FLOC-1315
> No approval is necessary for development releases

- Vagrantfile
- docs/gettinginvolved/infrastructure/release-process.rst
- vagrant/dev/bootstrap.sh
Also copied the box built by Buildbot to a suitable location, and added an updated version to Atlas.
> [FLOC-1343] Virtualenvwrapper floc 1343

- docs/gettinginvolved/infrastructure/release-process.rst
> Removed .rb

- flocker/volume/filesystems/interfaces.py
- flocker/volume/filesystems/memory.py
- flocker/volume/filesystems/zfs.py
- flocker/volume/functional/test_filesystems_zfs.py
- flocker/volume/service.py
- flocker/volume/test/filesystemtests.py
- flocker/volume/test/test_filesystems_memory.py
https://clusterhq.atlassian.net/browse/FLOC-1476
Just enough to get it working.
> [FLOC-1476] ZFS "volume" deletion.

- flocker/control/_config.py
- flocker/control/_model.py
- flocker/control/httpapi.py
- flocker/control/test/test_clusterstate.py
- flocker/control/test/test_config.py
- flocker/control/test/test_httpapi.py
- flocker/control/test/test_model.py
- flocker/control/test/test_protocol.py
- flocker/node/_deploy.py
- flocker/node/functional/test_deploy.py
- flocker/node/script.py
- flocker/node/test/test_deploy.py
- flocker/node/test/test_script.py
- setup.py
https://clusterhq.atlassian.net/browse/FLOC-1453
As a nice side-effect the invariant on `Node` also ensures you can't e.g. move a dataset from one node to another if you're not correspondingly modifying the application that uses it.
I'm really liking pyrsistent.
> [FLOC-1453] First class datasets

- docs/advanced/api.rst
- docs/advanced/api_examples.yml
- docs/advanced/architecture.rst
- flocker/control/httpapi.py
https://clusterhq.atlassian.net/browse/FLOC-1472
> [FLOC-1472] Better API explanations

- flocker/acceptance/test_api.py
- flocker/control/_model.py
- flocker/node/_deploy.py
- flocker/node/test/test_deploy.py
- flocker/testtools/__init__.py
https://clusterhq.atlassian.net/browse/FLOC-1477
https://clusterhq.atlassian.net/browse/FLOC-1478
This should finish off https://clusterhq.atlassian.net/browse/FLOC-1467
> [FLOC-1477] [FLOC-1478] Deployer deletion

- admin/packaging.py
- admin/test/test_packaging.py
- flocker/cli/script.py
- flocker/cli/test/test_cli_script.py
- setup.py
Fixes FLOC-1463. See https://clusterhq.atlassian.net/browse/FLOC-1463?focusedCommentId=16380&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-16380
> [FLOC-1463] Initial stub script for Flocker CLI

- flocker/node/_loop.py
- flocker/node/test/test_loop.py
Fixes FLOC-1378 (at least, well enough for now)
> insert a one second sleep as a temporary solution to this issue

- admin/aws.py
See FLOC-1471 comments for information and linked Buildbot PR.
> Copy key in a way which preserves metadata

- admin/aws.py
https://clusterhq.atlassian.net/browse/FLOC-1471
> Fix typo in #1197.

- docs/advanced/api_examples.yml
- docs/spelling_wordlist.txt
- flocker/control/httpapi.py
- flocker/control/schema/endpoints.yml
- flocker/control/schema/types.yml
- flocker/control/test/test_httpapi.py
- flocker/control/test/test_schemas.py
https://clusterhq.atlassian.net/browse/FLOC-1520
> [FLOC-1520] Create container

- docs/advanced/api_examples.yml
https://clusterhq.atlassian.net/browse/FLOC-1518
Basically just a code review.
> [FLOC-1518] Use valid paths

- flocker/control/test/test_httpapi.py
https://clusterhq.atlassian.net/browse/FLOC-1541
> [FLOC-1541] Fix race condition in test

- docs/advanced/api_examples.yml
- flocker/control/httpapi.py
- flocker/control/test/test_httpapi.py
https://clusterhq.atlassian.net/browse/FLOC-1540
> [FLOC-1540] Remove container API endpoint

- docs/advanced/api_examples.yml
- flocker/control/_config.py
- flocker/control/httpapi.py
- flocker/control/schema/endpoints.yml
- flocker/control/schema/types.yml
- flocker/control/test/test_httpapi.py
- flocker/control/test/test_schemas.py
Fixes FLOC-1556
Please wait for #1218 to be merged before reviewing, it will make the diff a lot smaller.
> [FLOC-1556] Create container with CPU shares

- NEWS
This should not be merged until the release process is complete.
> [FLOC-1537] Release 0.3.3dev8

- docs/advanced/api_examples.yml
- flocker/control/_config.py
- flocker/control/httpapi.py
- flocker/control/schema/endpoints.yml
- flocker/control/schema/types.yml
- flocker/control/test/test_httpapi.py
- flocker/control/test/test_schemas.py
> [FLOC-1557] Create container with memory limit

- docs/advanced/api_examples.yml
- flocker/control/httpapi.py
- flocker/control/schema/endpoints.yml
- flocker/control/schema/types.yml
- flocker/control/test/test_httpapi.py
- flocker/control/test/test_schemas.py
> [FLOC-1558] Create container with links

- admin/packaging.py
https://clusterhq.atlassian.net/browse/FLOC-1566
> Ignore lintian error about package revision.

- Vagrantfile
- docs/gettinginvolved/infrastructure/release-process.rst
- docs/spelling_wordlist.txt
- flocker/provision/_install.py
The commit for this PR was with a new dev box
> Copy git config to VM

- docs/_themes/clusterhq/static/css/docs.css
This colour configuration has had approval from @alicesowerby
> Search highlight floc 1334

- docs/advanced/api_examples.yml
- docs/spelling_wordlist.txt
- flocker/control/httpapi.py
- flocker/control/schema/endpoints.yml
- flocker/control/schema/types.yml
- flocker/control/test/test_httpapi.py
- flocker/control/test/test_schemas.py
Fixes FLOC-1568
Diff will look cleaner once #1221 is merged; this branch includes the work from that one in order to allow one of the tests utilising an `AttachedVolume` to pass.
> [FLOC-1568] List configuration containers

- docs/advanced/api_examples.yml
- docs/spelling_wordlist.txt
- flocker/control/httpapi.py
- flocker/control/schema/endpoints.yml
- flocker/control/schema/types.yml
- flocker/control/test/test_httpapi.py
- flocker/control/test/test_schemas.py
https://clusterhq.atlassian.net/browse/FLOC-1555
Depends on #1218 being merged for nice diff.
There's no acceptance test because it's a pain to do lacking e.g. ability to poll for currently running containers. So will want to return to it later when it's easier. Or, ideas welcome.
> [FLOC-1555] Container with dataset

- flocker/control/_config.py
- flocker/control/_model.py
- flocker/control/test/test_clusterstate.py
- flocker/control/test/test_config.py
- flocker/control/test/test_httpapi.py
- flocker/control/test/test_model.py
- flocker/control/test/test_protocol.py
- flocker/node/_deploy.py
- flocker/node/test/test_deploy.py
https://clusterhq.atlassian.net/browse/FLOC-1569
> [FLOC-1569] Application can express running state

- docs/advanced/api_examples.yml
- flocker/control/httpapi.py
- flocker/control/schema/endpoints.yml
- flocker/control/schema/types.yml
- flocker/control/test/test_httpapi.py
- flocker/control/test/test_schemas.py
https://clusterhq.atlassian.net/browse/FLOC-1581
> [FLOC-1581] List containers state

- flocker/control/httpapi.py
https://clusterhq.atlassian.net/browse/FLOC-1587
> [FLOC-1587] Document that datasets aren't removed by container removal

- admin/release.py
- admin/test/test_release.py
- flocker/docs/__init__.py
- flocker/docs/_version.py
- flocker/docs/test/test_version.py
> Publish pre release floc 1594

- flocker/acceptance/test_api.py
https://clusterhq.atlassian.net/browse/FLOC-1567
> [FLOC-1567] Acceptance test: container with dataset

- flocker/control/_clusterstate.py
- flocker/control/_model.py
- flocker/control/test/test_clusterstate.py
- flocker/control/test/test_model.py
- flocker/node/_loop.py
https://clusterhq.atlassian.net/browse/FLOC-1595
> [FLOC-1595] Partial state updates

- docs/gettinginvolved/infrastructure/release-process.rst
> Switch to the correct directory before publishing docs

- docs/gettinginvolved/infrastructure/release-process.rst
This removes what I think is automatically tested and what was deemed unnecessary around https://zulip.com/#narrow/stream/engineering/subject/0.2E4.2E0pre1/near/37390076.
> Removed unnecessary review steps

- docs/gettinginvolved/infrastructure/release-process.rst
- docs/indepth/installation.rst
- flocker/provision/_install.py
- flocker/provision/_sphinx.py
> Brew tap floc 1611

- flocker/control/_model.py
- flocker/node/__init__.py
- flocker/node/_deploy.py
- flocker/node/_docker.py
- flocker/node/_loop.py
- flocker/node/agents/blockdevice.py
- flocker/node/agents/test/test_blockdevice.py
- flocker/node/script.py
- flocker/node/test/test_deploy.py
- flocker/node/test/test_docker.py
- flocker/node/testtools.py
Will be more readable once #1233 is merged (which can be done as soon as buildbot is green).
> [FLOC-1542] Split container discovery

- flocker/test/test_testtools.py
- flocker/testtools/__init__.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-1656
> Test the error case and fix it too.

- flocker/control/__init__.py
- flocker/control/_model.py
- flocker/control/_protocol.py
- flocker/control/test/test_model.py
- flocker/control/test/test_protocol.py
- flocker/node/agents/blockdevice.py
- flocker/node/agents/test/test_blockdevice.py
- flocker/node/test/test_deploy.py
- flocker/node/test/test_loop.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-1654
Note this PR is not against master. Make sure to review #1276 first. When all the PRs in this issue are accepted I'll merge them and merge the result into master.
> Nonmanifest datasets floc 1655

- flocker/control/__init__.py
- flocker/control/_clusterstate.py
- flocker/control/_model.py
- flocker/control/_protocol.py
- flocker/control/test/test_clusterstate.py
- flocker/control/test/test_httpapi.py
- flocker/control/test/test_model.py
- flocker/control/test/test_protocol.py
- flocker/node/_deploy.py
- flocker/node/_loop.py
- flocker/node/agents/blockdevice.py
- flocker/node/agents/test/test_blockdevice.py
- flocker/node/test/test_deploy.py
- flocker/node/test/test_loop.py
- flocker/node/testtools.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-1654
Note this PR is not against master. Make sure to review #1276 first. When all the PRs in this issue are accepted I'll merge them and merge the result into master.
> Multiple discovery floc 1654

- flocker/control/__init__.py
- flocker/control/_clusterstate.py
- flocker/control/_model.py
- flocker/control/_protocol.py
- flocker/control/httpapi.py
- flocker/control/test/test_clusterstate.py
- flocker/control/test/test_httpapi.py
- flocker/control/test/test_model.py
- flocker/control/test/test_protocol.py
- flocker/node/_deploy.py
- flocker/node/_loop.py
- flocker/node/agents/blockdevice.py
- flocker/node/agents/test/test_blockdevice.py
- flocker/node/test/test_deploy.py
- flocker/node/test/test_loop.py
- flocker/node/testtools.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-1650
> Accept an invariant parameter in pmap_field.

- flocker/control/httpapi.py
- flocker/control/schema/endpoints.yml
- flocker/control/test/test_httpapi.py
https://clusterhq.atlassian.net/browse/FLOC-1660
> [FLOC-1660] Configuration API endpoint

- docs/gettinginvolved/infrastructure/release-process.rst
> Getting started release process floc 1592

- vagrant/dev/Vagrantfile
https://clusterhq.atlassian.net/browse/FLOC-1648
This addresses the failure in the issue. There appear to be other issues, but they can be addressed separately.
> [FLOC-1648] Don't enable shared folders when building dev box.

- docs/gettinginvolved/infrastructure/documentation.rst
https://clusterhq.atlassian.net/browse/FLOC-1695
> [FLOC-1695] Adjust documentation / and /en/ redirects to match reality.

- admin/acceptance.py
- admin/run-acceptance-tests
- admin/runner.py
- admin/test/test_runner.py
- admin/vagrant.py
- flocker/testtools/__init__.py
https://clusterhq.atlassian.net/browse/FLOC-1675
> [FLOC-1675] Switch run-acceptance-tsts to use spawnProcess.

- admin/build_targets/centos-7/Dockerfile
- admin/build_targets/fedora-20/Dockerfile
- admin/build_targets/ubuntu-14.04/Dockerfile
- setup.py
https://clusterhq.atlassian.net/browse/FLOC-1707
> Update to Twisted 15.1.

- flocker/node/_loop.py
- flocker/node/test/test_loop.py
https://clusterhq.atlassian.net/browse/FLOC-1357
> [FLOC-1357] Log errors in the convergence loop, and then continue to next iteration.

- admin/build_targets/centos-7/Dockerfile
- admin/build_targets/fedora-20/Dockerfile
- admin/build_targets/ubuntu-14.04/Dockerfile
- admin/packaging.py
- admin/test/test_packaging.py
- docs/gettingstarted/index.rst
- flocker/ca/__init__.py
- flocker/ca/_ca.py
- flocker/ca/_script.py
- flocker/ca/test/__init__.py
- flocker/ca/test/test_ca.py
- flocker/ca/test/test_script.py
- flocker/testtools/__init__.py
- setup.py
- vagrant/tutorial/cache.sh
Fixes https://clusterhq.atlassian.net/browse/FLOC-1636
If one is interested in manual verification of the generated certificate, test like so:
```
(flocker1)dave@dave-ThinkPad-X230:~/flocker$ flocker-ca initialize whatever
Created cluster.key and cluster.crt. Please keep cluster.key secret, as anyone who can access will be able to control your cluster.
(flocker1)dave@dave-ThinkPad-X230:~/flocker$ openssl x509 -in cluster.crt -text -noout
Certificate:
Data:
Version: 1 (0x0)
Serial Number:
fc:1e:92:1e:75:c8:d2:4b:02:ff:87:30:c1:a4:ad:dc
Signature Algorithm: sha256WithRSAEncryption
Issuer: CN=whatever
Validity
Not Before: Apr  8 09:39:31 2015 GMT
Not After : Apr  3 09:39:31 2035 GMT
Subject: CN=whatever
Subject Public Key Info:
Public Key Algorithm: rsaEncryption
Public-Key: (4096 bit) …
```
> [FLOC-1636] CA initialization

- flocker/node/testtools.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-1658
> Turn any connection attempt error into a skip reason

- flocker/node/agents/blockdevice.py
- flocker/node/agents/test/test_blockdevice.py
Fixes <https://clusterhq.atlassian.net/browse/FLOC-1492>.  Prepares the way for <https://clusterhq.atlassian.net/browse/FLOC-1504>.
> Loopback volume resize floc 1492

- flocker/provision/_install.py
- setup.py
https://clusterhq.atlassian.net/browse/FLOC-1722
> [FLOC-1722] Remove unused code from acceptance tests.

- flocker/common/__init__.py
- flocker/common/_thread.py
- flocker/common/test/test_thread.py
- flocker/node/agents/blockdevice.py
- flocker/node/agents/test/test_blockdevice.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-1549
> [FLOC-1549] Auto-async wrapper for IBlockDeviceAPI  providers.

- flocker/ca/__init__.py
- flocker/ca/_ca.py
- flocker/ca/_script.py
- flocker/ca/functional/test_ca.py
- flocker/ca/test/test_ca.py
> [FLOC-1638] Node certificate

- flocker/cli/functional/test_deploy_script.py
- flocker/cli/functional/test_sshconfig.py
https://clusterhq.atlassian.net/browse/FLOC-698
> [FLOC-698] Kill ssh-agent at end of tests.

- flocker/acceptance/test_api.py
- flocker/node/agents/functional/test_cinder_behaviour.py
- flocker/node/functional/test_deploy.py
- flocker/node/functional/test_docker.py
- flocker/node/test/test_docker.py
- flocker/testtools/__init__.py
- flocker/volume/filesystems/zfs.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-1779
> More descriptive random names

- flocker/ca/test/test_script.py
> [FLOC-1782] CA Script Test

- flocker/node/agents/blockdevice.py
- flocker/node/agents/test/test_blockdevice.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-1499
Based on https://github.com/ClusterHQ/flocker/pull/1333 (to be merged shortly)
> BlockDeviceDeployer unmount logic

- flocker/node/agents/blockdevice.py
- flocker/node/agents/test/test_blockdevice.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-1498
> BlockDeviceDeployer mount support

- docs/advanced/api_examples.yml
- docs/spelling_wordlist.txt
- flocker/acceptance/testtools.py
- flocker/control/httpapi.py
- flocker/control/schema/endpoints.yml
- flocker/control/schema/types.yml
- flocker/control/test/test_httpapi.py
- flocker/control/test/test_schemas.py
> [FLOC-1632] Documentation and other improvements for list nodes API endpoint

- docs/gettinginvolved/infrastructure/release-process.rst
- setup.py
Reverts ClusterHQ/flocker#1360
> Revert "Replace gsutil with awsutil"

- flocker/node/agents/blockdevice.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-1820
> Reference them.

- flocker/node/agents/blockdevice.py
- flocker/node/agents/cinder.py
- flocker/node/agents/ebs.py
- flocker/node/agents/test/test_blockdevice.py
- flocker/node/script.py
- flocker/test/test_testtools.py
- flocker/testtools/__init__.py
Design for https://clusterhq.atlassian.net/browse/FLOC-1809
> [FLOC-1809] Cloudy identifier

- flocker/node/agents/cinder.py
- flocker/node/agents/ebs.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-1825
> Define some test-case-names.

- admin/test/test_release.py
- admin/yum.py
https://clusterhq.atlassian.net/browse/FLOC-1823
> [FLOC-1823] Don't leak build path into dpkg repository metadata.

- docs/gettinginvolved/infrastructure/release-process.rst
- setup.py
Reverts ClusterHQ/flocker#1373 See comments on https://clusterhq.atlassian.net/browse/FLOC-1738 explaining why.
> Revert "Revert "Replace gsutil with awsutil""

- admin/build_targets/centos-7/Dockerfile
- admin/build_targets/fedora-20/Dockerfile
- admin/build_targets/ubuntu-14.04/Dockerfile
- flocker/common/__init__.py
- flocker/common/_thread.py
- flocker/common/test/test_openstack.py
- setup.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-1838
Depends on #1388
[Relative diff](https://github.com/ClusterHQ/flocker/compare/blockdevice-factory-FLOC-1836...openstack-logging-FLOC-1838)
> OpenStack logging tools

- flocker/ca/functional/test_ca.py
> [FLOC-1766] Skip tests in setup if flocker-ca not installed

- docs/advanced/api.rst
- flocker/node/script.py
- flocker/node/test/test_script.py
- flocker/provision/_install.py
This adds a few more lines to copy/paste for the user but adds no functionality.
It was split out of FLOC-1791.
There is some duplication but the agents (and their tests) will be merged in FLOC-1791.
> Backend section floc 1881

- admin/package-files/systemd/flocker-agent.service
- admin/package-files/upstart/flocker-agent.conf
- admin/packaging.py
- admin/test/test_packaging.py
- docs/indepth/tutorial/vagrant-setup.rst
- flocker/node/functional/test_script.py
- flocker/node/script.py
- flocker/node/test/test_script.py
- setup.py
This PR is ready to be looked at but the only tests for the crux of this are the acceptance tests which have not run yet.
It is meant to change nothing for the user but be a step towards FLOC-1791.
> Remove flocker zfs agent floc 1892

- docs/advanced/api.rst
- docs/indepth/installation.rst
- docs/spelling_wordlist.txt
- flocker/control/httpapi.py
- flocker/restapi/_infrastructure.py
- flocker/restapi/docs/publicapi.py
- flocker/restapi/docs/test/test_publicapi.py
- flocker/restapi/test/test_infrastructure.py
https://clusterhq.atlassian.net/browse/FLOC-1867
> Add API headers FLOC 1867

- admin/acceptance.py
- docs/gettinginvolved/acceptance-testing.rst
Fixes https://clusterhq.atlassian.net/browse/FLOC-1934
> [FLOC-1934] First (untested) attempt at giving a no-pull option

- flocker/node/agents/ebs.py
- flocker/node/agents/functional/test_ebs.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-1835
> [FLOC-1835] Add Boto debug config option.

- docs/gettinginvolved/infrastructure/release-process.rst
- docs/gettingstarted/index.rst
Fixes https://clusterhq.atlassian.net/browse/FLOC-1999
> [FLOC-1999] Vagrant gsg floc 1999

- flocker/ca/functional/test_validation.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-1894
> [FLOC-1894] Clean up server-side connections

- admin/build_targets/centos-7/Dockerfile
- admin/build_targets/fedora-20/Dockerfile
- admin/build_targets/ubuntu-14.04/Dockerfile
- setup.py
Fixes: https://clusterhq.atlassian.net/browse/FLOC-2029
> [FLOC-2029] Pin python-keystoneclient

- admin/vagrant-acceptance-targets/centos-7/Vagrantfile
- docs/using/tutorial/Vagrantfile.template
- vagrant/tutorial/post-reboot-bootstrap.py
https://clusterhq.atlassian.net/browse/FLOC-2052
> [FLOC-2052] Tell NetworkManager to reload config.

- flocker/control/_model.py
- flocker/node/_deploy.py
- flocker/node/agents/test/test_blockdevice.py
- flocker/node/test/test_deploy.py
Fixes: https://clusterhq.atlassian.net/browse/FLOC-2012
> [FLOC-2012] Handle unknown other node state somewhat better in P2PManifestationDeployer

- flocker/node/_deploy.py
- flocker/node/functional/test_deploy.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-2003
> [FLOC-2003] Command line introspection was wrong, resulting in unnecessary application restart

- admin/acceptance.py
https://clusterhq.atlassian.net/browse/FLOC-2070
> Always keep acceptance cluster if --keep specified.

- docs/conf.py
- flocker/docs/prompt_patched.py
- setup.py
Upstream patch submitted as https://github.com/sbrunner/sphinx-prompt/pull/3
This temporarily uses the code from that patch in the Flocker code.
> Add patched prompt directive that works on Safari and Chrome

- docs/gettinginvolved/infrastructure/release-process.rst
Fixes https://clusterhq.atlassian.net/browse/FLOC-2118
> [FLOC-2118] Release improvements for 0.4.1dev3

- docs/gettingstarted/fig.yml
Fixes https://clusterhq.atlassian.net/browse/FLOC-1789
> [FLOC-1789] Change docker image name

- flocker/node/agents/_logging.py
- flocker/node/agents/ebs.py
- flocker/node/agents/functional/test_ebs.py
Based on `boto-config-FLOC-2028`.
> [FLOC-2131] Boto configuration changes

- NEWS
- docs/gettinginvolved/plugins.rst
- docs/releasenotes/index.rst
- docs/using/installing/index.rst
Fixes https://clusterhq.atlassian.net/browse/FLOC-2148
> [FLOC-2148] Release notes floc 2148

- docs/using/installing/index.rst
Robs feedback comments:
https://docs.google.com/document/d/12LZHegqXSCLaEB2OPd4Dcg5rHRuU1rK1Xz53qyXwdb8/edit#heading=h.obzsgevhppff
and
https://docs.google.com/document/d/1aTIrDN6YGq6I7Qc1MwFKxnooO9yz7qZ_mFtNo8bOFfg/edit#heading=h.5crjnr15nsco
(there is some overlap on these drive docs)
> [FLOC-2149] Update to the AWS install section of the Installation doc

- docs/gettinginvolved/infrastructure/release-process.rst
- docs/releasenotes/index.rst
- docs/using/installing/index.rst
Fixes https://clusterhq.atlassian.net/browse/FLOC-2159
> [FLOC-2159] Warning in pip instructions

- admin/release.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-2168
> [FLOC-2168] Fixed kwarg

- flocker/node/agents/ebs.py
flocker.node.agents.functional.test_ebs
EBSBlockDeviceAPIInterfaceTests
test_attach_destroyed_volume ...                                       [OK]
-------------------------------------------------------------------------------
Ran 1 tests in 6.590s
> [FLOC-2150] Wait for delete to complete before returning from destroy_volume.

- docs/reference/api_examples.yml
- flocker/control/_model.py
- flocker/control/httpapi.py
- flocker/control/schema/endpoints.yml
- flocker/control/schema/types.yml
- flocker/control/test/test_httpapi.py
- flocker/control/test/test_model.py
- flocker/control/test/test_schemas.py
- flocker/node/agents/blockdevice.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-2160
> [FLOC-2160] Report non-manifest datasets in /state/datasets

- flocker/node/agents/ebs.py
Fixes: https://clusterhq.atlassian.net/browse/FLOC-2165
> [FLOC-2165] EBS: ``list_volumes`` should list volumes in all states.

- flocker/provision/_aws.py
Not actually tested in anyway, so chances are this won't actually pass buildbot at all.
> [FLOC-2198] Attempt to retry SSH key installation on AWS

- admin/acceptance.py
https://clusterhq.atlassian.net/browse/FLOC-2225
> [FLOC-2225] Show acceptance error messages on the terminal

- flocker/acceptance/testtools.py
Fixes: https://clusterhq.atlassian.net/browse/FLOC-2224
> [FLOC-2224] Don't expect all datasets to have a path

- docs/_themes/clusterhq/layout_docs.html
- docs/_themes/clusterhq/static/css/docs.css
> Update top navigation in docs inline with new site

- docs/gettinginvolved/infrastructure/release-process.rst
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/1569)
> [FLOC-2193] Move merging PR

- docs/using/tutorial/volumes.rst
Fixes: https://clusterhq.atlassian.net/browse/FLOC-2238
> [FLOC-2238] remove reference to "ZFS-based volume manager"

- admin/aws.py
- admin/functional/test_aws.py
- admin/release.py
- admin/test/test_release.py
PR against 0.9.0pre1 of Vagrant fix from FLOC-2191
> [FLOC-2242] Release maintenance/flocker 0.9.0pre1/fix content type

- NEWS
- admin/aws.py
- admin/functional/test_aws.py
- admin/release.py
- admin/test/test_release.py
- docs/releasenotes/index.rst
- flocker/acceptance/testtools.py
Pre-tag review for 0.9.0pre1
Fixes https://clusterhq.atlassian.net/browse/FLOC-2223
Follow the review process at http://doc-dev.clusterhq.com/gettinginvolved/infrastructure/release-process.html#pre-tag-review-process
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/1570)
> [FLOC-2223] Release Flocker 0.9.0pre1

- flocker/node/script.py
- flocker/node/test/test_script.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/1536)
> [FLOC-2136] Reliable agent IP detection

- NEWS
All failing tests have, I think, been deemed acceptable.
Please follow the "Pre-tag Review Process" at:
http://doc-dev.clusterhq.com/gettinginvolved/infrastructure/release-process.html#pre-tag-review-process
> [FLOC-2254] Release Flocker 0.9.0

- docs/_themes/clusterhq/layout_docs.html
> Upper case C in "use cases"

- flocker/provision/_aws.py
Required to enable client testing on AWS
> [FLOC-2260] Add Ubuntu 15.04 to AWS provisioner

- admin/release.py
- admin/test/test_release.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-2249
> [FLOC-2249] Release base

- docs/using/tutorial/vagrant-setup.rst
Fixes FLOC-2151 via documenting the workaround for loss of static IP config,
> [FLOC-2151] Add warning about restarting VMs to tutorial doc

- flocker/node/_deploy.py
- flocker/node/agents/test/test_blockdevice.py
- flocker/node/test/test_deploy.py
- flocker/node/testtools.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-2255
This is stuff I couldn't help but clean up before attempting to fix FLOC-2240.
> [FLOC-2255] Refactoring, code cleanup, and additional test coverage

- flocker/node/agents/cinder.py
Fixes: https://clusterhq.atlassian.net/browse/FLOC-2278
> [FLOC-2278] A more reliable implementation of compute_instance_id for OpenStack 

- flocker/node/agents/_logging.py
- flocker/node/agents/ebs.py
- flocker/node/agents/functional/test_ebs.py
Fixes: https://clusterhq.atlassian.net/browse/FLOC-1953
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/1568)
> [FLOC-1953] EBS: retry attach_volume 

- flocker/acceptance/test_postgres.py
Already merged into master. Don't actually expect these tests to pass - that will be in follow up PR #1606.
> [FLOC-2285] Postgres tests improvements

- flocker/node/_deploy.py
- flocker/node/agents/test/test_blockdevice.py
- flocker/node/test/test_deploy.py
- flocker/node/testtools.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-2269
1.0.0pre1 PR corresponding to #1582
> [FLOC-2269] Backport ApplicationNodeDeployer

- flocker/node/_change.py
- flocker/node/_deploy.py
- flocker/node/test/test_deploy.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-2271
Backport of #1598
> [FLOC-2271] Backport ApplicationNodeDeployer volume size-related calculations fixes

- flocker/node/_change.py
- flocker/node/_deploy.py
- flocker/node/test/test_deploy.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-2240
Note this is against master because a dependency hasn't been merged into 1.0.0pre1 yet.  I'll do 1.0.0pre1 after that dependency is merged but doing things in the right order now would prevent this from going up for review.
> [FLOC-2240] Don't restart for dataset size changes

- flocker/node/agents/_logging.py
- flocker/node/agents/cinder.py
Reverts ClusterHQ/flocker#1607
This introduced a regression into master on the `flocker-lint` builder.
http://build.clusterhq.com/builders/flocker-lint/builds/7759
> Revert "[FLOC-2295] Output OpenStack logs to Eliot."

- flocker/acceptance/test_deployment.py
https://clusterhq.atlassian.net/browse/FLOC-2283
> [FLOC-2283] Use a realistic blocksize in test_application_volume_quotas.

- docs/using/tutorial/vagrant-setup.rst
Fixes https://clusterhq.atlassian.net/browse/FLOC-2307
> [FLOC-2307] Release maintenance/flocker 1.0.0pre1/document vagrant power cycle

- flocker/node/agents/ebs.py
- flocker/node/agents/functional/test_ebs.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-2296
> [FLOC-2296] Release maintenance/flocker 1.0.0pre1/reused ebs device

- LICENSE
- admin/test/test_license.py
- admin/test/test_packaging.py
- admin/test/test_release.py
- admin/testtools.py
- docs/gettinginvolved/infrastructure/release-process.rst
Fixes https://clusterhq.atlassian.net/browse/FLOC-1968
> [FLOC-1968] License

- flocker/restapi/docs/test/test_publicapi.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-2306
> [FLOC-2306] Publicapi skip

- flocker/node/agents/cinder.py
Fixes: https://clusterhq.atlassian.net/browse/FLOC-2294
Merged 65f9bf0e02938dcba06da2a80180c6acd98326fe (PR #1600) into master
> [FLOC-2294] A more reliable implementation of compute_instance_id for OpenStack

- docs/releasenotes/index.rst
Originally done against 1.0.0 release branch.
> [FLOC-2300] Release notes warning

- docs/gettinginvolved/infrastructure/release-process.rst
Fixes https://clusterhq.atlassian.net/browse/FLOC-2232
> [FLOC-2232] Added JIRA prerequisite

- docs/using/installing/index.rst
https://clusterhq.atlassian.net/browse/FLOC-2319
> mkdir /etc/flocker on every node.

- flocker/acceptance/test_deployment.py
> [FLOC-2284] Realistic blocksize in quota test

- flocker/node/agents/_logging.py
- flocker/node/agents/cinder.py
> [FLOC-2325] Cinder logging

- docs/using/installing/index.rst
See: https://github.com/ClusterHQ/flocker/pull/1630.
> [FLOC-2321] mkdir /etc/flocker everywhere

- README.rst
The wording for the Flocker introduction (lines 9-18) has been taken from the v1 marketing material, which also features here: https://docs.clusterhq.com/en/1.0.0/introduction/index.html#what-is-flocker
> [FLOC-2365] Update Readme Content

- docs/gettinginvolved/infrastructure/release-process.rst
Fixes https://clusterhq.atlassian.net/browse/FLOC-2314
> [FLOC-2314] Reduce env variable

- flocker/provision/_install.py
- flocker/provision/test/test_install.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-1620
> [FLOC-1620] Centos latest

- NEWS
- docs/releasenotes/index.rst
- docs/using/administering/index.rst
- docs/using/administering/upgrading.rst
I have not actually previewed the result, please review carefully!
> [FLOC-2456] Some news entries and documentation for 1.0.1

- docs/gettinginvolved/plugins.rst
- docs/releasenotes/index.rst
- docs/using/installing/index.rst
Fixes https://clusterhq.atlassian.net/browse/FLOC-2458
Merge #1677 into release/flocker-1.0.0 branch
> [FLOC-2458] Add EMC links to Install doc

- flocker/node/agents/blockdevice.py
- flocker/node/agents/test/test_blockdevice.py
Reverts ClusterHQ/flocker#1668
> Revert "[FLOC-2371] Blkid uuid"

- flocker/node/agents/ebs.py
- flocker/node/agents/functional/test_ebs.py
- flocker/node/agents/test/test_blockdevice.py
- flocker/node/agents/test/test_ebs.py
Fixes: https://clusterhq.atlassian.net/browse/FLOC-2465
Merges #1684 into master.
> [FLOC-2465] Ebs device name mapping

- NEWS
- docs/releasenotes/index.rst
- docs/using/administering/index.rst
- docs/using/administering/upgrading.rst
Fixes: https://clusterhq.atlassian.net/browse/FLOC-2466
Merges #1685 to master.
> [FLOC-2466] Some news entries and documentation for 1.0.1

- CONTRIBUTING.rst
- README.rst
https://clusterhq.atlassian.net/browse/FLOC-2479
> [FLOC-2479] Add UserVoice to the README.

- docs/_themes/clusterhq/static/css/docs.css
> [FLOC-2485] Font size should be set once, not on nested sections

- docs/_themes/clusterhq/static/css/docs.css
> [FLOC-2484] Make padding top and bottom the same on headers

- docs/_themes/clusterhq/static/css/docs.css
Reverts ClusterHQ/flocker#1702 (shouldn't have been merged)
> Revert "[FLOC-2484] Make padding top and bottom the same on headers"

- docs/using/installing/index.rst
(cherry picked from commit df1675516e99d7f3de8f8e8a014ee4ac4908d389)
> [FLOC- 2460] fix broken link

- docs/using/authentication.rst
(cherry picked from commit dbbc2a6984fc770e840929572b69ff65418484de)
> [FLOC-2461] fix broken link

- docs/using/authentication.rst
Reverts ClusterHQ/flocker#1710
> Revert "[FLOC-2461] fix broken link"

- docs/using/installing/index.rst
Reverts ClusterHQ/flocker#1709
> Revert "[FLOC- 2460] fix broken link"

- setup.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-2506
See #1706 for comments on the approach.
> pin pyasn1-modules

- NEWS
- docs/reference/api_examples.yml
- docs/releasenotes/index.rst
- docs/using/config/configuration.rst
- flocker/control/httpapi.py
- flocker/node/_deploy.py
- flocker/node/test/test_deploy.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-2467
Update of https://github.com/ClusterHQ/flocker/pull/1696 (changing branch name ... which matters ...)
> Release maintenance/flocker 1.0.1/disable restart policies floc 2467

- docs/using/config/configuration.rst
> [FLOC-2399] Allow either single app string or list in deployment config

- admin/release.py
- admin/test/test_release.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-2370
> [FLOC-2370] Redirects

- NEWS
- admin/package-files/rsyslog/flocker.conf
- admin/packaging.py
- admin/test/test_packaging.py
- docs/releasenotes/index.rst
- docs/spelling_wordlist.txt
- docs/using/administering/upgrading.rst
Corresponding master fix for #1729.
> [FLOC-2542] CentOS logs

- flocker/testtools/__init__.py
`logged_run_process` has helped us debug issues with failing builders, but we're struggling to associate output from subprocesses with the correct subprocess. 
This (I think) fixes that by making sure that output from the subprocess is logged within the context of the action that corresponds to running the process.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/1731)
> Log subprocess output in the context of the subprocess action

- flocker/acceptance/test_deployment.py
- flocker/acceptance/test_moving_applications.py
- flocker/acceptance/test_moving_data.py
- flocker/acceptance/test_ports.py
- flocker/acceptance/test_postgres.py
- flocker/acceptance/testtools.py
> [FLOC-2355] Fix test ports Mongo

- flocker/acceptance/test_api.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-2488
> [FLOC-2488] Increase the timeout on test_move_container_with_dataset

- admin/package-files/upstart/flocker-container-agent.conf
- admin/package-files/upstart/flocker-control.conf
- admin/package-files/upstart/flocker-dataset-agent.conf
- flocker/common/functional/test_script.py
- flocker/common/script.py
- flocker/common/test/test_script.py
- flocker/testtools/__init__.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-2595
Reviewed and accepted in #1750
Based on design in #1747
> [FLOC-2595] An option to allow logging directly to a file

- flocker/volume/functional/test_filesystems_zfs.py
See https://clusterhq.atlassian.net/browse/FLOC-2509
This PR overrides #1718
> zfs test_maximum_size_enforced: test the right scenario and verify that

- admin/homebrew.py
- admin/test/test_homebrew.py
- dev-requirements.txt
- requirements.txt
https://clusterhq.atlassian.net/browse/FLOC-2605
> [FLOC-2605] Use explicit dependencies for homebrew.

- NEWS
- docs/releasenotes/index.rst
Ready for pre-tag review:
* http://doc-dev.clusterhq.com/gettinginvolved/infrastructure/release-process.html#pre-tag-review-process
Fixes: https://clusterhq.atlassian.net/browse/FLOC-2616
> [FLOC-2616] Release Flocker 1.0.3

- docs/using/installing/index.rst
> Typo (duplicate "named")

- docs/gettinginvolved/infrastructure/release-process.rst
Fixes https://clusterhq.atlassian.net/browse/FLOC-2512
> [FLOC-2512] Staging release

- docs/conf.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-695
Manually tested this
Output before:
```
make html
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.3.1
Initializing Spelling Checker
loading translations [en]... done
loading pickled environment... not yet created
loading intersphinx inventory from http://docs.python.org/objects.inv...
building [mo]: targets for 0 po files that are out of date
WARNING: unsupported build info format in u'/Users/bridget/work/flocker/docs/_build/html/.buildinfo', building all
building [html]: targets for 56 source files that are out of date
updating environment: 56 added, 0 changed, 0 removed
reading sources... [100%] using/tutorial/volumes
looking for now-outdated files... none found
pickling environment... done
checking …
```
> Change intersphinx to not load python.org metadata

- docs/concepts/security.rst
- docs/install/install.rst
- docs/using/authentication.rst
> [FLOC 2233] Replace instances of "authorised" with "authorized"

- docs/install/install.rst
> [FLOC 2266] Change ZoL link on installing doc

- docs/concepts/index.rst
- docs/install/index.rst
- docs/using/index.rst
> [FLOC 2706] Fix the disappearance of sub topics under Install/Using/Concept headers

- docs/_themes/clusterhq/layout_docs.html
- docs/_themes/clusterhq/static/css/docs.css
> [FLOC-2539] Change navigation link to "Install & Docs"

- docs/labs/docker-plugin.rst
Fixes https://clusterhq.atlassian.net/browse/FLOC-2722
> Use more stable link to docker volumes plugin docs

- flocker/acceptance/endtoend/test_cli.py
- flocker/acceptance/testtools.py
> [FLOC-2726] Move CLI utility functions to CLI tests

- docs/install/install-node.rst
> [FLOC 2237] Add port 27017 requirement to AWS instructions

- docs/_themes/clusterhq/layout_docs.html
we need to test that thIs works on the subdomain before merging. If it does not function correctly - a new site on heatmap.me needs to be added.
Please don't merge beforehand.
Fixes FLOC-2772
> [FLOC-2772] Add heatmap.me snippet to the docs template

- docs/config/configuring-nodes-storage.rst
> [FLOC 2265] Specify that only one backend can be chosen

- docs/config/configuring-nodes-storage.rst
> [FLOC 2411] Specify that hostname config must be correct

- tox.ini
Also includes some speedups courtesy of @achanda.
> [FLOC-2274] Unbreak tox

- flocker/apiclient/__init__.py
- flocker/apiclient/_client.py
- flocker/control/test/test_httpapi.py
- flocker/dockerplugin/__init__.py
- flocker/dockerplugin/_api.py
- flocker/dockerplugin/schema/endpoints.yml
- flocker/dockerplugin/schema/types.yml
- flocker/dockerplugin/test/__init__.py
- flocker/dockerplugin/test/test_api.py
- flocker/dockerplugin/test/test_schemas.py
- flocker/restapi/testtools.py
- setup.py
1. Builds on #1825, which is mergeable when buildbot is happy. Hopefully by the time you're reviewing this you can click Merge yourself.
2. Relevant docs: https://github.com/docker/docker/blob/master/docs/extend/plugins_volume.md#volumedrivercreate
> [FLOC-2784] Docker plugin: create volume

- flocker/dockerplugin/_api.py
- flocker/dockerplugin/schema/endpoints.yml
- flocker/dockerplugin/test/test_api.py
- flocker/dockerplugin/test/test_schemas.py
Relevant Docker docs: https://github.com/docker/docker/blob/master/docs/extend/plugins_volume.md#volumedriverpath
> [FLOC-2786] Docker plugin get path API

- NEWS
- docs/releasenotes/index.rst
First part of the release, please follow http://doc-dev.clusterhq.com/gettinginvolved/infrastructure/release-process.html#pre-tag-review-process. There is WIP which will be worth putting in the NEWS / release notes when done but nothing finished and new that I thought should go into NEWS / release notes.
> [FLOC-2847] Release/flocker 1.1.0rc1

- docs/gettinginvolved/infrastructure/release-process.rst
Fixes https://clusterhq.atlassian.net/browse/FLOC-2235
> [FLOC-2235] Add access to Drive requirement

- docs/gettinginvolved/infrastructure/release-process.rst
Fixes https://clusterhq.atlassian.net/browse/FLOC-2328
> [FLOC-2328] You need to be able to force builds on BuildBot to do a release

- NEWS
> [FLOC-2868] Release 1.1.0

- flocker/apiclient/_client.py
- flocker/apiclient/test/test_client.py
- flocker/dockerplugin/test/test_api.py
> [FLOC-2864] Flocker API client delete datasets

- NEWS
Do not merge yet. I think that this can be reviewed without waiting for more than the docs builder.
https://clusterhq.atlassian.net/browse/FLOC-2870
> [FLOC-2870] Release/flocker 1.2.0.dev1

- docs/gettinginvolved/client-testing.rst
- docs/labs/weave.rst
Fixes https://clusterhq.atlassian.net/browse/FLOC-2875
> [FLOC-2875] Links floc 2875

- flocker/node/functional/test_docker.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-2880
Replaces the test double with tested use of the real type.  Still not what I'd call ideal but there's not much we can easily do about the fact that the way `Response` is made to be used is error prone.
> [FLOC-2880] Switch to using the real `requests.Response`

- build.yaml
> fix typo in build.yaml \ -> /

- flocker/control/test/test_persistence.py
Using github as a way of showing diffs.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/1862)
> Strategy for nodes with volumes

- docs/install/install-node.rst
> [FLOC 2905] Fix broken link in install node doc

- docs/using/examples/environment.rst
> [FLOC 1034] Remove SHOW DATABASE step in mysql document

- NEWS
- docs/releasenotes/index.rst
> [FLOC-2921] Release Flocker 1.2.0

- docs/config/configuring-authentication.rst
Fixes 2339
This issue resolves the feedback from @myechuri, following an installation run-through.
Note that this only fixes point 4 in the issue. I think points 1 - 3 have already been addressed in previous PRs. Please advise if that is not the case.
> [FLOC 2339] Update to authentication docs from MY feedback

- AUTHORS.rst
- docs/conf.py
- docs/gettinginvolved/authors.rst
Fixes https://clusterhq.atlassian.net/browse/FLOC-2928
> [FLOC-2928] Don't spellcheck the authors

- AUTHORS.rst
- flocker/node/_loop.py
Traceback (most recent call last):
File "/usr/local/bin/flocker-dataset-agent", line 7, in <module>
from flocker.node.script import flocker_dataset_agent_main
File "/usr/local/lib/python2.7/dist-packages/flocker/node/__init__.py", line 17, in <module>
from .script import BackendDescription, DeployerType
File "/usr/local/lib/python2.7/dist-packages/flocker/node/script.py", line 37, in <module>
from ._loop import AgentLoopService
File "/usr/local/lib/python2.7/dist-packages/flocker/node/_loop.py", line 395, in <module>
class AgentLoopService(object, MultiService):
TypeError: Error when calling the metaclass bases
Cannot create a consistent method resolution
order (MRO) for bases object, MultiService
> Fix Running MRO error:

- build.yaml
- jobs.groovy.j2
Added a lot of documentation about the build.yaml and the jobs.groovy.j2
> improve commenting in build.yaml, jobs.groovy.j2

- admin/yum.py
- docs/gettinginvolved/infrastructure/release-process.rst
A few simple changes to smooth over the release process a little bit, based on my experience of completing the 1.2.0 release.
> [FLOC-2939] Release docs improvements

- docs/reference/api_examples.yml
- flocker/control/httpapi.py
- flocker/control/schema/endpoints.yml
- flocker/control/schema/types.yml
- flocker/control/test/test_httpapi.py
- flocker/control/test/test_schemas.py
Builds on and refactors #1901 so that should be reviewed first.
> [FLOC-2739] Delete leases endpoint

- docs/reference/api_examples.yml
- flocker/control/_persistence.py
- flocker/control/httpapi.py
- flocker/control/test/test_httpapi.py
- flocker/control/test/test_persistence.py
Builds on #1906 so review that first.
> [FLOC-2738] API endpoint for renewing leases

- flocker/control/_config.py
- flocker/control/schema/types.yml
- flocker/control/test/test_schemas.py
> [FLOC-2965] Validate rest API UUIDs

- flocker/control/httpapi.py
https://clusterhq.atlassian.net/browse/FLOC-2969
> Fix typo in ConfigurationAPIUserV1.acquire_lease docstring.

- flocker/apiclient/__init__.py
- flocker/apiclient/_client.py
- flocker/apiclient/test/test_client.py
- flocker/control/httpapi.py
Fixes: https://clusterhq.atlassian.net/browse/FLOC-2954
> [FLOC-2954] Leases support in API client

- flocker/control/_model.py
- flocker/control/test/test_model.py
> [FLOC-2976] Respect leases when updating node

- flocker/dockerplugin/_script.py
- flocker/provision/_install.py
> Change api.crt --> plugin.crt

- admin/acceptance.py
- flocker/acceptance/endtoend/test_dataset.py
- flocker/acceptance/testtools.py
- flocker/node/agents/cinder.py
- flocker/node/agents/functional/test_cinder.py
- flocker/provision/_common.py
A release maintenance branch for #1921 which has already been reviewed and approved.
> [FLOC-3009] Only use virtual disk serial number if the virtio_blk driver is detected

- flocker/provision/_install.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-3031
> [FLOC-3031] Upgrade in parallel

- admin/acceptance.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-3030
> [FLOC-3030] Let me specify the number of libcloud nodes to create and provision.

- admin/release.py
- admin/test/test_release.py
- admin/test/test_vagrant.py
- admin/vagrant.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-2871
> [FLOC-2871] Quote vagrant floc 2871

- CONTRIBUTING.rst
- docs/config/configuring-authentication.rst
- docs/gettinginvolved/acceptance-testing.rst
- docs/gettinginvolved/infrastructure/packaging.rst
- docs/gettinginvolved/infrastructure/release-process.rst
- docs/using/config/usage.rst
- docs/using/examples/environment.rst
- docs/using/examples/linking.rst
- docs/using/tutorial/exposing-ports.rst
- docs/using/tutorial/moving-applications.rst
- docs/using/tutorial/vagrant-setup.rst
- docs/using/tutorial/volumes.rst
> [FLOC 1612] Replace use of code-blocks with prompt in docs

- admin/package-files/systemd/flocker-container-agent.service
- flocker/acceptance/endtoend/test_dockerplugin.py
- flocker/acceptance/testtools.py
- flocker/testtools/__init__.py
> [FLOC-2947] Docker plugin persist restarts

- flocker/provision/_install.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-3033
> [FLOC-3033] Stop things before removing them

- flocker/node/_loop.py
- flocker/node/test/test_loop.py
- flocker/testtools/__init__.py
This is the backport of PR #1938 to the 1.3 branch. The change here is identical to the change in that PR.
> [FLOC-3071] Backport to Flocker 1.3 #1938 Send node state only on change

- flocker/control/_persistence.py
- flocker/control/test/test_persistence.py
Fixes: https://clusterhq.atlassian.net/browse/FLOC-3081
> [FLOC-3081] Only persist the configuration when leases have changed

- admin/acceptance.py
- flocker/provision/_common.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-3089
I have tested this by successfully running acceptance tests against Vagrant.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/1966)
> Run acceptance tests floc 3089

- docs/concepts/architecture.rst
- docs/using/administering/debugging.rst
- flocker/control/script.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-3039
> [FLOC-3039] Enable profiling

- flocker/provision/_install.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-3104
> [FLOC-3104] Configure acceptance testing nodes in parallel

- flocker/control/test/test_protocol.py
- flocker/testtools/test/test_amp.py
Fixes: https://clusterhq.atlassian.net/browse/FLOC-3106
> [FLOC-3106] LoopbackAMPClient serialization

- flocker/control/_protocol.py
- flocker/control/test/test_protocol.py
Fixes: https://clusterhq.atlassian.net/browse/FLOC-3108
> [FLOC-3108] A big composeable AMP argument type

- NEWS
- docs/releasenotes/index.rst
https://clusterhq.atlassian.net/browse/FLOC-3115
> [FLOC-3115] Release flocker-1.4.0.

- docs/gettinginvolved/acceptance-testing.rst
Fixes https://clusterhq.atlassian.net/browse/FLOC-3126
> Changed key reference

- docs/gettinginvolved/infrastructure/release-process.rst
Fixes https://clusterhq.atlassian.net/browse/FLOC-3121
> Uncomment line which made a section be missed

- dev-requirements.txt
- flocker/node/_docker.py
- flocker/node/functional/test_docker.py
- requirements.txt
> [FLOC-3119] Cache inspected image data in memory

- docs/labs/installer.rst
Fixes 3163
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2008)
> [FLOC 3163] fix broken ref link

- flocker/node/agents/cinder.py
Fixes: https://clusterhq.atlassian.net/browse/FLOC-3159
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2006)
> [FLOC-3159] Bump timeout to 600.

- flocker/provision/_install.py
Fixes: https://clusterhq.atlassian.net/browse/FLOC-3070
This is an alternative #1936 that doesn't affect documentation.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2010)
> [FLOC-3032] Re-install flocker-docker-plugin on acceptance test upgrades

- docs/conf.py
- docs/gettinginvolved/plugins/building-driver.rst
Fixes 3177
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2013)
> [FLOC 3177] broken doc links

- admin/acceptance.py
- admin/test/test_acceptance.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-3188
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2020)
> [FLOC-3188] Make remote_logs.log JSON

- flocker/provision/_install.py
Currently, trying to run the client or acceptance tests for Flocker versions other than the latest version fails on Ubuntu, due to `apt` wanting to install the latest dependency rather than the requested dependency. e.g. running `admin/run-client-tests --distribution ubuntu-15.04 --flocker-version=1.2.0.dev1` fails with:
```
The following packages have unmet dependencies:
clusterhq-flocker-cli : Depends: clusterhq-python-flocker (= 1.2.0-0.dev.1) but 1.4.0-0.dev.1 is to be installed
E: Unable to correct problems, you have held broken packages.
```
This PR pins the version for any dependencies starting with `clusterhq-` to the same as the top-level package. Currently, the only such dependency is `clusterhq-python-flocker` which always must match the version number of the top-level …
> [FLOC-3012] Pin Ubuntu version for dependencies, to prevent apt conflicts

- docs/index.rst
- docs/labs/installer.rst
Fixes 3217
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2031)
> [FLOC 3217] Fix broken "tutmongo" ref links 

- docs/install/install-client.rst
Fixes 3244
Small typo change in install-client.rst
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2063)
> [FLOC 3244] change pre-requisite to prerequisite

- docs/concepts/volume.rst
- docs/introduction/flocker-supports.rst
- docs/tutorials_examples/tutorial/vagrant-setup.rst
Fixes 3237
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2064)
> [FLOC 3237] Replace use of command-line with command line

- docs/releasenotes/index.rst
Regularly scheduled release.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2034)
> [FLOC-3165] Release flocker 1.5.0

- docs/gettinginvolved/infrastructure/release-process.rst
https://clusterhq.atlassian.net/browse/FLOC-3048
I haven't tested this, but have verified the bit about closing the release PR.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/1997)
> [FLOC-3048] Add instructions for handling merge conflicts.

- docs/reference/api.rst
- flocker/apiclient/_client.py
- flocker/apiclient/test/test_client.py
Fixes: https://clusterhq.atlassian.net/browse/FLOC-3297
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2075)
> [FLOC-3297] Implement a version method to the FlockerClient

- docs/reference/api.rst
- flocker/apiclient/_client.py
- flocker/apiclient/test/test_client.py
- flocker/control/__init__.py
Fixes: https://clusterhq.atlassian.net/browse/FLOC-3298
Stacked on top of: https://github.com/ClusterHQ/flocker/pull/2075
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2084)
> [FLOC-3298] Add a list_nodes method to FlockerClient

- flocker/node/_loop.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-3352
Also applied the treatment to the other transition table in this module so it's also available for inspection by tools.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2109)
> [FLOC-3352] Global transition tables

- flocker/node/agents/test/test_cinder.py
Die evil code, dieee!! (I had a bit of a dull day, I need to steam out) - ps: sorry for fixing a bug adding a new one.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2131)
> Killing useless test. Darwin would be proud

- docs/_themes/clusterhq/layout_docs.html
The style of this widget is customisable via Zendesk however I have not been able to change much. 
When built locally, the live chat functions as expected.
Fixes FLOC-3389
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2135)
> [FLOC-3389] add zopim widget from zendesk

- admin/initialize-release
- admin/release.py
- admin/test/test_release.py
- docs/gettinginvolved/infrastructure/release-process.rst
Improve the release process, automate more of it, make less steps.
Fixes FLOC-3404.
Docs build for modified release instructions:
http://build.clusterhq.com/results/docs/release-improvements-FLOC-3404/build-11077/gettinginvolved/infrastructure/release-process.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2147)
> [FLOC-3404] Release improvements

- AUTHORS.rst
- docs/config/configuring-nodes-storage.rst
- docs/config/dell-configuration.rst
- docs/introduction/flocker-supports.rst
Fixes 3439
A page for the new Dell storage config was contributed in https://github.com/ClusterHQ/flocker/pull/2158.
This PR pulls in that change, with a small style amendment. It also adds Sean to our list of Authors.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2161)
> [FLOC 3439] Add the Dell storage config doc as provided by Stmcginnis

- docs/config/configuring-nodes-storage.rst
- docs/config/huawei-configuration.rst
- docs/config/nexenta-configuration.rst
- docs/introduction/flocker-supports.rst
- docs/spelling_wordlist.txt
Fixes 3438
Adds Huawei and Nexenta drivers to the list of supported storage drivers.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2166)
> [FLOC 3438]

- docs/install/setup-aws.rst
- docs/spelling_wordlist.txt
Fixes 3279
Addresses feedback from using our guide on setting up nodes using AWS.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2173)
> [FLOC 3279] Improvements to the AWS guide

- flocker/node/agents/blockdevice.py
- flocker/node/agents/test/test_blockdevice.py
This was split off from an approved PR so just needs to have green build.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2187)
> [FLOC-3460] Rename the class to be more general and clear.

- dev-requirements.txt
- flocker/control/test/test_persistence.py
https://clusterhq.atlassian.net/browse/FLOC-3471
I want to use this in #2175.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2189)
> [FLOC-3471] Upgrade hypothesis to 1.14.0.

- flocker/node/_deploy.py
- flocker/node/agents/blockdevice.py
https://clusterhq.atlassian.net/browse/FLOC-3489
> [FLOC-3489] Be more specific in arguments to `NotInUseDatasets`.

- flocker/node/agents/blockdevice.py
- flocker/node/agents/test/test_blockdevice.py
#2201 is an example of where we will need access to this state.
> [FLOC-3493] Add ATTACHED_ELSEWHERE state.

- flocker/acceptance/obsolete/test_containers.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-3486
> [FLOC-3486] Mark it as flaky.

- flocker/__init__.py
- flocker/cli/script.py
- flocker/control/_protocol.py
- flocker/control/httpapi.py
- flocker/control/test/test_protocol.py
Instead of a cache that is tied to a particular context, use a LRU cache so delayed updates also benefit from the cache.
> [FLOC-3473] Try to reduce control service load

- docs/_themes/clusterhq/layout_docs.html
- docs/_themes/clusterhq/static/css/docs.css
> [FLOC-3520] change docs nav to be inline with current website

- flocker/provision/_install.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-3247
> [FLOC-3247] Retry the Docker installation step.

- flocker/acceptance/obsolete/test_cli.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-3529
http://build.clusterhq.com/boxes-flocker?branch=test_deploy-is-flaky-FLOC-3529
> [FLOC-3529] Mark the flaky test as flaky

- dev-requirements.txt
- flocker/common/algebraic.py
- flocker/common/test/test_algebraic.py
- flocker/node/agents/blockdevice.py
- requirements.txt
https://clusterhq.atlassian.net/browse/FLOC-3495
> [FLOC-3495] Cleanup discovered dataset invariant

- docs/releasenotes/index.rst
https://clusterhq.atlassian.net/browse/FLOC-3542
Review Process: http://doc-dev.clusterhq.com/gettinginvolved/infrastructure/release-process.html#pre-tag-review-process
> [FLOC-3542] Release 1.8.0.

- flocker/node/agents/cinder.py
Fixes FLOC-1831. Note this change is sufficiently tested by a lack of regression in tests in `flocker.node.agents.functional.test_cinder` that utilise `wait_for_volume_state`.
> [FLOC-1831] Change cinder backend to retrieve expected ID only

- benchmark/metrics/test/test_cputime.py
Benchmarking tests were working on Ubuntu, but not on CentOS.
Some tests assumed that a process named `init` always existed. Fixed by using `systemd` if OS is CentOS.  Tests are skipped if not on Ubuntu or CentOS.
This problem was highlighted by change from Buildbot to Jenkins, which adds tests for the `benchmark` directory.
> [FLOC-3561] Select standard test process based on OS

- build.yaml
Fixes https://clusterhq.atlassian.net/browse/FLOC-3587
> [FLOC-3587] Try collecting _trial_temp/test.log

- build.yaml
Fixes https://clusterhq.atlassian.net/browse/FLOC-3580
> [FLOC-3580] Add `--debug-stacktraces` to the three trial invocations.

- build.yaml
Added a generic function that retries commands and used it with brew (which sometimes fails due to network issues)
> [FLOC 3596] Added retries to brew in Jenkins

- admin/acceptance.py
- flocker/acceptance/endtoend/test_leases.py
- flocker/common/__init__.py
- flocker/dockerplugin/_api.py
- flocker/dockerplugin/test/test_api.py
- flocker/node/agents/blockdevice.py
- flocker/node/agents/functional/test_cinder.py
- flocker/node/agents/test/blockdevicefactory.py
- flocker/node/agents/test/test_blockdevice.py
- flocker/testtools/__init__.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-3605
The lower bound used to be 100GiB but now it is 75GiB.
> [FLOC-3605] Test against smaller volumes on Rackspace

- admin/acceptance.py
- flocker/provision/_libcloud.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-3482
> [FLOC-3482] Retry node creation failure and cleanup node resources

- build.yaml
Reverts ClusterHQ/flocker#2270
> Revert "[FLOC 3596] Added retries to brew in Jenkins"

- flocker/acceptance/endtoend/test_leases.py
https://clusterhq.atlassian.net/browse/FLOC-3631
> [FLOC-3631] Fix `test_leases.LeaseAPITests.test_lease_prevents_move`.

- docs/gettinginvolved/plugins/building-driver.rst
- flocker/node/agents/blockdevice.py
1. Some hints were added to interface.
2. One was added to plugin docs.
3. Plugin docs were re-ordered slightly so instructions make more sense (docs now finish talking about necessary code before talking about how to publish the result).
> [FLOC-3614] IBlockDeviceAPI implementation tips and hints

- flocker/node/agents/blockdevice.py
- flocker/node/agents/test/test_blockdevice.py
https://clusterhq.atlassian.net/browse/FLOC-3607
> [FLOC-3607] Construct actions uniformly.

- docs/config/configuring-nodes-storage.rst
Fixes 3656
Small change to title
> [FLOC 3656] Rename the List of Backends document

- flocker/node/agents/blockdevice.py
- flocker/node/agents/test/test_blockdevice.py
https://clusterhq.atlassian.net/browse/FLOC-1772
> [FLOC-1772] Split deletes.

- setup.py
https://clusterhq.atlassian.net/browse/FLOC-3666
> [FLOC-3666] Use https for dependency link.

- admin/acceptance.py
- build.yaml
- flocker/acceptance/endtoend/test_dockerplugin.py
Run acceptance tests against loopback backend... hopefully. Theory is new Jenkins builds will appear.
> [FLOC-3669] Loopback acceptance tests in Jenkins

- build.yaml
- flocker/node/agents/test/test_blockdevice_manager.py
- jobs.groovy.j2
https://clusterhq.atlassian.net/browse/FLOC-3672
> [FLOC-3672] Run agent tests as root.

- flocker/node/agents/blockdevice.py
- flocker/node/agents/test/test_blockdevice.py
https://clusterhq.atlassian.net/browse/FLOC-3671
This merges #2320 to run the new tests.
> [FLOC-3671] ICalculater 

- flocker/node/agents/blockdevice.py
- flocker/node/agents/test/test_blockdevice.py
https://clusterhq.atlassian.net/browse/FLOC-3386
The code changes are probably easiest reviewed looking directly at the [code](https://github.com/ClusterHQ/flocker/blob/calculate-desired-datasets-FLOC-3386/flocker/node/agents/blockdevice.py#L1635-L1738) rather than the diff since github does poorly at generating a sensible diff.
> [FLOC-3386] Calculate desired datasets floc 3386

- flocker/ca/_script.py
https://clusterhq.atlassian.net/browse/FLOC-3690
> Remove a bit of dead code.

- flocker/common/__init__.py
- flocker/common/_interface.py
- flocker/common/test/test_interface.py
- flocker/node/agents/blockdevice.py
https://clusterhq.atlassian.net/browse/FLOC-3691
> [FLOC-3691] Add an invariant for `providedBy`.

- flocker/node/agents/blockdevice.py
- flocker/node/agents/test/test_blockdevice.py
https://clusterhq.atlassian.net/browse/FLOC-3693
> Simplify arguments to `CreateBlockDeviceDataset`.

- docs/labs/installer-tutorial.rst
> [FLOC 3694] add close parenthesis to Labs doc

- flocker/node/agents/test/test_blockdevice.py
Reverts ClusterHQ/flocker#2347
Failing in master: http://ci-live.clusterhq.com:8080/job/ClusterHQ-flocker/job/master/job/run_trial_on_AWS_Ubuntu_Trusty_as_root_flocker.node.agents/22/testReport/flocker.node.agents.test.test_blockdevice/BlockDeviceCalculatorTests/test_simple_transitions/
> Revert "[FLOC-3713] Enable test_simple_transitions"

- admin/acceptance.py
- admin/cluster_setup.py
- admin/setup-cluster
- admin/test/test_acceptance.py
- docs/gettinginvolved/acceptance-testing.rst
- docs/gettinginvolved/cluster-setup.rst
- docs/gettinginvolved/index.rst
- flocker/provision/_ca.py
- flocker/provision/test/test_ca.py
A tool "branched off" of `run-acceptance-tests`.
> [FLOC 3535] cluster setup tool

- requirements.txt
https://clusterhq.atlassian.net/browse/FLOC-3729
> [FLOC-3729] Update cryptography.

- flocker/node/agents/blockdevice.py
https://clusterhq.atlassian.net/browse/FLOC-3751
> [FLOC-3751] Add a type for the transition map.

- flocker/acceptance/endtoend/test_dockerplugin.py
- requirements.txt
Fixes https://clusterhq.atlassian.net/browse/FLOC-3752
> [FLOC-3752] Update version of docker-py and remove workaround

- admin/functional/test_aws.py
- admin/test/test_acceptance.py
- admin/test/test_homebrew.py
- admin/test/test_packaging.py
- admin/test/test_release.py
- admin/test/test_vagrant.py
- flocker/common/test/test_retry.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-3484
> [FLOC-3484] Change admin test suite to use Flocker-supplied base test case class

- flocker/node/agents/blockdevice.py
- flocker/node/agents/test/test_blockdevice.py
https://clusterhq.atlassian.net/browse/FLOC-3761
> [FLOC-3761] Make `MountBlockDevice` take the arguments it actually needs.

- build.yaml
Fixes https://clusterhq.atlassian.net/browse/FLOC-3780
Can't say I understand how the old version worked or why it stopped working.
> [FLOC-3780] Switch to shell syntax and rely on the shell to do this interpolation

- flocker/node/agents/functional/test_ebs.py
> [FLOC-3791] Fix skipTest

- flocker/control/test/test_clusterstate.py
- flocker/control/test/test_config.py
- flocker/control/test/test_httpapi.py
- flocker/control/test/test_model.py
- flocker/control/test/test_model_change.py
- flocker/control/test/test_persistence.py
- flocker/control/test/test_protocol.py
- flocker/control/test/test_script.py
I think this one is purely mechanical, but am not 100% sure, since I got interrupted a lot while working on it.
> Migrate flocker.control tests to new base test cases

- flocker/route/functional/networktests.py
- flocker/route/functional/test_iptables_create.py
> [FLOC-3803] Migrate route tests to new base cases

- flocker/dockerplugin/test/test_script.py
> [FLOC-3800] Move flocker.dockerplugin tests to new base case

- flocker/docs/test/test_version_extensions.py
> [FLOC-3801] Migrate docs tests to new base cases

- flocker/testtools/_base.py
- flocker/volume/functional/test_filesystems_zfs.py
- flocker/volume/functional/test_script.py
- flocker/volume/test/filesystemtests.py
- flocker/volume/test/test_filesystems_memory.py
- flocker/volume/test/test_filesystems_zfs.py
- flocker/volume/test/test_ipc.py
- flocker/volume/test/test_script.py
- flocker/volume/test/test_service.py
- flocker/volume/testtools.py
Also add successResultOf, failureResultOf, and assertNoResult to
AsyncTestCase so that the volume tests can run.
> [FLOC-3802] Move volume tests to new base cases

- flocker/node/agents/_logging.py
- flocker/node/agents/ebs.py
- flocker/node/agents/functional/test_ebs.py
> [FLOC-3686] EBS check attachment state

- build.yaml
Fixes https://clusterhq.atlassian.net/browse/FLOC-3836
Does what it says on the tin.
> [FLOC-3836] Run all of test_docker

- flocker/node/functional/test_docker.py
Fixes FLOC-3844 while main issue is under investigation.
> Mark test as flaky

- admin/cleanup-cluster
- admin/cluster_cleanup.py
- docs/gettinginvolved/cluster-setup.rst
A script to clean up all containers and datasets in a cluster.
> [FLOC-3850] cluster cleanup script

- flocker/testtools/_base.py
> [FLOC-3845] Add log entries for test entry and exit

- flocker/testtools/test/test_base.py
> [FLOC-3880] Don't expect foo as end of string

- admin/cluster_setup.py
For some platforms the address is node.private_address while
for others private_address is not set and the right address
is node.address.
> [FLOC-3888] correctly determine ip addresses to use for deployment via _compose

- jobs.groovy
Fixes https://clusterhq.atlassian.net/browse/FLOC-3894
> [FLOC-3894] Lower the clone timeout and raise the checkout retry count.

- admin/acceptance.py
- admin/test/test_acceptance.py
https://clusterhq.atlassian.net/browse/FLOC-3884
> [FLOC-3884] Tail per-file, since tailing multiple files results in extra garbage being inserted by tail

- admin/installer/setup_client.sh
fixes https://clusterhq.atlassian.net/browse/FLOC-3913
> FLOC-3913 Remove curls for missing files and postgres dir

- benchmark/submit.py
The tool expects the result document to be provided via the standard
input.
> [FLOC-3900] tool for submitting benchmark results to a server

- flocker/node/functional/test_docker.py
Justification in the comments in the code.
> [FLOC-3935] Give Docker client test an hour to run

- flocker/node/agents/functional/test_ebs.py
- flocker/node/functional/test_docker.py
All of these are now closed. Future errors are real errors.
> [FLOC-3937] Remove stale flaky decorators

- flocker/testtools/_base.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-3886
> [FLOC-3886] Remove end marker

- benchmark/_driver.py
Those are useful for reasoning about the cluster's benchmark results.
> [FLOC-3808] add node, container and dataset counts to description of flocker cluster

- build.yaml
- jobs.groovy
Jenkins is now configured to be able to notify slack. This adjusts
the job config of the daily jobs to send a notification to
> [FLOC-3876] Notify slack if a daily jenkins job fails.

- jobs.groovy
https://clusterhq.atlassian.net/browse/FLOC-4005
They shouldn't be changed.
> [FLOC-4005] Don't use parameters to pass environment variables.

- build.yaml
https://clusterhq.atlassian.net/browse/FLOC-4006
> [FLOC-4006] Make sure old files don't pollute upload documentation.

- flocker/node/agents/test/test_gce.py
Found these sitting in one of my git trees. Thought they would have more use if they were checked in.
> [FLOC-4004] Add forgotten GCE unit tests.

- admin/eliotlogging.py
- admin/filter-eliot
- flocker/testtools/__init__.py
- flocker/testtools/_base.py
- flocker/testtools/test/test_base.py
```
./admin/filter-eliot [PATH]
```
Takes test.log as input and produces valid Eliot as output.
> [FLOC-4002] Script to demangle Eliot logs

- benchmark/scenarios/write_request_load.py
I feel awfully bad for creating an issue for this.
I misunderstood what I needed to refactor. Bellow the one line of code changes.
Thank you gvernor for your time. Whoever you are :)
> using only control service in write setup

- admin/merge_pr
admin/merge_pr https://github.com/ClusterHQ/flocker/pull/<id>
will loop until all the checks are green, then trigger a merge
and delete the branch.
Rather than having to decide between merging with failing tests,
or spending time triggering retries and checking status, you can
use this script to do the work. Give it the URL of the pull request
and it will loop checking the status. When it is green it will
merge the PR, delete the source branch from github and exit.
If tests fail then it will retry the Jenkins job once, and if they
fail again it will tell you about it so that you can take a look.
If the test failures aren't your fault you can click retry and it
will merge if it is green from that run. If they are your fault
then kill the script and make the fixes.
If you just want to get a …
> [FLOC-4013] Add a script that can help with merging a pull request.

- flocker/node/script.py
- flocker/node/test/dummybackend.py
- flocker/node/test/test_script.py
Reverts ClusterHQ/flocker#2542
> Revert "[FLOC-3998] Flocker dataset config"

- build.yaml
https://clusterhq.atlassian.net/browse/FLOC-4071
> [FLOC-4071] Link to the website endpoint in doc build.

- admin/aws.py
- admin/release.py
- admin/test/test_release.py
- docs/redirects.yaml
https://clusterhq.atlassian.net/browse/FLOC-3999
> [FLOC-3999] Documentation redirects.

- build.yaml
Help us to figure out the intermittent Vagrant problems on Jenkins.
> [FLOC-4083] Enable verbose vagrant logging for most commands.

- flocker/control/test/test_protocol.py
- flocker/control/testtools.py
- flocker/testtools/amp.py
- flocker/testtools/test/test_amp.py
https://clusterhq.atlassian.net/browse/FLOC-4088
This is just moving some code around.
> [FLOC-4088] Factor out loopback AMP client.

- build.yaml
- jobs.groovy
https://clusterhq.atlassian.net/browse/FLOC-4101
> [FLOC-4101] Add build number to github -> jenkins links.

- build.yaml
https://clusterhq.atlassian.net/browse/FLOC-4106
> [FLOC-4106] Make linkcheck and spelling output more visible.

- flocker/node/agents/test/test_ebs.py
Is actually a fix for https://clusterhq.atlassian.net/browse/FLOC-3524?focusedCommentId=22263&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-22263
not necessarily for the issue itself.
> [FLOC-3524] Fix pylint error

- admin/merge-pr
- admin/merge_pr
- admin/merge_pr.py
> [FLOC-4120][merge_pr] Don't crash if inQueue missing.

- build.yaml
Fixes: https://clusterhq.atlassian.net/browse/FLOC-4119
I'm not sure whether Jenkins will add my new build step automatically.
If it appears to work, I'll remove the ``--dry-run`` option and rebuild.
> [FLOC-4119] Configure Jenkins to run ``cleanup_cloud_resources`` daily

- docs/releasenotes/index.rst
https://clusterhq.atlassian.net/browse/FLOC-4170
> [FLOC-4170] Release 1.10.2

- admin/merge_pr.py
- admin/test/test_merge_pr.py
Also add some tests for the merge_pr module. They are far from
complete.
> [FLOC-4140] Handle Jenkins skipping 'builds' in the job dict.

- admin/functional/test_release.py
- admin/release.py
Fixes: https://clusterhq.atlassian.net/browse/FLOC-4190
> [FLOC-4190] Fix a bug in the initialize-release tool

- admin/cluster_add_nodes.py
save_evironment function now receives one extra parameter
> Adding missing parameter to function call

- docs/gettinginvolved/plugins/building-driver.rst
https://clusterhq.atlassian.net/browse/FLOC-4249
> [FLOC-4249] Release Flocker 1.10.2.post1

- docs/gettinginvolved/plugins/building-driver.rst
https://clusterhq.atlassian.net/browse/FLOC-4238
This is in preperation for #2659.
> [FLOC-4328] Update plugin documentation to require unicode for `required_config`.

- docs/gettinginvolved/functional-testing.rst
Fixes: https://clusterhq.atlassian.net/browse/FLOC-4246
> [FLOC-4246] Add documentation for GCE functional tests

- flocker/node/agents/functional/test_gce.py
- flocker/node/agents/gce.py
Not much to say about this one.  GCE only has 2 types of disks we can use: magnetic PD and SSD PD so bronze will be magnetic, gold and silver will be SSD.  The hoops to use Values and ValueConstants make me a bit sad but work...  Feel free to suggest alternatives.
> GCE storage profiles: FLOC-3828

- admin/acceptance.py
- admin/cluster_setup.py
- admin/test/test_acceptance.py
- flocker/acceptance/endtoend/test_dataset.py
- flocker/acceptance/endtoend/test_dockerplugin.py
- flocker/acceptance/testtools.py
- flocker/common/plugin.py
- flocker/common/test/test_plugin.py
- flocker/node/backends.py
- flocker/provision/_common.py
- flocker/provision/_install.py
- flocker/provision/test/test_install.py
https://clusterhq.atlassian.net/browse/FLOC-4272
> [FLOC-4272] Use `BackendDescription`s instead of `DatasetBackend` constants.

- docs/installation/setup-aws.rst
- flocker/provision/_aws.py
https://clusterhq.atlassian.net/browse/FLOC-4277
> [FLOC-4277] Update CentOS base image.

- AUTHORS.rst
> [FLOC-4201] update wording in documentation

- docs/docker-integration/cloudformation.rst
Fixes 4269
Addresses a suggestion raised by @moshez 
Note - Point 2 raised in 4269 "Move the Volume Hub part of step 2 to Step 1.5. Looks too mushed up with Step 2." has not been corrected in this PR - this will be done as part of the review comments submitted by FFFunction, that are currently being transcribed into JIRA tickets. (will update here when references are available)
> [FLOC 4269] Rename keypair suggestion

- flocker/node/__init__.py
- flocker/node/_container.py
- flocker/node/test/test_container.py
Fixes: https://clusterhq.atlassian.net/browse/FLOC-4325
Copied from #2720 with some additional test fixes.
> [FLOC-4325] Increase container agent sleep time to 5 seconds

- flocker/restapi/_infrastructure.py
- flocker/restapi/_logging.py
- flocker/restapi/test/test_infrastructure.py
Fixes: https://clusterhq.atlassian.net/browse/FLOC-4327
Copied from #2720 with some test alterations.
> [FLOC-4327] Stop logging the response body of REST API requests

- flocker/control/_model.py
- flocker/control/_persistence.py
- flocker/node/_container.py
- flocker/node/agents/blockdevice.py
Fixes: https://clusterhq.atlassian.net/browse/FLOC-4332
Copied from #2720
> [FLOC-4332] Avoid expensive pyrsistent operations

- CONTRIBUTING.rst
Update documentation for gettinginvolved/contribute.html to add setup instructions Centos7 & Ubuntu environment
> [FLOC-1845] Update gettinginvolved/contribute.html to add setup instructions.

- requirements.txt
I just added an optimization to pyrsistent that increases the chance of getting the exact same object for equivalent PClasses.  Preliminary tests in flocker indicate that this greatly helps our comparisons when we are looking up PClasses in our lru caches.
> [FLOC-4395] Update Flocker to use pyrsistent with PClass.set optimizations.

- flocker/control/_protocol.py
- flocker/control/test/test_protocol.py
First pass implementation of batched updates.
I'll probably revisit this to reduce calls further. This greatly reduces the number of broadcasts, but a decent number of requests, especially when we are busy, are done via the non-broadcast "send update once last update is acknowledged" codepath. It would be much faster (just for amortized logging reasons) to figure out how to collapse all of those into a single call as well. I'll be looking to amortize all of those as well.
> [FLOC-4396] Only send updates on the second to nodes (for broadcast)

- docs/releasenotes/index.rst
Fixes: https://clusterhq.atlassian.net/browse/FLOC-4393
> [FLOC-4393] Release Flocker 1.12.0

- benchmark/benchmark.yml
Missing stanzas from benchmark.yml that are needed to run the 10 QPS benchmark scenarios.
> [FLOC-4402] Update the benchmark.yml

- admin/test/test_merge_pr.py
- flocker/common/algebraic.py
- flocker/control/test/test_persistence.py
- flocker/node/agents/blockdevice.py
- flocker/node/agents/test/test_blockdevice.py
- requirements.txt
Fixes: https://clusterhq.atlassian.net/browse/FLOC-4412
Broken out from https://github.com/ClusterHQ/flocker/pull/2792
> [FLOC-4412] Upgrade to Hypothesis 3 

- requirements.txt
Grab the latest optimizations from:
https://github.com/ClusterHQ/pyrsistent/commit/28853bd4d0235fab5cbfcdc8ab01a61902111f72
> [FLOC-4414] Update pyrsistent version

- admin/build_targets/centos-7/Dockerfile
- admin/build_targets/ubuntu-14.04/Dockerfile
- admin/build_targets/ubuntu-15.10/Dockerfile
- build.yaml
- requirements/admin.txt
- requirements/admin.txt.in
- requirements/constraints.txt
- requirements/flocker-dev.txt
- requirements/flocker.txt
- requirements/flocker.txt.in
Fixes: https://clusterhq.atlassian.net/browse/FLOC-4430
Add the latest Pyrsistent performance improvements to Flocker:
* ClusterHQ/pyrsistent#12
In running the `./admin/update-requirements` tool I also picked up a bunch of other library updates which I decided to include in this branch.
I already ran the tests in #2817
> [FLOC-4430] Pyrsistent chq5 with pset batch operations

- docs/releasenotes/index.rst
Fixes https://clusterhq.atlassian.net/browse/FLOC-4433
> [FLOC-4433] Release Flocker 1.13.0

- docs/spelling_wordlist.txt
Fixes: https://clusterhq.atlassian.net/browse/FLOC-4444
Merging https://github.com/ClusterHQ/flocker/pull/2828 into master.
> [FLOC-4444] Add diff to the spelling list

- docs/releasenotes/index.rst
Fixes: https://clusterhq.atlassian.net/browse/FLOC-4446
> [FLOC-4446] Release Flocker 1.13.0.post1

- docs/releasenotes/index.rst
Fixes: https://clusterhq.atlassian.net/browse/FLOC-4462
> [FLOC-4462] Release Flocker 1.14.0

- docs/releasenotes/index.rst
Fixes: https://clusterhq.atlassian.net/browse/FLOC-4496
> [FLOC-4496] Release Flocker 1.15.0

- flocker/node/agents/blockdevice_manager.py
Fixes: https://clusterhq.atlassian.net/browse/FLOC-4499
Not strictly related to the configdrive parent issue, but this makes the blockdevice_manager log the commands that that it launches.
> [FLOC-4499] Log block manager commands

- .pylintrc
- admin/cluster_add_nodes.py
- admin/cluster_setup.py
- admin/merge_pr.py
- admin/test/test_images.py
- admin/update-requirements-entrypoint
- benchmark/cluster_containers_setup.py
- benchmark/scenarios/_request_load.py
- benchmark/scenarios/test/test_rate_measurer.py
- benchmark/test/test_driver.py
- flocker/control/_diffing.py
- flocker/control/test/test_protocol.py
- flocker/control/testtools.py
- flocker/node/agents/blockdevice_manager.py
- flocker/node/agents/testtools/_loopback.py
- flocker/restapi/docs/test/test_publicapi.py
- flocker/volume/functional/test_service.py
- flocker/volume/test/test_ipc.py
- flocker/volume/testtools.py
Fixes: https://clusterhq.atlassian.net/browse/FLOC-4469
> [FLOC-4469] remove unused variables (pylint)

- docs/_themes/clusterhq/layout_docs.html
- docs/_themes/clusterhq/static/js/segment.js
Fixes: https://clusterhq.atlassian.net/browse/FLOC-4519
Based on #2667 and additionally remove the Google Analytics JavaScript code 
(as discussed with @ferrantim)
> [FLOC-4519] Use segment.com for analytics

- docs/_themes/clusterhq/layout_docs.html
- docs/_themes/clusterhq/static/js/segment.js
Fixes: https://clusterhq.atlassian.net/browse/FLOC-4520
Merging #2933 to master.
> [FLOC-4520] Use segment.com for analytics

- docs/_themes/clusterhq/layout_docs.html
Fixes: https://clusterhq.atlassian.net/browse/FLOC-4532
Merging #2945 into master.
> [FLOC-4532] Remove zendesk from flocker-docs

- .pylintrc
- .travis.yml
- build.yaml
Fixes: https://clusterhq.atlassian.net/browse/FLOC-4535
Example results:
* Failure: https://travis-ci.org/ClusterHQ/flocker/builds/177635062
* Success: https://travis-ci.org/ClusterHQ/flocker/builds/177638042
> [FLOC-4535] Run lint checks on travis-ci

- build.yaml
- dockerfiles/control/Dockerfile
- dockerfiles/dataset/Dockerfile
- docs/gettinginvolved/infrastructure/packaging.rst
Fixes: https://clusterhq.atlassian.net/browse/FLOC-4537
> [FLOC-4537] build docker image for flocker control

- build.yaml
- dockerfiles/dataset/Dockerfile
- dockerfiles/docker-plugin/Dockerfile
- docs/gettinginvolved/infrastructure/packaging.rst
Fixes: [FLOC-4540](https://clusterhq.atlassian.net/browse/FLOC-4540)
> [FLOC-4540] Build Docker image for flocker-docker-plugin

- admin/packaging.py
- flocker/control/test/test_schemas.py
- requirements/admin.txt
- requirements/flocker-dev.txt
- requirements/flocker.txt
- requirements/lint.txt
- setup.cfg
Fixes: https://clusterhq.atlassian.net/browse/FLOC-4549
> [FLOC-4549] Update Python requirements

- flocker/acceptance/endtoend/test_dockerplugin.py
Fixes: 
* https://clusterhq.atlassian.net/browse/FLOC-4557
* https://github.com/ClusterHQ/flocker/issues/2970
Bind mount /dev into the lsblk test container so that multi-path devices can be examined.
@shay-berman please test this modified version of the acceptance test with your IBM driver.
I dug into the Docker and runc code to understand how `/dev` gets populated inside the container.
See the comments and links in the patch.
> [FLOC-4557] Bind mount /dev into the lsblk test container

- admin/acceptance.py
- admin/release-packaging/rhel/clusterhq-release.spec
- admin/release-packaging/rhel/clusterhq.repo
- build.yaml
- docs/gettinginvolved/infrastructure/packaging.rst
- flocker/provision/_aws.py
- flocker/provision/_gce.py
- flocker/provision/_install.py
- flocker/provision/_libcloud.py
Fixes: https://clusterhq.atlassian.net/browse/FLOC-4558
Stacked on: #2789
* Rackspace doesn't seem to have a RHEL7 image so that's not supported.
* I had to add a RHEL meta package which installed a `/etc/yum.repos.d/clusterhq.repo` pointing at the Centos-7 packages.
* Also had to add a hack to permit root logins on RHEL7 in lieu of #2726
> [FLOC-4558] RHEL7 acceptance tests

- build.yaml
Fixes: https://clusterhq.atlassian.net/browse/FLOC-4560
> [FLOC-4560] Don't overwrite the SSH key everytime

- flocker/provision/_libcloud.py
Fixes: https://clusterhq.atlassian.net/browse/FLOC-4559
I broke this in https://github.com/ClusterHQ/flocker/pull/2978
> [FLOC-4559] Fix rackspace node provisioning

- README.rst
> [2987] Link to readthedocs
