ClusterHQ/flocker

docs/advanced/cleanup.rst
Fixes https://clusterhq.atlassian.net/browse/FLOC-909
It might also be worth making it clear that the cleanup steps need to be performed in sequence ie all the containers must  be stopped before removing their zfs volumes. Otherwise you get this:
```
(flocker-tutorial)[~/flocker-tutorial]$ ssh root@172.16.255.250 'zfs destroy -r flocker'
cannot destroy 'flocker/7b766437-2c5a-46aa-afb1-abedf99a04d0.default.mongodb-volume-example': dataset is busy
```
The steps could be converted from headings to a numbered list.
=> [FLOC-909] Clarify that `zfs destroy` should be run on the remote node

flocker/restapi/__init__.py, flocker/restapi/_infrastructure.py, flocker/restapi/docs/__init__.py, flocker/restapi/docs/hidden_code_block.py, flocker/restapi/docs/publicapi.py, flocker/restapi/docs/test/__init__.py, flocker/restapi/docs/test/test_publicapi.py, flocker/restapi/test/test_infrastructure.py, setup.py, tox.ini
https://clusterhq.atlassian.net/browse/FLOC-921
1. I'm not sure this is the best way to change the directive to support non-hardcoded schema store and examples, but lacking an actual usage of the code it's not clear what a better way is.
2. Directive is untested, as it was in original code this is copied from...
I suggest limiting this branch to what it is (minimal port of existing code) and when we have issues actually using it (as is likely), fix those in a follow-up issue.
=> [FLOC-921] Sphinx apidocs generation

flocker/common/_ipc.py
=> Use options supported by OS X.

flocker/volume/script.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-1246
=> [FLOC-1246] Make help text parameter names consistent.

docs/_themes/clusterhq/layout.html, docs/conf.py, docs/gettinginvolved/infrastructure/release-process.rst, docs/gettinginvolved/infrastructure/release-schedule-versioning.rst, flocker/docs/__init__.py, flocker/docs/_version.py, flocker/docs/test/__init__.py, flocker/docs/test/test_version.py
https://clusterhq.atlassian.net/browse/FLOC-1252
I decided that we should tag documentation releases (with `+doc.X`). This is stripped in the documentation.
=> [FLOC-1252] Display marketing release version in documentation releases.

vagrant/tutorial/cache.sh
Fixes FLOC-1295
After this is merged it will probably be necessary to re-build the tutorial box for 0.3.2 and upload it to the appropriate place (manually).
The command to re-build the tutorial box is:
```
./build-vagrant-box --box tutorial --flocker-version 0.3.2
```
This needs to be run from a release/flocker-0.3.2 checkout to pick up the changes made here.
This also needs to happen **after** the Docker 1.4.1/Fedora regression is fixed somehow.
=> Pull a couple more images.

tox.ini
https://clusterhq.atlassian.net/browse/FLOC-1372
Otherwise, we automatically get newer versions, which cause spurious failures.
=> Use extra to install flake8 in tox.

admin/packaging.py, admin/test/test_packaging.py, admin/vagrant.py
https://clusterhq.atlassian.net/browse/FLOC-1366
https://clusterhq.atlassian.net/browse/FLOC-1363
Pip (via setuptools) normalizes the version of the package according
to PEP440, if the version is a valid PEP440 version.
The version versioneer generates isn't a valid PEP440 version, except
- if we are building a tag, in which case a ``.`` is inserted before
``dev`` and ``pre`` is turned into ``.rc``
or
- if the latest tag is has a local part (e.g. ``+docX``), in which case,
``-`` after ``+`` are turned into ``.``.
=> [FLOC-1366] [FLOC-1363] packaging: Get version from package.__version__ instead of pip.

docs/introduction.rst
Sphinx currently interprets it as continuing from the previous line ("Data Model") without the line break, and hence looks a tad ugly.
Link to current published docs for reference: https://docs.clusterhq.com/en/0.3.2/introduction.html#managing-volumes
=> Add whitespace into "Managing Volumes" section of docs/introduction.rst

docs/index.rst
Fixes https://clusterhq.atlassian.net/browse/FLOC-1220
It took me ages to figure out the correct rebase command for this. I didn't really need to rebase, but I wanted to finally understand how rebase should be used in this situation Here's what I cam up with.
```
git clone git@github.com:ClusterHQ/flocker.git "flocker-0.3.2"
cd flocker-0.3.2/
git checkout remove-zfs-reference-FLOC-1220
git merge origin/master
git checkout -b release-maintenance/flocker-0.3.2/remove-zfs-reference-FLOC-1220
git rebase --onto release/flocker-0.3.2 origin
git push --set-upstream origin release-maintenance/flocker-0.3.2/remove-zfs-reference-FLOC-1220
```
=> [FLOC-1220] Removed references to ZFS

admin/homebrew.py
Modify the existing script to accept a command line argument specifying the URL from which to download the sdist code.  Using the explicit argument enables CI by giving more flexibility to where the sdist file is located.  For backwards compatibility, providing no argument continues to use the release location on Google Storage.
Note, this change is equivalent to the change proposed in PR #1192, but separated from the additional design work to actually enable CI.
=> [FLOC-1533] Modify Homebrew recipe creation to accept explicit path to distribution.

admin/homebrew.py
BuildBot prefers command arguments to environment variables and file re-direction. Add some flags to the Homebrew creation script to rely on command options, while keeping backwards compatibility to currently documented release process.
Also, add some logging for progress.
=> [FLOC-1534] Flags to set version and output file for Homebrew recipe creation

flocker/control/schema/endpoints.yml, flocker/restapi/docs/publicapi.py, flocker/restapi/docs/test/test_publicapi.py
https://clusterhq.atlassian.net/browse/FLOC-1392
To review visually, compare documentation for `GET /v1/configuration/datasets` and `GET /v1/state/datasets` in build results and in http://doc-dev.clusterhq.com/advanced/api.html
=> [FLOC-1392] Array APIs now get documented

flocker/cli/functional/test_deploy_script.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-1547
I couldn't reproduce the thread ordering problem locally, so introduced some time delays to force the issue.
I should probably remove those delays before merging.
Or alternatively, I could somehow chain the firing of failures so that the errors are logged in predictable order.
But probably not worth spending time on.
=> [FLOC-1547] Sort the expected logged errors before comparing

flocker/node/__init__.py, flocker/node/_deploy.py, flocker/node/_loop.py, flocker/node/test/test_deploy.py, flocker/node/test/test_loop.py, flocker/node/testtools.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-1535
We'd also planned to remove the `local_state` argument of `calculate_necessary_state_changes`, thinking that the `cluster_state` would have all the required information. But actually, the `NodeState` attributes `running` and `not_running` and `used_ports` are not available from `cluster_state`. It is a `Deployment` and  only has `Node` records. 
There should probably be a followup issue to create a `DeploymentState` record which has `NodeStates` rather than `Nodes` and a corresponding update to the control service and AMP protocol to broadcast `DeploymentState` records.
=> [FLOC-1535] Update cluster local state before supplying it to calculate_necessary_state_changes

flocker/node/agents/__init__.py, flocker/node/agents/blockdevice.py, flocker/node/agents/test/__init__.py, flocker/node/agents/test/test_blockdevice.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-1490
Fixes https://clusterhq.atlassian.net/browse/FLOC-1494
This introduces an (incomplete) interface for block-device backends.  It also implements that interface using a local-only loopback block device provider.  This was split out of a larger branch which also includes new `IDeployer` implementation that knows how to use this new interface to provide block-device-based storage for a datasets convergence agent (that code to be up for review shortly, you can see it in https://github.com/ClusterHQ/flocker/tree/iblockdevice-deployer-FLOC-1502 (currently contains all of this code and some more code besides)).
The new interface and implementation also covers the "list existing block devices" functionality that's required but there's no …
=> [FLOC-1490, FLOC-1494] Initial IBlockDeviceAPI and an initial Loopback implementation for creating, attaching and listing block devices

CONTRIBUTING.rst, tox.ini
https://clusterhq.atlassian.net/browse/FLOC-1229
Now you can do `tox -e py27 flocker.control.test.test_httpapi` or whatever. Lack of this was constant annoyance for me.
=> [FLOC-1229] Allow passing arguments to trial run by tox

admin/build_targets/centos-7/Dockerfile, admin/build_targets/fedora-20/Dockerfile, admin/build_targets/ubuntu-14.04/Dockerfile, admin/packaging.py
Fixes: https://clusterhq.atlassian.net/browse/FLOC-1571
Adds eliot logging to admin/build-package.  Logs the steps run by `BuildSequence` so some kind of package build progress is apparent.
Excludes actual eliot action or message type definitions and excludes unit tests for the logging behavior because:
* this isn't production code
* the exact information being logged here is pretty haphazard (repr of an object).  maybe we'll think of something more useful to log later.
* the code being modified to do logging does have unit tests
* this is as much as I could implement while waiting for vagrant to download a flocker-tutorial box that I needed for other more important work
=> [FLOC-1571] Build package logging

admin/acceptance.py
Fixes FLOC-1584
Jean-Paul pointed out that this is related to https://clusterhq.atlassian.net/browse/FLOC-1385, and it seems that this has been fixed too. This branch modifies what I think is the fix for that, so I think that should be closed with FLOC-1584.
=> Remove known hosts when running vagrant tests

flocker/node/functional/test_deploy.py, flocker/testtools/__init__.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-167
Still a little bit of junk output but this gets rid of a about 99% of it.
=> Use a helper that captures all output instead of only some.

flocker/acceptance/test_api.py
Fixes FLOC-1590
Creates a MongoDB container on node 1 and writes some data. Moves the container with its associated dataset via the API move container endpoint to node 2. Then after moving, shuts down the container on node 2 and launches a new container on node 2 with a different exposed external port, then connects to that container and ensures the data written by the first container is mounted and can be re-read. This approach ensures the container has actually moved; we don't want the acceptance test to pass by accident, which could happen if the first container on node 1 hasn't moved, but we can still read the data because of the proxy layer when connecting to the originally open port on node 2's IP.
=> [FLOC-1590] Acceptance move container

flocker/route/_iptables.py, flocker/route/functional/test_iptables_create.py
Fixes: https://clusterhq.atlassian.net/browse/FLOC-1677
I think the exception I saw in that issue was due to passing `OpenPort` rather than `int` as the `target_port` argument of the `DELETE_OPEN_PORT` Eliot action.
Hopefully, when that's fixed, we'll be able to see what the actual error is.
If this parent action can be serialised by Eliot, I think we'll see a child IPTABLES action fail with a more meaningful error message.
=> [FLOC-1677] Log the port number rather than OpenPort in delete_open_port

flocker/ca/test/test_ca.py
Currently breaking one of the vagrant builds on master because the tests are not skipped on broken permissions.
=> [FLOC-1715] Hotfix for CA initialization tests

flocker/node/_change.py, flocker/node/test/test_change.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-1667
Depends on FLOC-1666 / #1285, review that first.
This is the second step towards FLOC-1591.  It centralizes `IStateChange.run` calls in one place so it is easy to manipulate them (eg by logging them all).
=> Move run logic floc 1667

flocker/node/_change.py, flocker/node/_deploy.py, flocker/node/agents/blockdevice.py, flocker/node/agents/test/test_blockdevice.py, flocker/node/test/test_change.py, flocker/node/test/test_deploy.py, flocker/node/testtools.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-1591
This is the last step.  Logging is added to the new `run_state_change` API and existing `IStateChange` implementations are augmented with the necessary Eliot logging information.
=> Automatically log IStateChanges

flocker/node/_change.py, flocker/node/test/istatechange.py, flocker/node/test/test_change.py, flocker/node/test/test_testtools.py, flocker/node/testtools.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-1714
I almost made `changes` a `PSet` but I concluded that being able to run the same change twice is probably a legitimate use-case (and at the very least less surprising than having two changes collapsed into one).
=> make the order of `changes` passed to `in_parallel` irrelevant

flocker/testtools/__init__.py
flocker-ubuntu-14.04 builder has test failures due to Docker client/server version mismatch:
docker.errors.APIError: 404 Client Error: Not Found ("client and server don't have same version (client : 1.16, server: 1.15)")
This is caused because of missing client version (1.15) in the following test code:
__________
From flocker/testtools/__init__.py:
from docker import Client as DockerClient
...
def build(self, dockerfile_variables=None):
...
def remove_image():
client = DockerClient() 
__________
Since default docker version is 1.16 (from py27/lib/python2.7/site-packages/docker/client.py:
DEFAULT_DOCKER_API_VERSION = '1.16'), and our Docker server version is 1.15, we run into version mismatch.
We need to create DockerClient(version="1.15") to fix the test issues on Ubuntu.
=> Fix default Docker client version used by Flocker testtools.

flocker/control/schema/types.yml, flocker/control/test/test_httpapi.py, flocker/control/test/test_schemas.py, flocker/node/agents/blockdevice.py, flocker/node/agents/test/test_blockdevice.py, flocker/testtools/__init__.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-1503
Initially I thought this would involve improving state discovery to include the size of non-manifest datasets.  I changed my mind, though.  Resizes are only attempted for datasets that have a manifestation and those datasets already have their size discovered.  I left the design notes for non-manifest dataset size discovered in, though, marked `FLOC-1503-x`.  I may go ahead and implement that stuff here anyway, it's barely an extra code and improves the system.  If the reviewer would prefer me not to, though, I'll split those things off into a separate issue.
=> Shrink block device volumes

admin/package-files/systemd/flocker-agent.service, admin/package-files/systemd/flocker-container-agent.service, admin/package-files/upstart/flocker-agent.conf, admin/package-files/upstart/flocker-container-agent.conf, docs/advanced/api.rst, flocker/node/script.py, flocker/node/test/test_script.py, flocker/provision/_install.py
Where we stray from [the design](https://github.com/ClusterHQ/flocker/pull/1338/files):
* For now the config option is called "control-service-config" instead of "config-options". This is because the "flocker-zfs-agent" script already has a "--config" option. The option name and description matches what this is now but a follow-up branch can change that when what it does changes.
* @exarkun asked for quotes around yml strings. We have done this in the documentation example but in the task we found one way to do this with `yaml.safe_dump` and that was to use `default_style='"'` param. However this looked bad with different types.
* The example yml used to be wrapped by braces but that changed because it looked odd to us.
* We agree that this documentation should be moved but have not done …
=> Yml startup floc 1790

docs/gettinginvolved/infrastructure/release-process.rst, setup.py
This can be reviewed but should not be merged yet because there is one outstanding use of `gsutil` in the release process. The issue (currently awaiting review) to remove this is https://clusterhq.atlassian.net/browse/FLOC-1718.
There are other uses of gsutil in the docs but some are going away, none already told you to use Flocker's setup.py, and most are very rarely run.
=> Replace gsutil with awsutil

docs/advanced/api.rst, flocker/node/script.py, flocker/node/test/test_script.py, flocker/provision/_install.py
Unlike the design at https://github.com/ClusterHQ/flocker/pull/1338 this does not specify TCP. It is possible to have a "protocol" key and just make sure that it is TCP but I think that it is better to just leave it and add an option later if necessary.
As per the previous PR, there is some documentation duplication and the documentation is not in the best place. However David Oliver is looking into restructuring the documentation and will look at this story in particular before submission so I don't think that should be solved here.
=> Control service yml floc 1801

Vagrantfile
As mentioned on the issue, I have done this issue because the slow network speed is annoying when testing packaging changes.
=> Change virtualbox settings

Vagrantfile
Reverts ClusterHQ/flocker#1378
This is because of some locking issue.
=> Revert "Change virtualbox settings"

flocker/node/_deploy.py, flocker/node/functional/test_deploy.py, flocker/node/test/test_deploy.py
Question for reviewer: perhaps our default policy should be restart always, instead of restart never?
*Update:* Rob has stated this is the desired default.
=> [FLOC-1803] Rely on Docker restart policies; no longer restart stopped containers ourselves.

admin/runner.py, admin/test/test_runner.py
https://clusterhq.atlassian.net/browse/FLOC-1849
This doesn't address the underlying issue (which is we don't interact with vagrant and virtualbox in a way that cleans up old images properly). But it does address the regression in #1294, where we stopped showing stderr from vagrant.
(See 
http://build.clusterhq.com/builders/flocker%2Facceptance%2Fvagrant%2Ffedora-20/builds/2059
where it demonstrates the output).
=> [FLOC-1849] Show stderr from admin.runner too.

docs/gettinginvolved/acceptance-testing.rst, docs/spelling_wordlist.txt, flocker/node/agents/functional/test_cinder.py, flocker/node/agents/functional/test_cinder_behaviour.py, flocker/node/agents/functional/test_ebs.py, flocker/node/agents/test/blockdevicefactory.py
https://clusterhq.atlassian.net/browse/FLOC-1787
This is based on #1347 since the code this is touching is refactored there. ([relative diff](https://github.com/ClusterHQ/flocker/compare/openstack-attach-FLOC-1485...explict-cloud-testing-variables-FLOC-1787))
=> [FLOC-1787] Make functional cloud testing variables explict.

docs/advanced/api_examples.yml, flocker/acceptance/test_api.py, flocker/control/httpapi.py, flocker/control/schema/endpoints.yml, flocker/control/schema/types.yml, flocker/control/test/test_httpapi.py, flocker/control/test/test_schemas.py
Fixes:
* https://clusterhq.atlassian.net/browse/FLOC-1848
Removes the maximum_size change capabilities from the update dataset API endpoint.
=> [FLOC-1848] Remove resize dataset from API

flocker/ca/_ca.py, flocker/ca/functional/test_ca.py
Fixes FLOC-1870
Prevents differing order of distinguished name components in generated certificates due to inconsistent dict iteration order.
Note: There are a couple of unrelated test failures
```
flocker.provision.test.test_ssh_conch.Tests.test_run_logs_stderr
flocker.provision.test.test_ssh_conch.Tests.test_run_logs_stdout
```
=> [FLOC-1870] Flocker CA tests

flocker/restapi/_infrastructure.py, flocker/restapi/docs/publicapi.py, flocker/restapi/docs/test/test_publicapi.py
This undoes the constraint introduced in PR #1412 that `header` is a required field in `user_documentation` decorator. Several tests do not include the `user_documentation` decorator at all, and it is possibly reasonable for this to happen for real operations ("private" operations, for example).
=> Fix doc tests floc 1913

flocker/node/agents/test/blockdevicefactory.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-1890
Goes along with https://github.com/ClusterHQ/build.clusterhq.com/pull/81 which sets the environment variable this depends on.
This is currently staged on http://23.253.99.92/boxes-flocker
=> Get the region from the environment.

admin/package-files/systemd/flocker-agent.service, admin/package-files/systemd/flocker-container-agent.service
Unfortunately `ConditionFileNotEmpty=` shows the same error. It doesn't seem worth investigating right now, and we can look into it if it ever causes hassle.
For now `journalctl -r -u flocker-agent` shows a traceback:
```
May 18 11:36:43 node1 systemd[1]: Unit flocker-agent.service entered failed state.
May 18 11:36:43 node1 systemd[1]: flocker-agent.service: main process exited, code=exited, status=1/FAILURE
May 18 11:36:43 node1 flocker-dataset-agent[2012]: {"task_uuid": "0e08892a-7221-4396-b6e0-5505061814d4", "error": false, "timestamp": 1431974203.083844, "message": "Main loop terminated.", "message_type": "twisted:log", "task_level": [4]}
May 18 11:36:43 node1 flocker-dataset-agent[2012]: {"task_uuid": "0e08892a-7221-4396-b6e0-5505061814d4", "error": true, "timestamp": …
```
=> File exists floc 1873

flocker/node/agents/cinder.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-1914
Adjust to the reality that OpenStack Cinder APIs operate in terms of GiB, not GB (as documentation suggests).
Here's a completely green run of the OpenStack functional tests on Rackspace (from this branch): http://build.clusterhq.com/builders/flocker%2Ffunctional%2Frackspace%2Fcentos-7%2Fstorage-driver/builds/54
=> [FLOC-1914] Switch from GB to GiB.

flocker/ca/_ca.py, flocker/ca/test/test_ca.py, setup.py
And add dependency on `service_identity`.
=> [FLOC-1607] Encode subjectAltName correctly when given hostname is actually an IP

docs/indepth/installation.rst, flocker/node/script.py, flocker/node/test/test_script.py
Design for: https://clusterhq.atlassian.net/browse/FLOC-1943
We plan to support a third dataset backend option, 'openstack' (after 'zfs' and 'loopback').
This requires:
* Documentation about what is supported,
* Documentation about how to create a valid agent.yml,
* Validation of the currently supported options.
Openstack backends require an auth plugin. For each auth plugin, there are various plugin-specific options.
We currently support two plugins: "rackspace" and "password".
The "password" plugin is used (at least) for PistonCloud.
Supported configs would be something like the following (but `yaml`):
```python
config_rackspace = {
'control-service': {
'hostname': '172.16.255.240',
'port': 4524,
},
'dataset': {
'backend': 'openstack',
'tenant_id': 'my_id', # required if openstack …
```
=> [FLOC-1943] Validate openstack credentials

admin/build_targets/centos-7/Dockerfile, admin/build_targets/fedora-20/Dockerfile, admin/build_targets/ubuntu-14.04/Dockerfile, setup.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-1959
The newer version of pyrsistent has better exceptions.
0.9.1 has exceptions like:
```
File "/home/exarkun/Environments/flocker/local/lib/python2.7/site-packages/pyrsistent.py", line 2721, in _check_types
raise TypeError
exceptions.TypeError: 
```
0.9.2 has exceptions like:
```
File \"/home/exarkun/Environments/flocker/local/lib/python2.7/site-packages/pyrsistent.py\", line 2761, in _check_types
raise exception_type(expected_types, actual_type, e, source_class, msg)
pyrsistent.CheckedValueTypeError: Type UuidFilepathPMap can only be used with ('FilePath',), not NoneType
```
=> [FLOC-1959] Have more informative pyrsistence type errors

admin/acceptance.py, docs/gettinginvolved/acceptance-testing.rst, flocker/acceptance/testtools.py, flocker/provision/_install.py
https://clusterhq.atlassian.net/browse/FLOC-1949
This will need to be refined to support cloud backends (passing credentials).
I also wonder if having `DatasetBackend` is worthwhile, if we expect people writing out-of-tree backends to use our acceptance tests.
There are some failures in the postgres tests that I haven't investigated yet.
This (temporarily) removes the ZFS acceptance tests, until after https://github.com/ClusterHQ/build.clusterhq.com/pull/91 lands
=> [FLOC-1949] Choose dataset backend in acceptance test runner.

flocker/node/_docker.py, flocker/node/functional/test_docker.py
This will also be covered by end-to-end acceptance test (the reason I discovered it) in FLOC-1976. In master there are no acceptance tests using `command_line` which is why this wasn't caught.
=> [FLOC-1984] Fix bug where pvector blew up docker-py

docs/gettinginvolved/infrastructure/release-process.rst, docs/gettingstarted/index.rst
Fixes https://clusterhq.atlassian.net/browse/FLOC-2004
Also happens to fix https://clusterhq.atlassian.net/browse/FLOC-1551.
This removes the &&s, but part of the advantage of that is that you can copy in one go - the prompt directive allows this to be done too by not copying the prompt.
=> Tested osx floc 2004

flocker/provision/_install.py, flocker/provision/test/test_install.py
This has been tested with an Ubuntu 14.04 container, as the output of ``lsb_release --release --short`` is ``14.04``. When the repository doesn't exist (if we change ``$(lsb_release --release --short)`` to ``foo``) then the error is much clearer than the datetime issue shown on the parent:
``sudo apt-get update`` gives:
```
W: Failed to fetch https://clusterhq-archive.s3.amazonaws.com/ubuntu-testing/foo/amd64/Packages  HttpError403
E: Some index files failed to download. They have been ignored, or old ones used instead.
```
at the end. Then:
```
root@3fb2482ad88f:/# sudo apt-get -y --force-yes install clusterhq-flocker-cli
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package clusterhq-flocker-cli
```
=> Replace hardcoded 14.04 in Ubuntu node instructions

flocker/node/script.py, flocker/node/test/test_script.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-2056
This removes some of the validation for zfs and loopback backends.  This is the easier option compared to adding proper validation for aws, openstack, and third-party backends (at least for now).  In general this was good validation and we should re-introduce it later in a way that's more friendly to extensions.
=> [FLOC-2056] Less agent.yml validation

flocker/acceptance/testtools.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-2057
This gives special treatment to a particular failure Twisted's web client can produce and makes sure to format as much information as we can get from it into the logs.
=> [FLOC-2057] Improved acceptance tests HTTP failure logging

admin/acceptance.py, admin/test/test_acceptance.py, docs/gettinginvolved/acceptance-testing.rst, flocker/provision/_install.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-2055
This changes the factoring of the acceptance test "runner" setup to make it easier to extend and it extends it to support a "managed" provider which just points at some already-running nodes.
The new provider isn't 100% feature complete (eg you have to install packages on it yourself).  Further enhancements would make this more usable but just being able to re-use some already-running nodes is already a big win.
=> [FLOC-2055] "Managed" acceptance test node provider/runner

flocker/node/_docker.py, flocker/node/functional/test_docker.py
Does not do anything with streaming, as mentioned in JIRA issue. This PR just prevents requests/urllib3 from using an infinite timeout, swapping it for a 10 minute timeout.
=> [FLOC-1788] Docker pull timeout

docs/gettingstarted/index.rst
A quick patch to make Getting Started Guide work with modified `sphinx-prompt`. Swaps the order of the `noscript` section with the normal tabbed section.
In `master`, the prompts are missing from the OS X and Ubuntu tabs since #1502  was merged. In this branch, the prompts should be back.
=> Swap tabs and noscript content, to make prompt styles work

admin/acceptance.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-2113
This makes the storage drivers section of the acceptance testing configuration file optional as it was intended to be.  Since the Vagrant runner doesn't accept any configuration, this fixes the issue (which seems to be that the slave is deployed with an old version of the configuration file).
Obsoletes #1518
=> [FLOC-2113] flocker/acceptance/vagrant/centos-7/zfs fails with a KeyError

flocker/node/agents/ebs.py
I went with 5 seconds, in hope that sometimes it'll be faster and 10 seconds is a long time.
=> [FLOC-2153] Add sleep before checking for result, to reduce polling

docs/reference/api_examples.yml, flocker/control/httpapi.py, flocker/control/schema/endpoints.yml, flocker/control/test/test_httpapi.py, flocker/control/test/test_schemas.py
Probably not *strictly* necessary, but I feel like it'll encourage people to interact badly with the API.
=> [FLOC-2143] Remove host attribute from /state/containers

docs/gettingstarted/index.rst
Fixes https://clusterhq.atlassian.net/browse/FLOC-2158
This also fixes https://clusterhq.atlassian.net/browse/FLOC-1309 by removing the last untested OS in the GSG.
=> [FLOC-2158] Remove Fedora 20 install instructions from the GSG

NEWS
Fixes https://clusterhq.atlassian.net/browse/FLOC-2083
It was agreed to ignore failing tests which are not release-specific. That means that (at least) the following test failures should be ignored in review:
* `flocker.provision.test.test_ssh_conch` `Reactor was unclean.` errors
* `flocker.acceptance.test_postgres.PostgresTests` timeouts on Vagrant
* Acceptance tests timeouts on Ubuntu / Rackspace
* Acceptance tests timeouts on CentOS 7 / Rackspace
**Important**: The branch should not be merged until the release process is complete.
=> [FLOC-2083] Release 0.4.1dev4

flocker/control/__init__.py, flocker/control/_clusterstate.py, flocker/control/_model.py, flocker/control/_protocol.py, flocker/control/script.py, flocker/control/test/clusterstatetools.py, flocker/control/test/test_clusterstate.py, flocker/control/test/test_protocol.py, flocker/control/test/test_script.py, flocker/node/_loop.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-2135
This includes:
* Changes to both sides of the AMP connection to send "ping" commands periodically.  This forces TCP-level disconnection notification in a timely manner.
* Changes to use AMP command dispatch as a signal of "activity" and considers this sufficient evidence that the agent is still operating properly.
* Changes to use "activity" (or inactivity) as the trigger for wiping state instead of using a hard-coded timeout on the age of the state itself.
It's probable this resolves FLOC-1896 as well.  The requirements there just say "do better".  This is probably better.
=> [FLOC-2135] Only invalidate agent-reported state if the agent really goes away

flocker/node/agents/blockdevice.py, flocker/node/agents/test/test_blockdevice.py
Design / fix for https://clusterhq.atlassian.net/browse/FLOC-2192
There's a test in this branch which demonstrates at least one of the problems we're seeing in the logs attached to FLOC-2192
```
Jun 09 16:41:29 acceptance-test-buildbot-0 flocker-dataset-agent[12516]: {"timestamp": 1433868088.771906, "task_uuid": "3701d26f-b458-407e-914c-5a544f
0d42ad", "message_type": "flocker:agent:converge:actions", "calculated_actions": "_InParallel(changes=pvector([DestroyBlockDeviceDataset(dataset_id=UU
ID('9ea3afb6-c3ca-4bef-8f0a-774a58fc005d')), MountBlockDevice(mountpoint=FilePath('/flocker/9ea3afb6-c3ca-4bef-8f0a-774a58fc005d'), dataset_id=UUID('9
ea3afb6-c3ca-4bef-8f0a-774a58fc005d'))]))", "task_level": [2, 4]}
```
The problem is that ``DestroyBlockDeviceDataset`` is a compound state change …
=> [FLOC-2192] Don't attempt to destroy nonmanifest datasets 

docs/using/installing/index.rst
Only one occurrence in the docs on master (installation doc). This is changed.
Definition of Stable and Experimental will be covered on FLOC 2045
=> [FLOC-2243] Remove Alpha and replace with Experimental

docs/_themes/clusterhq/layout_docs.html, docs/reference/authentication.rst, docs/using/installing/index.rst, flocker/docs/bootstrap/__init__.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-1979
The tabs appear to **not** render correctly in the branch as-is.  If someone knows how to fix that, I'd love to know (or just check it into the branch).  If not, then I guess we'll drop the tabs and just have one section after the other.
I also added a link to this section of the docs from the other section about certificates since the other section leaves the user hanging.
I also didn't add any instructions about the pkcs12 export password.  Possibly I should have?
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/1567)
=> [FLOC-1979] Client certificate instructions that work on OS X

admin/acceptance.py, docs/gettinginvolved/acceptance-testing.rst, flocker/provision/_aws.py
This has a corresponding config change to Buildbot (already in), so Buildbot will need to be restarted before the AWS acceptance tests will pass. Until this is merged *other* branches will fail to run AWS acceptance tests altogether, but its' not like they were passing before...
I do have a locally passing AWS acceptance test run, though, using this branch.
=> [FLOC-2244] Require zone when configuring AWS acceptance instances.

docs/using/installing/index.rst
CentOS and Ubuntu instructions moved so users don't miss essential instructions (these were previously below sections labelled as Alpha & Testing.
Note - while not part of this PR, we shouldn't be using Alpha in the docs. Issue raised: FLOC-2243
=> [FLOC-2209] Move the CentOS and Ubuntu instructions (above the Alpha and Testing sections)

admin/test/test_runner.py, flocker/provision/test/test_ssh_conch.py, flocker/testtools/ssh.py
In lieu of actually fixing [the actual bug in conch](https://twistedmatrix.com/trac/ticket/7936), this changes the `ISession` implementation that we use so that it sets `HOME` to the avatar's configured home directory.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/1580)
=> [FLOC-1884] Fix conch tests 

admin/acceptance.py
https://clusterhq.atlassian.net/browse/FLOC-2273
This is supposed to be handled by the Vagrantfile. Doing it again means we aren't testing what users will do.
=> [FLOC-2273] Dont provision vagrant in 1.0.0pre1.

flocker/node/agents/blockdevice.py, flocker/node/agents/test/test_blockdevice.py
Builds on #1605.
In theory this should fix postgres acceptance tests on AWS.
=> [FLOC-2289] Don't use world-writeable permissions if dataset has been modified with files

flocker/acceptance/test_deployment.py
#1602 was supposed to be this.
=> Use a realistic blocksize in test_application_volume_quotas.

flocker/node/_change.py, flocker/node/test/test_change.py
https://github.com/ClusterHQ/flocker/pull/1637 but with the right branch name. :cry: :cry:
=> [FLOC-2330] Release maintenance/flocker 1.0.0pre1/ - in_parallel error handling

README.rst
Fixes https://clusterhq.atlassian.net/browse/FLOC-2256
Done by testing the Flocker links, changing those which have moved, removing one which has gone from the docs it seems.
=> [FLOC-2256] Removed / changed broken links

NEWS, flocker/node/_change.py, flocker/node/test/test_change.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-2331 (sub-task of https://clusterhq.atlassian.net/browse/FLOC-2327) in the master.  Forward-port of #1637.
Has an extra change from the 1.0.0 release since that branch hasn't been merged yet.  Don't merge this until #1634 is merged.
=> [FLOC-2331] in_parallel error handling

flocker/node/agents/blockdevice.py, flocker/node/agents/test/test_blockdevice.py
`mkfs` will blindly run and make a filesystem on a device that already
has one, and it won't even tell you about it.
Look before we leap by running `blkid` to see what's there.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/1650)
=> Cannot make filesystem on device that has one

flocker/node/agents/blockdevice.py, flocker/node/agents/test/test_blockdevice.py
This applies the diff at #1650 to the release branch.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/1663)
=> Do not call mkfs on devices that already have filesystems

flocker/node/agents/blockdevice.py, flocker/node/agents/test/test_blockdevice.py
Reverts ClusterHQ/flocker#1653
For 1.0.1 we're going with a different implementation strategy to resolve this bug.  To minimize the size of the change, this change should be backed out because it will not be required for the alternate strategy.
=> Revert "[FLOC-2369] Store dataset UUIDs on filesystems we create"

flocker/node/agents/ebs.py, flocker/node/agents/functional/test_ebs.py, flocker/node/agents/test/test_ebs.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-2329
This is an entirely different approach to fixing the issue than was taken previously.  All of the filesystem UUID changes are gone.  This instead attempts to change the EBS storage driver so that it can reliably respond to `get_device_path` requests.
=> Release maintenance/flocker 1.0.0/ebs device name mapping floc 2329

docs/gettinginvolved/plugins.rst, docs/releasenotes/index.rst, docs/using/installing/index.rst
This is a somewhat light effort, but covers the EMC GitHub repos. I discussed this @ferrantim and this covers the EMC backend, but we will need to expand this in the future.
I've created FLOC 2442 and 2443 to make this whole section easier to find, and use.
=> [FLOC-2177] Add EMC links to Install doc

flocker/acceptance/test_api.py, flocker/acceptance/test_deployment.py, flocker/acceptance/testtools.py
https://clusterhq.atlassian.net/browse/FLOC-2400
This is in preparation for getting proper eliot logs from the acceptance tests.
=> [FLOC-2400] Remove useless return of `Cluster` from `Cluster` methods

NEWS
Fixes https://clusterhq.atlassian.net/browse/FLOC-2475
This is ready for a pre-tag review process.
The only failing tests are known and in ``flocker.provision.test.test_ssh_conch``.
Please follow http://doc-dev.clusterhq.com/gettinginvolved/infrastructure/release-process.html#pre-tag-review-process
=> [FLOC-2475] Release Flocker 1.0.1

CONTRIBUTING.rst, README.rst, docs/concepts/security.rst, docs/conf.py, docs/gettinginvolved/infrastructure/release-process.rst, docs/gettinginvolved/infrastructure/vagrant.rst, docs/gettinginvolved/plugins.rst, docs/labs/docker-plugin.rst, docs/labs/weave.rst, docs/using/installing/index.rst, docs/using/tutorial/vagrant-setup.rst
Fixes https://clusterhq.atlassian.net/browse/FLOC-2492
This changes redirected links, and then ignores links which are:
* Examples, to show a structure (e.g. a GitHub comparison)
* Password protected
* Failing because of https://clusterhq.atlassian.net/browse/FLOC-1156
FLOC-1156 is a follow up to this.
=> [FLOC-2492] Linkcheck

vagrant/tutorial/Vagrantfile
https://clusterhq.atlassian.net/browse/FLOC-2550
* Add python27-slim image to the vagrant VM as part of the vagrant provisioning tasks.
* Fixes Vagrantfile according to the Ruby Style Guide
=> add python27-slim docker image to Vagrantfile

flocker/acceptance/test_deployment.py
Raise `SkipTest` in test_application_volume_quotas, linking to the bug that tracks us fixing it.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/1733)
=> Skip test_application_volume_quotas, because it's flaky

NEWS, admin/package-files/rsyslog/flocker.conf, admin/packaging.py, admin/test/test_packaging.py, docs/releasenotes/index.rst, docs/spelling_wordlist.txt, docs/using/administering/upgrading.rst
To review you need to install generated RPM somewhere and run the services. Things you will need to verify:
1. Flocker logs are not in /var/log/messages. Maybe... ssh into running acceptance test node?
2. Logs are still available via journald. You can validate this by checking that the remote logs for the CentOS acceptance builders still contains Flocker logs.
=> Install rsyslog configuration file keeping Flocker logs out of /var/log

flocker/volume/functional/test_filesystems_zfs.py
If that is not explicitly done then some data may linger in userland
until the file is closed and so the error would be reported outside
the scope where we expect it.
See https://clusterhq.atlassian.net/browse/FLOC-2508
=> zfs test_maximum_size_enforced: flush the data to the kernel

flocker/provision/_install.py, flocker/provision/test/test_install.py
For review, check acceptance tests step `trial` stdio file includes the entire `agent.yml` file, not just the dataset backend. Search for `/etc/flocker/agent.yml`
This PR is against `master`. See previous review at #1725 which was against 1.0.1 (but not going to be merged).
=> [FLOC-2532] Fix dataset logging

README.rst
Once the fix to [FLOC-2567](https://clusterhq.atlassian.net/browse/FLOC-2567) lands, the badge will be out of date.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/1736)
=> Remove coveralls badge from README

flocker/volume/test/filesystemtests.py
The previous code had 2 problems and each of them ensured that the test
would pass (except for possible EPIPE) even if the tested code didn't behave as expected.
- previously the test would discard the first byte of the stream, so the
receiving side could know that the stream is corrupt just from reading
its header and thus it wouldn't need to read the rest of the stream
and so the exception would change little
- even if a completely valid stream were sent then the receiving side would
still reject it because 'snapshots' parameter was not passed to the
sending side and, thus, the sending side would generate a full stream
for a filesystem that already exists and that would be rejected
So now we make sure that an incremental stream is sent.
Also we send all of the stream except the last …
=> test_exception_aborts_write: the writer sometimes can get IOError/EPIPE

NEWS
Please review using pre-tag review process at http://doc-dev.clusterhq.com/gettinginvolved/infrastructure/release-process.html#pre-tag-review-process
We decided to live with failing conch tests in the 1.0 release.  See https://zulip.com/#narrow/stream/engineering/subject/1.2E0.2E2 for discussion around this.
=> [FLOC-2606] Flocker 1.0.2

flocker/acceptance/test_deployment.py
"Fixes" FLOC-2558
Increases the timeout on `flocker.acceptance.test_deployment.DeploymentTests` to 200 seconds. See https://clusterhq.atlassian.net/browse/FLOC-2558?focusedCommentId=18735&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-18735
This may be sufficient for our immediate purposes. AWS builds are passing (for now).
=> [FLOC-2558] Increase timeout on acceptance deployment tests

CONTRIBUTING.rst, docs/gettinginvolved/infrastructure/packaging.rst, docs/gettinginvolved/infrastructure/release-process.rst
#1724 removed the `doc` and `release` targets in `setup.py`. All the packages mentioned in these targets were moved to the `dev` target. This was done because most people who are developing Flocker will need all of these dependencies at some stage.
This PR removes some mentions of these targets which were missed in the earlier patch, replacing `doc` and `release` with `dev`.
In addition, the instructions in the `CONTRIBUTING.rst` file did not work, even when modified. So this patch also replaces these instructions with ones that work, and removes the bullet point structure to match the subsequent sections on running tests.
=> [FLOC-2581] Remove doc and release targets

NEWS, docs/releasenotes/index.rst
Fixes: https://clusterhq.atlassian.net/browse/FLOC-2617
Expected test failures:
* http://build.clusterhq.com/builders/flocker-centos-7/builds/5482 (these conch test failures are known and fixed or skipped in master)
* http://build.clusterhq.com/builders/flocker%2Facceptance%2Faws%2Fubuntu-14.04%2Faws/builds/1064 (this mongo object mismatch is already fixed in master)
Please follow the pre-tag release review process:
* http://doc-dev.clusterhq.com/gettinginvolved/infrastructure/release-process.html#pre-tag-review-process
=> [FLOC-2617] Release Flocker 1.0.3pre1

docs/spelling_wordlist.txt
https://clusterhq.atlassian.net/browse/FLOC-2625
ClusterHQ/build.clusterhq.com#120 moved the spelling builder to ubuntu 14.04. New versions don't like the spelling of `MiB` (I discovered this testing updated images on a staging buildbot).
=> [FLOC-2625] Add MiB to wordlist.

flocker/node/_docker.py, flocker/node/functional/test_docker.py, flocker/node/test/test_docker.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-1040
This changes the test to retry when it encounters this error.  In support of this, a new exception, `AddressInUse` is also introduced and the implementations updated to raise it when this particular failure is encountered.  In support for *this*, automatic port assignment (specify port 0, get a free port) is also added to the Docker client implementations.
Note the first revision in the branch is assorted refactoring I did while working on the rest.  Behavior changes are all in the second revision.
=> [FLOC-1040] test_added_is_listed intermittent failure

flocker/node/test/test_docker.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-2636
=> [FLOC-2636] don't write to /tmp in IDockerClientTests.test_added_is_listed

flocker/node/test/test_docker.py
The error in http://build.clusterhq.com/builders/flocker-centos-7/builds/5503/steps/trial/logs/stdio seems to be caused by /tmp running out of space. Don't use it and create a temporary path within trial's temp on the regular filesystem.
=> [FLOC-2628] Don't use /tmp

admin/build_targets/centos-7/Dockerfile
This PR makes `yum` display details about low-level network operations while building the CentOS Dockerfile. This additional information might be useful next time FLOC-2452 shows up, or for other network problems.  The additional information is sent to stderr, and gets logged near the top of the `flocker-omnibus-centos-7` `build-package` step.
=> [FLOC-2640] Display debug information to help diagnose yum network problems

flocker/acceptance/test_api.py
Does seem to fix the issue - notice that if I add a print statement for count it sometimes needs to retry:
```
flocker.acceptance.test_api
ContainerAPITests
test_linking ... 
1
2
[OK]
```
=> [FLOC-2633] Retry HTTP requests in case it takes a while for the HTTP server to start up

docs/install/post-install.rst
Fixes 2658
Due to this partially being completed on FLOC 2657, this PR only includes the addition of contents, and an amendment to the Next Steps text.
The final sub task of Story 2644 will move the Authentication steps into the Install section (FLOC 2716)
=> [FLOC 2658] Move the cluster install steps to a new document

admin/release.py
This PR enables the requests library logging to display the URLs and status of HTTP connections.  This makes it easier to see which URLs have failed if an error occurs.
This is particularly useful now, as we start running dev releases with the PEP440 changes.
To test, run a command like:
```
./admin/publish-artifacts --target=clusterhq-archive-testing --flocker-version=0.9.0pre1
```
In other branches, the only information is a stack trace and:
```
flocker.provision._effect.SequenceFailed: <SequenceFailed(results=[], exc_info=(<class 'requests.exceptions.HTTPError'>, HTTPError('404 Client Error: Not Found',), <traceback object at 0x3a65488>))>
```
With this branch, before the stack trace, we also see:
```
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): …
```
=> [FLOC-2746] Add network logging to release processes.

flocker/node/_docker.py, flocker/node/functional/test_docker.py, flocker/node/testtools.py, requirements.txt
Fixes:
* https://clusterhq.atlassian.net/browse/FLOC-2035
* https://clusterhq.atlassian.net/browse/FLOC-2627
Docker-py-1.3.1 fixes https://github.com/docker/docker-py/pull/681 which is what prevented `flocker-container-agent` pulling images from private registries.
Docker-py depends on Requests >= 2.5.1
* https://github.com/docker/docker-py/commit/9bed480c2745b06219c629dbbfd46b298c005447
So I updated that too.
I haven't updated `python-keystoneclient` - there doesn't seem any reason to. 
We can update all our dependencies properly when we start using `requires.io` or similar in 
* https://clusterhq.atlassian.net/browse/FLOC-1172
FLOC-2035 says "restore test that depends on modern requests" but the commit ID in the issue description refers to something different. So I'll leave that unless …
=> [FLOC-2035] [FLOC-2627]  Upgrade to docker-py-1.3.1 and requests-2.7.1

docs/gettinginvolved/index.rst, docs/index.rst, docs/introduction/index.rst
Fixes 2389
Note - the issue requests that the content be copied from the Introduction to Flocker page - I thought this was unnecessary repetition, and have written a short intro to the documentation, and what the user can expect to find.
=> [FLOC 2389] Update info in the Flocker Doc landing page

NEWS, docs/releasenotes/index.rst, docs/spelling_wordlist.txt, docs/using/config/usage.rst
Fixes: https://clusterhq.atlassian.net/browse/FLOC-2757
News and What's New changes are based on the aborted dev1 release in https://github.com/ClusterHQ/flocker/pull/1779 with a few additions.
=> [FLOC-2757] Release Flocker 1.1.0.dev2

admin/publish-artifacts, admin/release.py
The change in #1803 made `publish-artifacts` display useful logging information. However, it also added logging to commands such as `test-redirects` which uses the same module for its core functions.
While the debugging info helps in `publish-artifacts`, it obscures in `test-redirects`. Hence, this PR moves the logging setup code into the top-level `publish-artifacts` script, so it only affects that code.
The command `./admin/publish-artifacts --flocker-version=0.9.0pre1 --target=clusterhq-archive-testing` still provides network logging.
The command `./admin/test-redirects` does not. (It will probably complain about the redirects, but will not display INFO and DEBUG messages).
=> [FLOC-2775] Move logging setup from release code to publish-artifacts

admin/release.py, admin/test/test_release.py
Fixes: https://clusterhq.atlassian.net/browse/FLOC-2768
I'm attempting to test this by finishing off the `1.1.0.dev2` release.
```
(2768)(fix-publish-artifacts-FLOC-2768 ✕?)[~/.../HybridLogic/flocker]$ ./admin/publish-artifacts --flocker-version=1.1.0.dev2
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): build.clusterhq.com
DEBUG:requests.packages.urllib3.connectionpool:"GET /results/omnibus/1.1.0.dev2/centos-7/clusterhq-python-flocker-1.1.0-0.dev.2.x86_64.rpm HTTP/1.1" 200 24757867
DEBUG:requests.packages.urllib3.connectionpool:"GET /results/omnibus/1.1.0.dev2/centos-7/clusterhq-flocker-cli-1.1.0-0.dev.2.noarch.rpm HTTP/1.1" 200 2325
DEBUG:requests.packages.urllib3.connectionpool:"GET /results/omnibus/1.1.0.dev2/centos-7/clusterhq-flocker-node-1.1.0-0.dev.2. …
```
=> [FLOC-2768] Pass the requirements.txt path to make_recipe

flocker/control/test/test_httpapi.py, flocker/dockerplugin/__init__.py, flocker/dockerplugin/_api.py, flocker/dockerplugin/schema/endpoints.yml, flocker/dockerplugin/schema/types.yml, flocker/dockerplugin/test/__init__.py, flocker/dockerplugin/test/test_api.py, flocker/dockerplugin/test/test_schemas.py, flocker/restapi/testtools.py, setup.py
1. Move a bunch of utility code out of `flocker.control.test.test_httpapi` and into `flocker.restapi.testtools`. It is not modified in any way.
2. Add basic (output) schema and API call implementations for three trivial Docker plugin API endpoints.
The relevant documentation:
https://github.com/docker/docker/blob/master/docs/extend/plugin_api.md#pluginactivate
https://github.com/docker/docker/blob/master/docs/extend/plugins_volume.md#volumedriverremove
https://github.com/docker/docker/blob/master/docs/extend/plugins_volume.md#volumedriverunmount
=> [FLOC-2783] Simple API calls for Docker plugin API

docs/_themes/clusterhq/layout_docs.html
Optimizely snippet.
Fixes FLOC-2677
http://build.clusterhq.com/results/docs/docs-optimizely-FLOC-2677/build-9236/ is running a test at the moment, I changed the text to 
> You are reading an in-development version of the documentation. Some of the functionality may not work as expected. Things may break.
In the warning I added "Things may break"
=> [FLOC-2677] add Optimizely to docs template

admin/client.py, admin/run-client-tests, docs/gettinginvolved/acceptance-testing.rst, docs/gettinginvolved/client-testing.rst, flocker/provision/_install.py, flocker/provision/_ssh/__init__.py, flocker/provision/_ssh/_conch.py, flocker/provision/_ssh/_model.py
The client tests currently start cloud nodes for testing. Since the tests are very short, this is wasteful in time and money, especially since the tests do not need the same capabilities as the acceptance tests.
This PR changes the tests to use a local Docker container.
Apart from the resource usage argument above, this PR is motivated by
- FLOC-2750, regarding client test failures due to cloud request limits, and 
- the code review of FLOC-2769.  The problem with the PR #1820 is that the cloud tests do not maintain the environment between commands. Each command runs in a separate SSH channel. This prevents `virtualenv` being used sensibly. The Docker Runner in this PR supports keeping the environment between commands in a sequence, so will allow a cleaner solution to that PR.
Although …
=> [FLOC-2771] Run client installation tests using Docker

flocker/provision/_libcloud.py
… to reduce chances of hitting rate limits on cloud provider.
Node startup takes a while anyway, so it's unlikely to slow us down much. Longer term we will pre-provision nodes so we won't have this speed hit at all.
=> [FLOC-2751] Check if node exists every 15 seconds instead of every 3 seconds

LICENSE, admin/LICENSE.template, admin/release.py, admin/test/test_release.py, admin/update-license, docs/gettinginvolved/infrastructure/release-process.rst
Fixes https://clusterhq.atlassian.net/browse/FLOC-1968
This duplicates the LICENSE file into a template and makes two changes to it:
* A set of braces "`{}`" are replaced with "`{{}}`", but this does not change the rendered file
* Instead of `2014, 2015` the LICENSE file now has `2014-{current_year}`.
=> [FLOC-1968] Automate copyright changes in license

flocker/restapi/_error.py, flocker/restapi/_infrastructure.py, flocker/restapi/test/test_infrastructure.py
1. Docker doesn't send it, and Docker API plugin needs to deal with this somehow.
2. More generally, it's better to be lenient in what one accepts.
=> [FLOC-2866] REST API no longer requires application/json content-type

flocker/control/_model.py, flocker/control/_persistence.py, flocker/control/test/persisted_model.json, flocker/control/test/test_model_change.py, setup.py
If someone changes `flocker.control._model` this should detect that and cause a failing test, warning the developer that they need to write upgrade code for our on-disk format.
Support for upgrade code is being implemented in a different branch.
=> [FLOC-2851] Configuration model change detection

CONTRIBUTING.rst
Fixes 2481
In addition, this PR removes ref tags from the CONTRIBUTING.rst document, which don't work in GitHub, and replaces them with links to the latest pages on the ClusterHQ website.
=> [FLOC 2481] Update CONTRIBUTING.rst for consistency

flocker/node/functional/test_docker.py, flocker/node/test/test_docker.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-2909
This is a work-around for a Docker 1.8.1 / Docker hub bug.  Hopefully Docker upstream will fix whatever the underlying problem is.  This avoids us having hanging/failing test suite meanwhile.
Note that BuildBot is still using an older version of Docker - probably around 1.3.3.  Ideally we would have coverage on the CI system for the old and new versions of Docker until we finish the transition.  Failing that, build results against Docker 1.8.1 are available at http://54.200.233.212/boxes-flocker?branch=http-app-latest-FLOC-2909 (for as long as I happen to be running that alternate master).
=> [FLOC-2909] Use openshift/busybox-http-app:latest

docs/labs/docker-plugin.rst, docs/labs/installer.rst
Fixes FLOC 2890
* Mention that CoreOS is supported as experimental option.
* Uncomment ZFS support because unofficial-flocker-tools#2 landed.
* Fix typo in FDP install page
* Mention that FDP doesn't depend on Docker experimental any more.
=> [FLOC-2890] CoreOS & ZFS labs docs for installer

admin/yum.py, dev-requirements.txt
Fixes https://clusterhq.atlassian.net/browse/FLOC-2904
I ran `admin/publish-artifacts --flocker-version=1.2.0.dev1` from the tag of the last dev release with these changes. This has been tested by running the Ubuntu CLI instructions from http://doc-dev.clusterhq.com/install/install-client.html#ubuntu-14-04.
The initial problem was that various versions of `dpkg-scanpackages` had different outputs - we didn't notice until we started doing releases outside of Vagrant. The approach that this uses is to introduce a Python dependency which has consistent output across the `dpkg-scanpackages` versions I've tested and has the side-effect of making the code nicer, in my opinion.
=> Ubuntu packages floc 2904

build.yaml
need to disable selinux setenforce 0 calls, as selinux is disabled on the baked image.
This causes the job to fail
=> Remove setenforce from aws centos jenkins jobs floc 2891

build.yaml
Disabling SElinux setenforce 0 calls, as selinux is disabled on the new baked images.
Had to update the instance types as I had a few out-mem conditions with the T2micros.
With the new images we aren't requited to use the M3 old generation instances and can use T2 all around
=> Change instance types floc 2891

flocker/node/functional/test_docker.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-2910
This will be used to help resolve FLOC-2911 and FLOC-2912, at least.
Note diff is wrong, it includes already-merged changes from #1871
=> [FLOC-2910] Factor out code for running a registry and pushing an image

flocker/node/functional/test_docker.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-2911
Fixes https://clusterhq.atlassian.net/browse/FLOC-2882
This removes the possibility of intermittent failures of this test caused by problems with Docker hub itself or with the test client's network connection to Docker hub.
FLOC-2882 is fixed as a side-effect due to the deterministic control afforded (and exercised) over the local registry the test now talks to.
See FLOC-2902 and FLOC-2910 for further context.
Depends on #1874 (note diff is currently wrong, including those changes)
=> [FLOC-2911] [FLOC-2882] Don't use Docker hub in test_pull_timeout

flocker/node/agents/_logging.py, flocker/node/agents/ebs.py, flocker/node/agents/functional/test_ebs.py
Fix bug in EBS driver that causes failure in logging devices in use while attempting to find an available device name during attach_volume.
=> [FLOC-2607] Fix invalid Eliot log message from EBS driver.

flocker/__init__.py
We're seeing [segfaults in our tests](https://clusterhq.atlassian.net/browse/FLOC-2913), and the evidence points to them being [due to pyrsistent's C extensions](https://github.com/tobgu/pyrsistent/issues/52). 
To do this patch, I followed the [advice from Jean-Paul and Itamar in the comments](https://clusterhq.atlassian.net/browse/FLOC-2913?focusedCommentId=19430&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-19430) and the pattern already established in `flocker/__init__.py`. 
Writing a good automated test for this is tricky, and since neither `_suppress_warnings` nor `_redirect_eliot_logs_for_trial` have automated tests, I haven't done so.
I *have* run the `flocker.control.test.test_persistence` tests (i.e. the tests that segfault) locally, and used `ps` …
=> [FLOC-2913] Disable pyrsistent C extensions

flocker/node/agents/ebs.py
From builder flocker/functional/aws/ubuntu-14.04/storage-driver logs (http://build.clusterhq.com/builders/flocker%2Ffunctional%2Faws%2Fubuntu-14.04%2Fstorage-driver/builds/2209), all ``Method`` key values are ``POST``, and all ``Path`` key values are ``/``:
_______
Madhuris-MacBook-Pro-2:~ madhuriyechuri$ grep "Method:" /tmp/m2 | wc -l
376
Madhuris-MacBook-Pro-2:~ madhuriyechuri$ grep "Method:" /tmp/m2 | grep -v POST | wc -l
0
Madhuris-MacBook-Pro-2:~ madhuriyechuri$ grep "Path:" /tmp/m2 | wc -l
376
Madhuris-MacBook-Pro-2:~ madhuriyechuri$ grep "Path:" /tmp/m2 | grep -v "Path: /" | wc -l
0
Madhuris-MacBook-Pro-2:~ madhuriyechuri$ cat /tmp/m2 | wc -l
1765
_______
Reduce log spew by 42% by removing these logs that aren't useful for debugging.
=> [FLOC-2929] Reduce EBS driver log spew by avoiding logging "msg": "Path: /" and "Method: POST"

flocker/node/functional/test_docker.py
As discussed on [FLOC-2949](https://clusterhq.atlassian.net/browse/FLOC-2949), I prematurely upgraded the version of docker on the slaves, causing the tests to fail. 
This patch disables those tests in the sure and certain hope that we can land [FLOC-2912](https://clusterhq.atlassian.net/browse/FLOC-2912) (#1877) and [FLOC-2915](https://clusterhq.atlassian.net/browse/FLOC-2915) (#1878) quickly.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/1896)
=> [FLOC-2949] Mark failing Docker tests as expected failing

flocker/__init__.py
Eliot imports pyrsistent, so we need to disable C extension first.
Also fix docstring and copyright, since I was touching the module anyway.
=> [FLOC-2913] Disable pyrsistent C extension earlier in the startup process

flocker/node/_deploy.py, flocker/node/agents/blockdevice.py, flocker/node/agents/test/test_blockdevice.py, flocker/node/test/test_deploy.py, flocker/node/testtools.py
If a lease is held on a dataset on the current node we shouldn't delete it or resize it or unmount it, since that means it's in use. (Eventually leases will be the only way to make things in-use, but for now we also consider application state.)
=> [FLOC-2740] Respect leases when calculating changes

docs/reference/api_examples.yml, flocker/control/httpapi.py, flocker/control/schema/endpoints.yml, flocker/control/schema/types.yml, flocker/control/test/test_httpapi.py, flocker/control/test/test_schemas.py
1. Expand schema to know about leases. The tests were structured so the good/bad examples can be re-used in later schema tests.
2. Add a new endpoint for listing leases.
=> [FLOC-2736] REST API endpoint: list leases

flocker/apiclient/_client.py, flocker/apiclient/test/test_client.py
1. HTTP requests and response are logged.
2. Logging can be traced from the requesting process on to the REST API process.
Builds on #1898, which should be reviewed first.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/1902)
=> [FLOC-2873] REST API client logging

admin/acceptance.py, flocker/acceptance/endtoend/test_dockerplugin.py, flocker/dockerplugin/_api.py, flocker/dockerplugin/test/test_api.py, flocker/node/_docker.py
Demonstrate that volumes can be moved to different containers on the same node and on different nodes.
This also includes a fix to the way the plugin API work which is necessary for the tests to pass: the `/VolumeDriver.Path` call needs to return a result immediately even if it doesn't know the path yet.
Finally, the acceptance test remote log capture also captures the flocker-docker-plugin logs since that was helpful when debugging.
=> [FLOC-2946] Docker plugin acceptance tests for volume movement

docs/_themes/clusterhq/layout.html, docs/_themes/clusterhq/layout_docs.html, docs/_themes/clusterhq/layout_version.html, docs/index.rst, docs/version.rst
Added javascript to AJAX GET https://docs.clusterhq.com/en/lates/version.html and compare to DOCUMENTATION_OPTIONS
Added new theme with no markup for version output. Added logic to use plain layout for version.rst.
Fixes FLOC-2529
=> [FLOC-2529] Add notice for out of date docs

flocker/node/agents/cinder.py, flocker/node/agents/functional/test_cinder.py, flocker/node/agents/functional/test_cinder_behaviour.py
This PR adds a more explicit check of the states that Cinder volumes traverse when performing create/delete and attach/detach operations.  This allows unexpected states to raise a more useful exception. See, in particular, the test `test_disk_attachment_fails_with_conflicting_disk` in `test_cinder.py`, which now sees an UnexpectedStateError rather than a TimeoutError.  The error is both more informative and occurs sooner.
To quote https://github.com/ClusterHQ/flocker/pull/1910:
"Unfortunately these tests can not be run using our existing CI system and are currently being run manually on a devstack instance running on an on-metal Rackspace server. To run these tests, ssh into the Rackspace server then ssh into the guest node on this server. The code has already been checked out on this …
=> [FLOC-2970] Improved wait error

README.rst
The link was broken, probably pointing to an old url.
=> Update link to "installing" documentation

flocker/node/agents/functional/test_cinder.py
Fixes: https://clusterhq.atlassian.net/browse/FLOC-2975
This is a cleanup for the tests added in #1910 
Those tests copied PKI keys and certs into the `/etc/pki` directories, and left them there.
This PR creates the keys and certs in a temporary directory, which is removed at the end of test.
This PR also renames the factory function for the `VirtIOClient` to give a better idea of it's main characteristics; `from_instance_id` was a terrible but simple name. `using_insecure_tls` is more informative, and emphasises that this should not be used outside it's current context without detailed consideration.
To quote PR #1910:
> Unfortunately these tests can not be run using our existing CI system and are currently being run manually on a devstack instance running on an on-metal Rackspace …
=> [FLOC-2975] Cleanup PKI keys used for testing

NEWS, docs/releasenotes/index.rst
Reasoning for Buildbot failures:
1. http://build.clusterhq.com/builders/flocker%2Facceptance%2Faws%2Fcentos-7%2Faws/builds/2006/steps/trial/logs/stdio
Failed due to flocker.acceptance.endtoend.test_dockerplugin failure. This test seems to have failed in the recent runs as well: http://build.clusterhq.com/builders/flocker%2Facceptance%2Faws%2Fcentos-7%2Faws/builds/1992/steps/trial/logs/stdio
-> Waiting on confirmation that this is currently being worked on.
2. http://build.clusterhq.com/builders/flocker%2Facceptance%2Faws%2Fubuntu-14.04%2Faws/builds/2054/steps/trial/logs/stdio
-> Known issue: FLOC-1384
3. http://build.clusterhq.com/builders/flocker-centos-7/builds/6516/steps/trial/logs/stdio
``test_pull_image_if_necessary`` is an intermittent known failure …
=> [FLOC-2974] Release Flocker 1.3.0

flocker/node/agents/cinder.py, flocker/node/agents/ebs.py, flocker/node/agents/functional/test_cinder.py, flocker/node/agents/functional/test_cinder_behaviour.py, flocker/node/agents/functional/test_ebs.py, flocker/node/agents/test/blockdevicefactory.py
The block device test code duplicates code for setting up `IBlockDeviceAPI` instances. In `master`, a good example is https://github.com/ClusterHQ/flocker/blob/9ebddf05cf6fc68dbd0f1af5a1d983efa232d716/flocker/node/agents/test/blockdevicefactory.py#L181-L189 which duplicates https://github.com/ClusterHQ/flocker/blob/9ebddf05cf6fc68dbd0f1af5a1d983efa232d716/flocker/node/agents/cinder.py#L773-L782.
This PR rewrites this code to reduce this repetition. The main change is that `get_blockdeviceapi_args`, which returned a factory function and a dictionary to apply to that function, is replaced by a simpler `get_blockdevice_config`, which just returns the configuration stanza relevant to the tested platform.  This means the caller needs to do a bit more work (see the change to the …
=> [FLOC-2985] Remove duplication in block device test setup

flocker/acceptance/endtoend/test_dockerplugin.py, flocker/acceptance/endtoend/test_leases.py, flocker/acceptance/testtools.py, flocker/apiclient/_client.py, flocker/control/httpapi.py
Fixes: https://clusterhq.atlassian.net/browse/FLOC-2741
This isn't quite what we designed, notably:
* We can't just move / delete a dataset from underneath a running container; the Docker bind mount prevents the Flocker dataset being unmounted.
* The 10s delay is really ugly, but how else can we catch the potential important error that would result in flocker-dataset-agent unmounting a leased dataset?
* We'd originally planned to write tests for expiring leases too, but that's difficult because we can't really know what expiry time to use when acquiring the lease. It depends on how quickly docker responds to API requests. We could set a really long expiry time, but that would slow down the tests.
=> [FLOC-2741] End to end tests for leases

flocker/provision/_install.py, vagrant/tutorial/post-reboot-bootstrap.py
ZFS 0.6.5 has stopped loading modules when the `zpool` command is run.  This prevents our Vagrant Tutorial box from building, and may cause problems for people using our instructions to build a ZFS backend.
It is possible to add the environment variable `ZFS_MODULE_LOADING=yes` to continue to load modules, as for older versions of ZFS.  This is a temporary provision in the ZFS code, which will be removed at a later date. This PR applies this to our ZFS commands, to ensure our tests continue to pass when ZFS 0.6.5 is installed.
An additional issue https://clusterhq.atlassian.net/browse/FLOC-3018 exists to provide a more permanent solution.
As this issue prevents a test from passing, I would like to merge it, even if some other tests fail: particularly those that do not deal with ZFS, and …
=> [FLOC-3016] Add support for ZFS 0.6.5

flocker/provision/_install.py
Fixes: https://clusterhq.atlassian.net/browse/FLOC-3008
The command to install the repo YUM package on CentOS needs to work on both systems where Flocker has been installed previously, and on systems where it hasn't.
Although `yum install` handles a repeated install fairly cleanly, it does exit with non-zero, causing problems for our automated testing.
A previous attempt to solve this changed the command to `yum update` which works on systems where Flocker has been installed before, but fails on fresh systems.
The whole exercise was obscured by the fact that for Buildbot tests, another repo is added to make the branch repos available, thus masking the absence of the production repo, until the actual instructions in the docs are followed.
This PR checks whether the yum package is installed …
=> [FLOC-3008] Idempotent repo installation on CentOS

flocker/provision/_install.py, vagrant/tutorial/post-reboot-bootstrap.py
This patch needs to be applied to the 1.3 branch in order for tests to pass, so that we can release 1.3.1 for other significant bugs.
=> [FLOC-3021] Backport ZFS 0.6.5. fix to release 1.3.0

admin/acceptance.py, docs/releasenotes/index.rst, flocker/acceptance/endtoend/test_dataset.py, flocker/acceptance/endtoend/test_leases.py, flocker/acceptance/testtools.py, flocker/node/agents/cinder.py, flocker/node/agents/functional/test_cinder.py, flocker/provision/_common.py
Merging Cinder device fix into master. This has already been merged into release/flocker-1.3.1 as part of FLOC-3009.
This was a bit tricky because of a conflict in flocker/acceptance/testtools.py. This PR removes the use of REALISTIC_BLOCKDEVICE_SIZE in function create_dataset, while another change adds a dataset_id parameter to that function. Since this removed the import of REALISTIC_BLOCKDEVICE_SIZE from the flocker.acceptance.testtools file, the test_leases module needed to be changed to import it from it's actual source, the flocker.testtools module.
=> [FLOC-3010] Accurate device path for Cinder devices

NEWS, docs/config/zfs-configuration.rst, docs/releasenotes/index.rst
This is the merge of release 1.3.1 into master.  It is done as a separate PR due to a merge conflict in the `NEWS` file between the 1.3.1 entry and the 1.4.0dev1 in `master`.  See https://clusterhq.atlassian.net/browse/FLOC-3048 for an explanation of why this is done as a separate PR to the release PR.
This PR should be the same as the 1.3.1 PR #1948 but with the 1.3.1 NEWS below the 1.4.0dev1 NEWS (i.e. in version order, not chronological order).
=> [FLOC-3049] Merge Flocker 1.3.1into master

flocker/apiclient/test/test_client.py
Sometimes, it takes long enough to communicate with a real API that a shorthold lease has expired before we attempt to reacquire it, hence the intermittent failure. This change gives the lease a 60 second expiry and ensures we have successfully acquired it before attempting to acquire a lease on the same dataset on a different node.
=> [FLOC-3015] Fix intermittent lease test failure

flocker/node/_loop.py, flocker/node/test/test_loop.py, flocker/testtools/__init__.py
Send node agent state to control agent only if:
- it differs from previously reported state, or,
- previous state send failed, or,
- last known state was sent to a different client.
@tomprince and i paired on this issue.
=> [FLOC-3036] Send node agent state only if it changed or new client.

docs/conf.py
The UserVoice website hosted at https://feedback.clusterhq.com is sending 403 Forbidden to Buildbot requests, probably because it frequently performs robot requests.
This PR stops checking the single link to the forum, to prevent linkcheck tests being permanently orange, and to be nice to someone who apparently doesn't want us knocking.
Note, I haven't actually confirmed that this is why Buildbot is getting 403.  The check works when running `make linkcheck` from a laptop.
=> [FLOC-3014] Link check for UserVoice is forbidden

docs/reference/api_examples.yml, docs/releasenotes/index.rst, flocker/control/httpapi.py, flocker/restapi/docs/publicapi.py, flocker/restapi/docs/test/test_publicapi.py
1. Make leases API endpoints public.
2. Fix various minor content and formatting issues in the examples and API endpoints.
3. Make the JSON API property documentation format correctly in the face of multi-type properties, in particular the "expires" property which supports both numbers and `null`.
=> [FLOC-3050] Make leases API public

flocker/apiclient/test/test_client.py
Fixes FLOC-3079. The test was failing because the persistence service and API service in this test suite are instantiated using different `IReactorTime` implementations, one using `Clock` and the other using the global `reactor`. This meant that leases created via the API were being created with an expiry calculated as seconds from Unix time, whereas the leases expiry loop (which compares datetimes) was checking the expiry against the real current time. Hence leases that had seemingly expired over 40 years ago :scream:
=> [FLOC-3079] Intermittently failing lease test

NEWS
All buildbot tests passed.
`docs/releasenotes/index.rst` does not appear to need any changes.
=> [FLOC-3093] flocker 1.4.0.dev2

admin/homebrew.py, admin/test/test_homebrew.py
Fixes an error on Jenkins where building the package fails due to a '+' signal
```
11:52:48 + /tmp/v/bin/python admin/build-package --destination-path repo --distribution OSX /flocker/dist/Flocker-1.4.0.dev1+71.g8a99cdb.tar.gz
11:52:50 Traceback (most recent call last):
11:52:50   File "admin/build-package", line 13, in <module>
11:52:50     main(top_level=TOPLEVEL, base_path=BASEPATH)
11:52:50   File "/scratch/jenkins/workspace/ClusterHQ-flocker/flocker-create-jenkins-osx-job-FLOC-2854/run_client_installation_on_OSX/admin/packaging.py", line 1315, in main
11:52:50     distribution=options['distribution'],
11:52:50   File "/scratch/jenkins/workspace/ClusterHQ-flocker/flocker-create-jenkins-osx-job-FLOC-2854/run_client_installation_on_OSX/admin/packaging.py", line 1125, in build_in_docker …
```
=> [FLOC-3023] + signs aren't allowed in ruby class names

flocker/node/_loop.py, flocker/node/test/test_loop.py, flocker/testtools/__init__.py, flocker/testtools/amp.py, flocker/testtools/test/test_amp.py
https://clusterhq.atlassian.net/browse/FLOC-3090
This is the expedient solution. One issue with it, is that it delays convergence iterations after this one until after the control node acknowledges the state update.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/1970)
=> [FLOC-3090] Implement back-pressure on agents sending updates.

admin/package-files/docker-plugin/systemd/flocker-docker-plugin.service, admin/package-files/systemd/flocker-container-agent.service, admin/package-files/systemd/flocker-control.service, admin/package-files/systemd/flocker-dataset-agent.service, flocker/common/_journald.py, flocker/common/functional/test_script.py, flocker/common/script.py
By logging directly using the journald APIs we can avoid a bug where log messages are line wrapped on 2048 byte boundaries. This means log messages will now be much easier to process with tools like `eliot-tree`.
The `sleep` in the tests is problematic; not sure what else to do about fact that logging takes a little bit of time to show up in `journalctl` output. Maybe retry a few times?
=> [FLOC-1796] Fix problem where log messages were being wrapped

flocker/control/_protocol.py, flocker/control/test/test_protocol.py
Instead of serializing config and state to JSON once for each destination, we only do it once.
The actual end-to-end result of this (lower CPU usage, i.e. the fact that we have caching enabled in `_send_state_to_connections`) is not tested, it's not clear to me how one would given current abstractions. Ideas welcome.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/1972)
=> [FLOC-3100] Memoize wire encode when sending updates to agents

flocker/node/_deploy.py, flocker/node/test/test_deploy.py
Fixes FLOC-3107. Previously we overlooked the memory limit and CPU shares coming back from a Unit when listing container state and didn't include these in the Applications we construct when discovering node state, hence erroneously constructing a model that represented a different state than that desired from the configuration and calculating changes accordingly - so containers were continuously created, destroyed and recreated when using these options.
=> [FLOC-3107] Include CPU shares and memory limit in Applications

docs/install/index.rst, docs/install/install-client.rst, docs/install/install-node.rst
An addition to previous PR from @lukemarsden - this amendment ensures that the user is aware that they are clicking a link that take them into the Labs installer instructions.
=> [FLOC 2993] Adding Labs context to Installer docs

flocker/control/_protocol.py, flocker/control/test/test_protocol.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-3110
This allows arbitrarily large (more or less) `Deployment` objects to be passed around as cluster configuration (using the recently introduced `Big` argument type).  It does likewise for `DeploymentState` objects.
Note that arbitrarily large `NodeState` objects passed from agents to the control service in `NodeStateCommand` are not supported.  They have a small serialization quirk and will need a slightly different strategy applied.
=> [FLOC-3110] Support big cluster configurations and numbers of nodes

flocker/node/agents/functional/test_ebs.py
This test assumes that '/dev/sda1' is the only device in use at the beginning of the test, which is not true in all test run environments. For example, my EC2 instance had the following devices before any functional tests ran:
```
brw-rw----  1 root disk    202,   0 May 13 22:37 xvda
brw-rw----  1 root disk    202,  80 Jun 11 04:09 xvdf
```
Attempted to cleanup volumes (``detach_destroy_volumes``) at the beginning of the testcase, but realized this is not sufficient for predictable test outcome either.
=> [FLOC-3122] Remove useless test test_in_use_device_log.

flocker/node/functional/test_deploy.py
Fixes FLOC-3114 - this should make the two affected tests less flaky by a) ensuring the unit we assert on is the correct unit, rather than assuming it's the only unit and b) checking that an assertion on a unit definitely happened.
=> [FLOC-3114] Intermittent deployer test failure

docs/releasenotes/index.rst, flocker/node/_loop.py, flocker/node/test/test_loop.py, flocker/node/testtools.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-3135
This ended up not being OpenStack specific.  As long as we actually retry the OpenStack operation, we'll eventually get results again.
=> [FLOC-3135] Handle exceptions from IDeployer.discover_state in the convergence loop

docs/_themes/clusterhq/static/css/docs.css
Before:
After:
@adamtheturtle You said you'd merge this.
=> [FLOC-1292] Make admonition links be visible.

admin/package-files/systemd/flocker-container-agent.service, admin/package-files/upstart/flocker-container-agent.conf, flocker/node/script.py
Fixes: https://clusterhq.atlassian.net/browse/FLOC-3150
Original plan was to modify systemd service files, but
* this alternative change means we don't have to add duplicate changes to upstart files, and
* that we can log the reason for the startup delay in Eliot format, and
* we can import the actual `EXPIRATION_TIME` used by the state wiper service.
After discussion with @exarkun we decided not to include our acceptance test for this change since it won't reliably run on Buildbot.
See reliable-reboot-acceptance-test-FLOC-3150 for the acceptance test for manual testing.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2001)
=> [FLOC-3150] Add a delay before starting the container-agent loop

flocker/control/_protocol.py, flocker/control/test/test_protocol.py, flocker/testtools/amp.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-3140
The general idea here is that because many different things trigger a full update of cluster parameters (state and configuration) to agents, it is often the case that several full updates will be sent to an agent before it has even had a chance to process the first update.  In these cases, the first update is unavoidable and the last update is useful but the intermediate updates are useless and we can avoid sending them.  So, do.
Since we only have manual, ad hoc benchmarking in place at the moment, here are some results from my manual, ad hoc benchmarks:
Without this change, it takes longer than 10 minutes (I didn't wait to see much much longer) for flocker-control to finish processing all of the events generated on the startup of a …
=> [FLOC-3140] Coalesce redundant cluster parameter updates to agents

flocker/node/agents/cinder.py, flocker/node/agents/functional/test_cinder.py
This PR adds 'available' as an expected state when attaching volumes using the Cinder client. Although the volume goes through the sequence `('available', 'attaching', 'in-use')`, the state 'available' was missing as an expected state because we have never seen 'available' occur in the attachment sequence. 
For detaching, we had seen the state 'in-use' occur at the start of the sequence `('in-use', 'detaching', 'available')`.  Hence, the equivalent detach code includes the initial state. 
Perhaps due to speedups introduced through recent patches, we have now seen the unexpected 'available' state occur in attachment.  Hence, we add it to the code as an expected state.
This has the nice effect of making the `attach_volume` and `detach_volume` functions more symmetric.
Note, there is another …
=> [FLOC-3155] Add 'available' as a possible transient state when attaching Cinder volumes

flocker/provision/_libcloud.py
https://clusterhq.atlassian.net/browse/FLOC-3158
My hypothesis is that https://clusterhq.atlassian.net/browse/FLOC-3152 is caused by `RequestLimitExceeded`. By propagating the error, we can see if that is in fact the case.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2005)
=> [FLOC-3158] Re-raise `RequestLimitExceeded` instead of `CloudKeyNotFound`.

admin/homebrew.py, admin/test/test_homebrew.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-3164
This has been manually tested on OS X 10.11 (output below).
A new issue has been created to choose supported OS X platforms and set up CI for those which are supported: https://clusterhq.atlassian.net/browse/FLOC-3171.
```
~$ flocker-deploy --version
-bash: flocker-deploy: command not found
~$ brew uninstall openssl
Error: No such keg: /usr/local/Cellar/openssl
~$ curl -O http://build.clusterhq.com/results/homebrew/osx-10-11-FLOC-3164/Flocker4eb91690e0df4459dbb1e8d4ae994e065ab63d70.rb
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100 11642  100 11642    0     0  13894      0 --:--:-- --:--:-- --:--:-- 13892
~$ brew install …
```
=> Osx 10 11 floc 3164

build.yaml
Use a different virtualenv path so that we can start having multiple builders per jenkins slave.
This removes a contention point where virtualenv was placed under /tmp/v
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2017)
=> Flocker venv random FLOC-3179

build.yaml
Update fpm-cron nightly jobs to use the same AMIs as flocker.
This means one less AMI to maintain.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2015)
=> update fpm cron jobs to use flocker AMI FLOC-3180

flocker/node/agents/test/test_blockdevice.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-1756
Functionality was already implemented at some point in the past, it seems.  Test just needs unskipping and it passes.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2019)
=> [FLOC-1756] Unskip test

admin/acceptance.py
Raises a slightly more informative error message when running the acceptance tests on a non-existent distro.
Makes some assumptions about the layout of `admin`, but they seem consistent with the rest of the assumptions in the code base.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2018)
=> Better error messages for admin/run-acceptance-tests

flocker/__init__.py, flocker/control/test/test_model.py, flocker/node/_change.py, requirements.txt
In theory this version doesn't segfault when the C extension is used... and using the C extension speeds things up a lot. Also this new version has way less bugs, some of them serious.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2022)
=> [FLOC-3192] Switch to newer pyrsistent

docs/_themes/clusterhq/layout_docs.html
Fixes 3228
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2035)
=> [FLOC 3228] lower the number of visible links from the left hand docs menu

flocker/provision/_libcloud.py
Fixes FLOC-3124. On PyPy, sometimes the resulting IP addresses returned from libcloud's rackspace driver (`wait_until_running`) are `unicode` instead of bytes. Our `run_remotely` helper uses a Pyrsistent record type that accepts `bytes`, therefore if the result from libcloud is unicode, encode it to ASCII.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2040)
=> [FLOC-3124] Enforce bytes on public address returned from libcloud

docs/conf.py, docs/gettinginvolved/infrastructure/release-process.rst
Fallback to intersphinx has caused builds that should've broken to pass, so get rid of it.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2049)
=> [FLOC-3226] Get rid of intersphinx so we don't get false positives on doc builds.

admin/acceptance.py, admin/client.py, admin/test/test_acceptance.py, flocker/provision/_common.py, flocker/provision/_install.py, flocker/provision/test/test_common.py
PR #2028 introduces a third location where `os_version` is generated from `version` and then both values are used to create a `PackageSource` object.
This PR makes `os_version` a property of `PackageSource`, allowing it to be generated on demand in one place, rather than by each piece of code that creates a `PackageSource` instance.
The code that uses `os_version` has been modified to call it once, to prevent frequent re-generation of the value.
Note, this changes the two existing locations where `PackageSource` instances are created.  The latter merge of this PR and #2028 should be updated to modify the third `PackageSource` creation.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2041)
=> [FLOC-3233] Make os_version a generated property of PackageSource

admin/client.py, docs/gettinginvolved/client-testing.rst
Interacting with Boot2Docker / Docker-machine on OS X has a few foibles compared to Linux, due to the use of Virtual Machine.  The changes in this PR should fix the client tests for consistent behaviour between platforms.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2047)
=> [FLOC-3044] OS X client test fixes

flocker/provision/__init__.py, flocker/provision/_aws.py, flocker/provision/_common.py, flocker/provision/_libcloud.py
https://clusterhq.atlassian.net/browse/FLOC-3195
This allows us to take advantage of boto retrying calls that fail due to `RequestLimitExceeded`.
In theory, this should reduce the incidents of getting that error, but I don't have data to back that up.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2026)
=> [FLOC-3195] Use boto for provisioning AWS acceptance test nodes.

docs/_themes/clusterhq/layout_docs.html, docs/config/enabling-control-service.rst, docs/index.rst, docs/install/index.rst, docs/install/install-node.rst, docs/introduction/index.rst
Fixes 3132
This PR moves the Flocker demo info (TrueAbility and Vagrant) into a section at the end of "Introduction to Flocker", and rewrites the overview of Installation to talk about the Labs Installer, and a simplified overview of the full install steps.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2033)
=> [FLOC 3132] Update the Installing Overview page

admin/packaging.py, admin/test/test_packaging.py, dev-requirements.txt, docs/control/administering/debugging.rst, requirements.txt
1. Install eliot-tree package.
2. Include eliot-tree and eliot-prettyprint as public binaries installed by the shared Python package so that they are always available.
3. Document how to use journalctl and eliot to extract useful information from Flocker logs.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2043)
=> [FLOC-3173] Document eliot/journald support

flocker/node/_loop.py, flocker/node/test/test_loop.py
Before this the reconnect delay would grow on every reconnect and never go back down.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2044)
=> [FLOC-3185] Reset reconnection delay upon succesful connection

flocker/control/_protocol.py, flocker/control/test/test_protocol.py
https://clusterhq.atlassian.net/browse/FLOC-3256
I think this might be causing a bunch of our intermittent failures.
I'm not sure what the best way to test this is, though.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2053)
=> [FLOC-3256] Fix typo in `_send_state_to_connections`.

flocker/control/__init__.py, flocker/node/__init__.py, flocker/node/_deploy.py, flocker/node/_loop.py, flocker/node/agents/blockdevice.py, flocker/node/agents/test/test_blockdevice.py, flocker/node/functional/test_deploy.py, flocker/node/test/test_deploy.py, flocker/node/test/test_testtools.py, flocker/node/testtools.py
This refactors IDeploy to enable state to go from discover_state to calculate_changes without requiring that the state be transferred to the control service.
It does so by introducing a new interface ILocalState. discover_state is modified to return a provider of this interface. This interface has a shared_state_changes() method that returns the tuple of IClusterStateChanges that discover_state would have returned prior to this PR. The entire opaque ILocalState is also handed to calculate_changes in addition to being used to send updates to the control service.
Implementations of IDeployer can use this to transfer data from discover_state to calculate_changes, and I've added BlockDeviceDeployerLocalState as an example of how the information from api.list_volumes() can be transferred …
=> [FLOC-3234] Refactor IDeploy to enable state transfer from discover_state to calculate_changes.

flocker/node/agents/blockdevice.py, flocker/node/agents/test/test_blockdevice.py
Now that we have the result of list_volumes() being passed from discover_state to calculate_changes, it is possible to use that information to map dataset_ids to blockdevice_ids prior to the construction of the IStateChanges.
This is helpful for the IStateChanges that start out by calling list_volumes just to map from dataset_id to blockdevice_id. This PR adds a blockdevice_id field to all of the IStateChanges that are used in DestroyBlockDeviceDataset, and removes many of the calls to list_volumes in that state change. The goal of this is to reduce over all API calls in the IStateChanges.
During development I added a hacky test to verify that list_volume calls were decreasing, but the test seemed brittle, so I have removed it for merging.
While I was in the code I did a drive by fix to …
=> Reduce API list_volume in DestroyBlockDeviceDataset

docs/introduction/flocker-supports.rst
Fixes 3144
Added a note at the bottom of the list of supported backends to the docs that describe how users can build and contribute new storage backends.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2069)
=> [FLOC 3144] Link from list of backends to contributing

docs/introduction/flocker-plugin.rst
Fixes 3191
Added a short section at the end of the Introduction/Flocker Plugin for Docker doc, which links forward to the installation steps.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2068)
=> [FLOC 3191] Add link to install from Plugin introduction

docs/install/installer.rst, docs/introduction/what-is-flocker.rst, docs/labs/compose.rst, docs/labs/index.rst, docs/labs/installer.rst, docs/labs/swarm.rst, docs/labs/volumes-cli.rst, docs/labs/weave.rst, docs/releasenotes/index.rst
Fixes 3198
The Flocker plugin for Docker was named Flocker Docker plugin when it was part of Labs. Now that this is supported, the rest of the docs should use the new name.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2067)
=> [FLOC 3198] Use correct name for the plugin

flocker/node/agents/blockdevice.py, flocker/node/agents/test/test_blockdevice.py
With this PR these IStateChanges are constructed with blockdevice_ids. This means that they do not have to do the dataset_id -> blockdevice_id mapping as part of their execution. This enables the removal of list_volumes() calls at the beginning of the execution of either of them.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2065)
=> Reduce API list_volume when Attaching and Mounting Volumes

flocker/node/agents/blockdevice.py, flocker/node/agents/test/test_blockdevice.py
Introduce a new interface for drivers that are capable of creating profiles.
In the long term drivers can choose to provide IProfiledBlockDeviceAPI, and if they do, then flocker will call create_volume_with_profile if the user attempts to create a volume with a specified storage profile over the control API.
I suppose this might be arguably more of a design review disguised as a tiny code review.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2066)
=> [FLOC-3270] Add a new interface for IBlockDeviceAPIs with storage profiles.

flocker/provision/_aws.py
https://clusterhq.atlassian.net/browse/FLOC-3260?jql=text%20~%20%22update%20centos%22
Both CentOS and Ubuntu have newer cloud images in AWS. Since we install all updates anyway, upgrade the base image to reduce the updates we need to install.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2072)
=> [FLOC-3260] Update AWS base images.

admin/acceptance.py, flocker/node/agents/cinder.py, flocker/node/agents/functional/test_cinder.py
Based on @jongiddy's comments in #1922. 
I've implemented most of his suggestions, but chickened out on re-using the minimum device sizes. It looks like the code is a great big tangle there (see [FLOC-2584](https://clusterhq.atlassian.net/browse/FLOC-2584)), and although I *do* think it's a good idea to disentangle it, I personally don't want to do it right now.
I pulled the comment on the symlink resolution from @wallrj's [insights on the original PR](https://github.com/ClusterHQ/flocker/pull/1921).
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2025)
=> [FLOC-3046] Cleanups for virtio stuff

flocker/node/agents/blockdevice.py, flocker/node/agents/cinder.py, flocker/node/agents/ebs.py, flocker/node/agents/functional/test_cinder.py, flocker/node/agents/test/test_blockdevice.py, setup.py
In some circumstances, `compute_instance_id` can return `None`. This is not a valid response according to the documentation, and most of our code base assumes that `compute_instance_id` returns a valid instance ID.
Thus, rather than returning `None`, we here raise an error.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2024)
=> [FLOC-3203] Raise error if we can't compute instance ID

flocker/acceptance/testtools.py
https://clusterhq.atlassian.net/browse/FLOC-3259
Make cleaning up nodes before a test into a tree of actions, so it is easier to identify the stuff that comes after.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2073)
=> [FLOC-3259] Log cleanup_nodes in acceptance tests.

docs/releasenotes/index.rst, flocker/acceptance/endtoend/test_dockerplugin.py, flocker/dockerplugin/_api.py, flocker/dockerplugin/test/test_api.py
Fixes FLOC-2819. Looking at https://github.com/docker/docker/blob/master/docs/extend/plugins_volume.md versus https://docs.docker.com/extend/plugins_volume/ it seems that the only difference in how the plugin API needs to work is that `/VolumeDriver.Create` now takes an `Opts` mapping of custom options passed through from Docker, e.g. as a result of `docker volume create --driver flocker --opt foo=bar --opt maxsize=10G`
It is unclear whether this `Opts` map is optional or not, I am inclined to suspect Docker will make the POST request to our plugin with `Opts` as an empty mapping `{}` if no `opt` flags were specified through the CLI/API on Docker's end - we also want compatibility with our existing previous Docker versions, so this design makes `Opts` on our endpoint optional with a …
=> [FLOC-2819] Docker 1.9 plugin compatibility

flocker/node/_docker.py, flocker/node/functional/test_docker.py, flocker/test/test_testtools.py, flocker/testtools/__init__.py
Our centos-7 tests often fail with `docker.errors.APIError: 500: Internal Server Error: Unknown device`
This is *probably* due to a race condition in Docker. See [FLOC-3077](https://clusterhq.atlassian.net/browse/FLOC-3077) for discussion. 
The work-around is to retry the list operation in the test in order to avoid the race condition. 
Rather than putting all of that logic in the test, I added a new `retry_failure` helper which does this. I considered trying to shoe-horn `loop_until` to fit this purpose, but it seemed cleaner to do it this way.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2076)
=> [FLOC-3077] Retry `list` in client tests to avoid spurious failures

jobs.groovy.j2
https://clusterhq.atlassian.net/browse/FLOC-3282
Part of enabling parity with the BB setup, this PR will enable automatic builds for the master branch only, which are built every time a commit is pushed to that branch.
http://ci-live.clusterhq.com:8080/job/ClusterHQ-flocker/job/flocker-enable-master-builds-on-jenkins-FLOC-3282/job/__main_multijob/2/
=> enable jenkins builds on git push for the master branch - FLOC-3282

docs/gettinginvolved/infrastructure/release-schedule-versioning.rst
Updating the "Version Numbers" section. Updates the section to not include 0 for ``X`` since we passed ``0.Y.Z``
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2090)
=> [FLOC-3332] Update release-schedule-versioning.rst

docs/concepts/clustering.rst, docs/install/install-node.rst, docs/install/setup-aws.rst, docs/tutorials_examples/tutorial/vagrant-setup.rst
Fixes 647
An old issue, but was updated due to ongoing work on creating a style guide for documentation. 
Note - there is no current use of "Mb" in the docs
=> [FLOC 647] Standardise space - no space before units

flocker/acceptance/test/__init__.py, flocker/acceptance/test/test_testtools.py, flocker/acceptance/testtools.py
Applies almost all of the suggestions from #2052 and [FLOC-3248](https://clusterhq.atlassian.net/browse/FLOC-3248)
* uses `wire_encode` instead of `json.dumps`
* catches `ValueError`, which can be raised on circular references and also invalid dates
* checks `args` for serializability as well as kwargs
Does this by extracting an `_ensure_encodeable` function, which in turn allows for a more functional implementation within `log_method`.
Did not implement the "force all arguments to be keyword arguments" suggestion. That can be done as a separate clean-up ticket, outside of the Green CI epic.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2077)
=> [FLOC-3248] Encode args as well as kwargs 

flocker/node/_loop.py, flocker/node/test/test_loop.py
The convergence loop needs to be improved such that sleeps in between iterations can be modified (different durations, for exampe) and interrupted (e.g. config updates should perhaps interrupt sleep). A preliminary step is making sleep an explicit state machine step.
http://build.clusterhq.com/boxes-flocker?branch=explicit-convergence-loop-sleep-state-FLOC-3310
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2081)
=> [FLOC-3310] Switch to explicit SLEEPING state in convergence loop

flocker/acceptance/obsolete/test_containers.py, flocker/acceptance/scripts/exitinghttp.py, flocker/acceptance/testtools.py
Fixes: https://clusterhq.atlassian.net/browse/FLOC-3308
Observed several times that one of the polling iterations would get stuck for two minutes trying to query what should have been the second run of the container.  Filed an issue for whatever networking problem *that* represents... And updated this branch to use short timeouts where we do a polling loop that might get hit by this.
=> [FLOC-3308] Attempt to fix intermittent test failure

docs/labs/compose.rst, docs/labs/index.rst, docs/labs/installer.rst, docs/labs/swarm.rst, docs/labs/volumes-gui.rst
Fixes 3338
Quick fix to consistently use title case in all documentation headers (as per the WIP Doc style guide: https://docs.google.com/spreadsheets/d/11E38SvKX7ujJ95qs7rvzgh3vIVmPyiTOSsvjR8KWMoY/edit#gid=0)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2093)
=> [Floc 3338] Use title case in Labs docs

admin/acceptance.py, flocker/acceptance/endtoend/test_dataset.py, flocker/acceptance/testtools.py, flocker/ca/_ca.py, flocker/ca/test/test_ca.py, flocker/provision/_common.py
This is the codified acceptance test for Flocker storage profiles basic support on EBS
It verifies that if a volume is created with the specific metadata that forces a profile for the volume, then the volume that is created has the correct EBS type for the given profile.
In the interest of keeping the acceptance tests lean, I've only added a test for gold rather than also testing for silver and bronze. I'm open to feedback on that decision. I figured this was enough to show the plumbing was there even if we aren't exhaustively testing every length of pipe at this level.
In order to validate the volume's performance characteristics from the acceptance test, this adds a backdoor to get the backend configuration from the process that sets up the acceptance test rig.  It then uses those …
=> [FLOC-3271] Acceptance test for Flocker for storage profiles.

flocker/node/agents/blockdevice.py, flocker/testtools/__init__.py
It's unused & untested. Why keep it?
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2097)
=> Remove unused `skip_except`

docs/introduction/flocker-supports.rst
Fixes 2443
Added info to the list of storage backends in the introduction, which points to the table in our marketing website, so that the user has some more information about their backend options.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2102)
=> [FLOC 2443] Add an introduction to choosing a backend

flocker/acceptance/endtoend/test_dataset.py, flocker/acceptance/endtoend/test_dockerplugin.py, flocker/acceptance/integration/test_postgres.py, flocker/acceptance/obsolete/test_cli.py, flocker/acceptance/obsolete/test_containers.py, flocker/acceptance/testtools.py, flocker/common/_retry.py, flocker/common/functional/test_script.py, flocker/common/test/test_retry.py, flocker/node/functional/test_deploy.py, flocker/node/functional/test_docker.py, flocker/node/testtools.py, flocker/provision/_ssh/_conch.py
**This PR depends on FLOC-3340 (#2095)**
One of the review comments in FLOC-3340 (#2095) was that it's unsafe to have a reactor parameter that defaults to the global reactor. 
This patch addresses that concern by:
1. making `reactor` a non-optional parameter
2. making it the _first_ parameter of `loop_until` and `retry_failure`
3. updating all call sites to pass `reactor` explicitly
As a general principle, I've tried to only pass a concrete reactor in at the leafs. Thus, I've updated `flocker.provision._ssh._conch` to pass `reactor` through from its entry point, `make_dispatcher`, and also `flocker.node.testtools.wait_for_unit_state` to take a reactor.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker …
=> [FLOC-3343] No default reactor in retry helpers

flocker/node/__init__.py, flocker/node/_change.py, flocker/node/_deploy.py, flocker/node/_loop.py, flocker/node/agents/test/test_blockdevice.py, flocker/node/test/test_change.py, flocker/node/test/test_deploy.py, flocker/node/test/test_loop.py
https://clusterhq.atlassian.net/browse/FLOC-3318
http://build.clusterhq.com/boxes-flocker?branch=wakeup-loop-if-changes-matter-FLOC-3318
1. Update sequentially/in_parallel so they indicate a no-op if they're not going to take any action.
2. Whenever the convergence loop receives an update from the control service while sleeping, it calculates what changes need to be made given that update, without doing any local discovery. If the result is not a no-op this means we should wake up, since the update apparently required some action on our part. Since `calculate_changes` is supposed to be purely in-memory operation this additional check should have limited no impact on system load, e.g. no cloud API calls involved.
3. Demonstrate that individual deployers return `NoOp` when no changes are …
=> [FLOC-3318] Wakeup convergence loop if changes matter

docs/tutorials_examples/tutorial/exposing-ports.rst
Fixes FLOC 431
This is a really old issue, and I couldn't find the exact codeblock that the issue refers to. It did highlight a syntax error in one codeblock though, which this PR corrects.
I've not manually run through the tutorial following this change, as the correction was obviously a syntax error.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2105)
=> [FLOC 431] remove $ from codeblock in tutorial

README.rst
Fixes 3350
The links in the readme directly to the docs have been removed in favour of a direct link to the docs - this ensures that this problem shouldn't occur again due to changing/new URLs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2108)
=> [FLOC 3350] fix broken links in README

docs/tutorials_examples/examples/linking.rst
Fixes 977
An old issue which adds a downloadable elk file where the text suggests one should be. A few tweaks to the wording around this.
I've not manually tested this, as it was an obvious error (the contents of the elk file was always provided - this just adds a link for users to download the file)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2106)
=> [FLOC 977] add elk download file

flocker/node/agents/blockdevice.py, flocker/node/agents/test/test_blockdevice.py
This PR modifies the Node agent on create requests.
After this PR, if the dataset being created has a metadata key "clusterhq:flocker:profile" and the backend supports creating volumes with a profile, then the value of that metadata will be handed down as the profile for the volume.
If that metadata entry exists but the backend does not support creating volumes with profiles, the agent will log that the profile was dropped, and will simply call create_volume on the backend without passing the profile down.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2103)
=> FLOC-3273 Modify the Node agent to plumb flocker profiles to the driver.

flocker/common/_retry.py, flocker/common/test/test_retry.py, flocker/node/_docker.py, flocker/node/agents/cinder.py
Container removal fails intermittently with a 500 error. To make this more reliable, any 500 error will be logged and the removal will be repeated. If the removal can be fixed simply by retrying, this will make the code more robust. If retries do not help, at least we have more logging info.
The container stopping and removal both run synchronously in a separate thread, so the `poll_until` function (synchronous version of `loop_until`) is modified to take a `steps` iterable for retry intervals (matching recent changes to `loop_until`).
Tests for `poll_until` are added, and to support the testing, the `sleep` function used in `poll_until` can be set to ensure tests do not take too much time.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on …
=> [FLOC-3262] Loop to destroy container

docs/install/docker-plugin.rst
Fixes 3359
Added info (with a link back to the FPD introduction page) to the Installing the plugin docs, so that the user is aware of what the plugin does.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2117)
=> [FLOC 3359] Extra info for Installing plugin doc

docs/config/index.rst
Fixes 3360
Makes the wording clearer for users to understand that they must have installed Flocker before the config steps
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2118)
=> [FLOC 3360] Reword the introduction to Configuring Flocker

build.yaml, jobs.groovy.j2
This PR adds a new Jenkins Job for the missing flake8 lint checks.
It simply runs tox -e lint just like the BB builder
Jenkins job:
http://ci-live.clusterhq.com:8080/job/ClusterHQ-flocker/job/add_lint_FLOC-2858/job/run_lint/7/console
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2110)
=> Adds lint flake8 checks jenkins job FLOC-2858

build.yaml
This PR fixes the issue where the run_sphinx job was failling.
http://ci-live.clusterhq.com:8080/job/ClusterHQ-flocker/job/master/job/run_sphinx/
And enables the uploads of the resulting html files to an S3 bucket on AWS.
http://ci-live.clusterhq.com:8080/job/ClusterHQ-flocker/job/jenkins-docs-FLOC-2857/job/run_sphinx/8/console
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2115)
=> Fixes Jenkins run_sphinx job (docs) -  FLOC-2857

docs/config/generate-api-certificates.rst
Fixes 3361
Added an introduction, which clearly states that the API user certificates is mandatory, regardless of how you intend to communicate with the control service - please could someone in the know about this confirm this.
Many thanks
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2116)
=> [FLOC 3361] add introduction to Generating API Certs doc

docs/control/administering/debugging.rst, docs/control/cli/application-config.rst, docs/tutorials_examples/examples/linking.rst, docs/tutorials_examples/tutorial/tutorial-requirements.rst
Fixes 3371
Note - the link to Docker Container Linking in the ElasticSearch/LogStash/Kilbana example has been removed, as Docker no longer publishes this page.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2125)
=> [FLOC 3371] Fix broken links in doc link checker

docs/config/enabling-control-service.rst
Fixes 3362
Adds an explanation of why you need to enable the control service.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2119)
=> [FLOC 3362] add context to Enabling control service doc

docs/config/enabling-agent-service.rst
Fixes 3363
Adds an explanation of why you need to enable the agent service.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2120)
=> [FLOC 3363] add context to Enabling agent service doc

jobs.groovy.j2, vagrant/tutorial/Vagrantfile, vagrant/tutorial/bootstrap.py
https://clusterhq.atlassian.net/browse/FLOC-3365
This PR fixes multiple issues with the builds of the vagrant basebox tutorial on Jenkins.
* updates the job definitions so that the branch that is built is the correct branch and not master
* Adds a chunk of code to the Vagrantfile allowing it to build the VB guest modules when the kernel is updated from upstream.
* Removes the step where vboxadd is executed as the VBguest modules are handled  by vagrant-vgbuest
Jenkins build:
http://ci-live.clusterhq.com:8080/job/ClusterHQ-flocker/job/flocker-fix-vagrant-basebox-FLOC-3365/job/_build_vagrant_basebox_for_flocker_tutorial/10/console
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2123)
=> Fixes Jenkins Builds of the vagrant basebox for flocker -  FLOC-3365

build.yaml
oneliner,
it increases the timeout from 60min to 120min for the nightly cron job that refreshes the OSX vagrant basebox for OSX run client tests
=> Increase timeout for OSX builds of the vagrant OSX box FLOC-3373

README.rst
Fixes 3390.
This link has been broken in a recent PR, when the tutorial URL was removed. Due to additional installation and configuration options, it might not be the best practice for a user to jump directly to the Mongo tutorial.
I think this sentence can now be removed.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2136)
=> [FLOC 3390] Remove broken link from README

README.rst
Fixes 3393
This issue simply removes the link (and rewords the sentence) relating to feedback via UserVoice, as this will no longer be supported.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2138)
=> [FLOC 3393] remove UserVoice link from README

CONTRIBUTING.rst
Fixes 3394
This issue simply removes the link (and rewords the sentence) relating to feedback via UserVoice, as this will no longer be supported.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2139)
=> [FLOC 3393] remove UserVoice link from CONTRIBUTING.rst

flocker/node/_change.py, flocker/node/agents/test/test_blockdevice.py, flocker/node/functional/test_deploy.py, flocker/node/test/test_change.py
1. Added explicit eliot actions for in-parallel and sequential runs.
2. Minorly refactored the code to be more object-oriented.
3. Fixed the bug which is the point of the exercise: sub-statechanges of `sequentially` are now run in correct Eliot context so it's possible to see them in appropriate place when reading logs.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2126)
=> [FLOC-3357] sequentially() and in_parallel() now have eliot actions

flocker/acceptance/endtoend/test_dataset.py, flocker/acceptance/endtoend/test_dockerplugin.py, flocker/acceptance/testtools.py, flocker/dockerplugin/_api.py, flocker/node/agents/blockdevice.py, flocker/node/script.py, requirements.txt
This also completes FLOC-3274.
With this PR, the Flocker plugin for Docker can now accept a "profile" option if it is being used with docker version 1.9.0+. The added test verifies that if the 'silver' profile is chosen with the create_volume request using the EBS backend, we get the expected volume type for EBS u'silver' profile.
Unfortunately docker-py 1.5.0 does not have full support for create_volume (it is merged at head), so there is some odd code that explicitly uses internals to that library to construct the correct request to docker.
Also this turns on the acceptance test, which revealed that the proxy BlockDeviceAPI was hiding the fact that the EBS driver implemented IProfiledBlockDeviceAPI, so that is fixed as well.
[<img src="https://reviewable.io/review_button.png" height=40 …
=> [FLOC-3272] Flongle profiles + acceptance test

docs/install/setup-aws.rst
Fixes 3251
Adds a step to our instructions on how to create nodes using AWS. Previously we did not mention there is a step on choosing an existing key pair or create a new one.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2144)
=> [FLOC 3251] add key pair step to AWS instructions

build.yaml
https://clusterhq.atlassian.net/browse/FLOC-3405
A number of tests are missing from Jenkins, these were created after
we took the initial snapshot of jobs running on BuildBot.
This PR adds those missing tests.
jenkins builds running here:
http://ci-live.clusterhq.com:8080/job/ClusterHQ-flocker/job/add_missing_tests_to_jenkins_FLOC-3405/
=> added missing tests to run on jenkins - FLOC-3405

docs/install/setup-aws.rst
Fixes 3250
We discovered that the AMI links we provided were CentOS 7 examples, which were correct, but not the typical process of creating instances on EC2.
This change directs users to the EC2 page they'd expect, and moves the CentOS 7 instructions into a note, highlighting that this is slightly different to what they'd might expect.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2146)
=> [FLOC 3250] Make the AMI step of AWS instructions clearer

docs/install/install-client.rst
Fixes 3218
Adds details to the CLI install instructions that the Ubuntu supported platforms must be 64-bit.
Users of Ubuntu 32-bit are directed to use our "Other Linux Distributions" instructions.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2153)
=> [FLOC 3218] Specify 64-bit Ubuntu platform in CLI install instructions

flocker/control/__init__.py, flocker/control/_clusterstate.py, flocker/control/_model.py, flocker/control/_protocol.py, flocker/control/test/test_clusterstate.py, flocker/control/test/test_model.py, flocker/control/test/test_protocol.py, flocker/node/_loop.py, flocker/node/script.py, flocker/node/test/test_loop.py, flocker/node/test/test_script.py, flocker/testtools/amp.py
1. The control service now handles node era update.
2. Sending of node era updates was moved elsewhere so we can easily get at the node UUID.
For full plan see https://clusterhq.atlassian.net/browse/FLOC-3261
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2141)
=> [FLOC-3379] Control service learns about eras

docs/_themes/clusterhq/layout_docs.html, docs/_themes/clusterhq/static/css/docs.css, docs/_themes/clusterhq/static/js/feedback.js
The form works the same way as the ones on the marketing website do.
When a user submits a form it sends an HTTP request with Javascript to Formstack. We have a formstack form made for documentation feedback and the fields are the IDs defined in the html file.
If the user doesn't have Javascript, the form will just post as normal.
Once the entry is at Formstack, Zapier detects this and creates a new Zendesk ticket.
Fixes FLOC-3391
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2137)
=> [FLOC-3391] Docs feedback

docs/reference/api_examples.yml, flocker/apiclient/_client.py, flocker/apiclient/test/test_client.py, flocker/control/__init__.py, flocker/control/_clusterstate.py, flocker/control/_model.py, flocker/control/_protocol.py, flocker/control/httpapi.py, flocker/control/schema/endpoints.yml, flocker/control/test/test_httpapi.py, flocker/control/test/test_model.py, flocker/control/test/test_protocol.py, flocker/control/test/test_schemas.py, flocker/node/_loop.py, flocker/node/script.py, flocker/node/test/test_loop.py, flocker/node/test/test_script.py, flocker/testtools/amp.py
This builds on #2141 which will hopefully be merged soon.
This adds a REST API for looking up nodes by era. The idea is that this is the new mechanism for figuring out "which node is this", and since eras are reboot-specific it's a mechanism that ensures clients of the REST API don't get stale node state.
For example, in the next stacked branch the Docker plugin will be changed to use this new API to discover its node identity, instead of extracting it from the node TLS certificate. This will mean the Docker plugin won't ever get stale pre-reboot state, since it won't be able to lookup node identity until an agent has updated the control service post-reboot.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on …
=> [FLOC-3381] Allow looking up node identity by era

flocker/acceptance/endtoend/test_dockerplugin.py, flocker/acceptance/endtoend/test_leases.py, flocker/node/_docker.py
Fixes FLOC-3421
https://clusterhq.atlassian.net/browse/FLOC-3421
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2156)
=> [FLOC-3421] Replace deprecated create_host_config with client method

docs/releasenotes/index.rst
Release flocker 1.7.0 with profiles support.
The test run at http://build.clusterhq.com/boxes-flocker?branch=release%2Fflocker-1.7.0 was not originally all green, specifically `flocker/unit-test/centos-7/zfs-head` was red for a few runs. See https://clusterhq.atlassian.net/browse/FLOC-3395 for discussions on why proceeding anyway, the summary is that the flakes occurred in test code and docker and thus are thought to not be indicative of any failures with core flocker code.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2159)
=> [FLOC-3395] Release flocker 1.7.0

flocker/acceptance/endtoend/test_dataset.py, flocker/acceptance/endtoend/test_dockerplugin.py, flocker/acceptance/obsolete/test_containers.py, flocker/node/agents/functional/test_cinder.py, flocker/node/agents/functional/test_ebs.py, flocker/node/functional/test_deploy.py, flocker/node/functional/test_docker.py, flocker/test/test_testtools.py, flocker/testtools/__init__.py, flocker/testtools/_flaky.py, flocker/testtools/test/test_flaky.py, flocker/volume/functional/test_service.py
Part of the work to add a `@flaky` decorator to flocker.
This patch adds a decorator that does absolutely nothing, and then applies that decorator to all of the tests for which we have bugs saying they are flaky.
It has been a worthwhile exercise in that it has taught me about which tests are actually flaky (I already had a sense of it, but it's surprisingly clear once you look at what actually needs to _import_ `flaky`), and also because it has made the uses for the `@flaky` decorator more clear (see `XXX` notes in the diff).
I think having these markers in the code will help people with debugging (esp. @Azulinho with the Jenkins migration), so even though there's no behavioural change, I think there's enough added value to land.
[<img src="https://reviewable.io/review_button.png" …
=> [FLOC-3414] No-op @flaky decorator

docs/config/configuring-nodes-storage.rst
Fixes 3425
Adds a dataset example to the yaml file provided in the configuring nodes document, so the user is aware that this is a requirement.
The wording around the example has been slightly ordered, including making the warnings about choosing localhost as the hostname more prominent.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2160)
=> [FLOC 3425] Add extra content to the example yaml file in configuring nodes doc

flocker/control/_protocol.py
Fix issue that caused AMP connections to disconnect immediately upon connecting.
IMPORTANT: To verify the fix we need to check lack of error and logs and CPU usage that is not 100%; green tests do not indicate this is fixed.
`master` does not have this issue since the stub code has been filled in.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2168)
=> [FLOC-3445] Prevent 100% CPU from disconnect/reconnect AMP clients cycle

docs/releasenotes/index.rst
Merge to get the release notes and the tag back into master. Merge resolved in favor of master so the release branch only patch is effectively removed from this merge.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2170)
=> [FLOC-3448] Merge release 1.7.1 back into master

docs/releasenotes/index.rst
Single patch on top of 1.7.0 to prevent breakage of AMP protocol.
Apart from the usual change to the release notes, this PR also provides a quick fix to the AMP protocol.  This fix conflicts with the real fix in `master`. When this PR is merged, the conflict will be resolved in favour of the `master` code.
I expect to do this by tagging the release, then creating a new branch `1.7.1-merge` from `1.7.1` to be merged into `master`. Before merging into `master`, this new branch will have `master` merged in and the conflict resolved. [EDIT - latest release notes actually describe what to do in this case]
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2169)
=> [FLOC-3448] Release Flocker 1.7.1

dev-requirements.txt, flocker/testtools/test/test_base.py
We were using a private API for testtools. Now we're not.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2174)
=> [FLOC-3450] Bump testtools to 1.8.1

flocker/node/agents/blockdevice.py, flocker/node/agents/test/test_blockdevice.py
As preliminary to breaking up creation into atomic steps, and also to recover from failures mid-way through creation, create a filesystem on an attached block device if it is missing one. Previously we would try to mount it, fail, repeat forever.
http://build.clusterhq.com/boxes-flocker?branch=repair-missing-filesystem-FLOC-1576
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2157)
=> [FLOC-1576] Repair missing filesystems

docs/releasenotes/index.rst
Release adds doc changes from `master` that do not have any related changes in code.  In particular, this was done to fix FLOC-3420, which was being reported by users.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2186)
=> [FLOC-3456] Release Flocker 1.7.2

flocker/node/_loop.py, flocker/node/agents/blockdevice.py, flocker/node/agents/test/test_blockdevice.py, flocker/node/test/test_loop.py, flocker/node/testtools.py
calculate_changes() is sometimes called with cached local state to decide if the sleeping converence loop should wake up.
1. If it throws an exception (indicating a bug) then wake up; better to be responsive than to sleep when there is work to be done.
2. Fix a case where it threw an exception due to using cached local state that was missing information
The latter case was happening in acceptance tests and may have been causing timeouts since the loop would not wake up.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2185)
=> [FLOC-3447] Calculate changes for wakeups

docs/_themes/clusterhq/static/css/docs.css
Fixes 3419
In bulleted lists, nested in a numbered list, the padding at the bottom of the last bullet was missing padding. This PR adds 10px to the bottom of the list, but limits this change so as not to impact the toctree listings used throughout the docs.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2183)
=> [FLOC 3419] add a margin to the bottom of lists, except if it is part of the toctree

docs/gettinginvolved/plugins/building-driver.rst
Fixes 3449
The example code on the contributing a backend guide (getting involved section) uses the `make_istatechange_tests` call for generating the list of functional tests for the backend.
This should have used `make_iblockdeviceapi_tests`. This change amends this.
Note: This is a duplicate of https://github.com/ClusterHQ/flocker/pull/2172
=> [FLOC 3449] change import call on backend contribution doc

docs/gettinginvolved/infrastructure/release-process.rst
Fixes 2239
The wording on step 2 of the release process doc was confusing. This PR changes this to be more specific.
It also cleans up some irregular use of headings and bullets, which made the .rst document difficult to read.
=> [FLOC 2239] Clarify note in release process doc

docs/gettinginvolved/infrastructure/release-process.rst
Fixes 2236
The Pre-tag review section of the release docs simply said that not deleting tags pushed to GitHub was a policy. This PR adds an explanation of why we don't do that.
=> [FLOC 2236] Add extra info to pre-tag introduction

docs/gettinginvolved/acceptance-testing.rst, docs/gettinginvolved/functional-testing.rst, docs/gettinginvolved/index.rst
Fixes 2824
We had some strange header tags being used in Acceptance testing doc - This has been corrected, and the Functional Testing content has been moved to its own page (it previously was embedded in the Acceptance test page, but the use of headers was inconsistent)
=> [FLOC 2824] Correct irregular title fonts in Acceptance/Functional test docs

docs/tutorials_examples/tutorial/vagrant-setup.rst
Fixes 2128
The Using Vagrant to Create Virtual Machines tutorial provides no details about installing the products. This PR adds an installation section with links to Vagrant and VirtualBox docs, but also adds a useful example for OS X users of installing using `brew cask`
=> [FLOC 2128] Add installing Vagrant/VirtualBox step to tutorial

docs/_themes/clusterhq/layout_docs.html
Fixes 2390
The docs pages have been missing the favicon that is present for the rest of the website. This adds it.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/flocker/2182)
=> [FLOC 2390] add favicon to docs

dev-requirements.txt, flocker/acceptance/endtoend/test_dataset.py, flocker/acceptance/endtoend/test_dockerplugin.py, flocker/acceptance/obsolete/test_containers.py, flocker/node/agents/functional/test_cinder.py, flocker/node/agents/functional/test_ebs.py, flocker/node/functional/test_deploy.py, flocker/node/functional/test_docker.py, flocker/testtools/_base.py, flocker/testtools/_flaky.py, flocker/testtools/_testhelpers.py, flocker/testtools/test/test_base.py, flocker/testtools/test/test_flaky.py, flocker/volume/functional/test_service.py
This branch adds support for retrying flaky tests.
It adds thing that wraps an arbitrary `RunTest` object with something that retries tests until they pass a minimum number of times, and updates our `async_runner` to use that, which means that any test case which inherits from `AsyncTestCase` and has a `@flaky` decorator will automatically retry.
The implementation approach means that it should also work for synchronous test cases, once we switch those over to testtools.
An earlier version of this branch used the [flaky](https://github.com/box/flaky) library. Unfortunately, there is very little that it provides which is useful to us.
You might notice the `_run_prepared_result` call. This is an infelicity in testtools, which uses underscore prefixes for both private and "protected" …
=> [FLOC-3443] Retry tests marked as flaky 

docs/config/enabling-agent-service.rst
Fixes 3488
The `flocker-container-agent` service must have Docker running before it is enabled (there is currently a bug on Ubuntu that forces a hang if Docker is not running - see FLOC 3490)
This PR adds a note to the Configuring the Agent Services page so the user is aware that they should have Docker running at this point in configuring Flocker.
=> [FLOC 3488] Add a note to agent service doc about Docker running

docs/control/administering/debugging.rst
Fixes 1877
Ubuntu logs are in the var/log/flocker directory. This PR adds this location to the debugging page.
There was some inconsistent titles, so this was cleaned up also.
FLOC-1936 will add more information about requiring the user to be root in order to view logs, so this PR simply adds the location.
=> [FLOC 1877] add the Ubuntu log directory

docs/control/administering/debugging.rst
Fixes 1936
The code blocks in the debugging page specify root access on nodes, but this PR adds a sentence in the introduction so users do not miss this.
=> [FLOC 1936] Root access required for viewing logs

flocker/testtools/_base.py, flocker/testtools/_flaky.py, flocker/testtools/test/test_base.py
testing-cabal/testtools#165 is the real solution, but it's going to take longer because it's being held to higher testing standards, and because we'd have to wait for a release before we could use it.
In the meantime, this patch re-enables `trial -u` support.
=> [FLOC-3496] Hacky solution to re-enable `trial -u` for acceptance tests

flocker/provision/_install.py, flocker/provision/_ssh/__init__.py, flocker/provision/_ssh/_model.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-2984
This adds retry-on-failure to most package interactions in the installation code used by the acceptance test runner.  This should fix the failure case described in the issue as well as various other hypothetical cases which could arise from other network-dependency package manager interactions.
There are still some non-retrying package manager uses but they follow a different pattern so require a slightly different change.
http://build.clusterhq.com/boxes-flocker?branch=retry-apt-get-update-FLOC-2984
=> [FLOC-2984] Retry many package management operations

docs/config/zfs-configuration.rst
Fixes 2670
This change was requested by a user, and @lukemarsden provided and checked the wording with the requestor. I've re-worded slightly, but not tested this docs addition to the ZFS Peer-to-Peer Backend Configuration documentation. 
Please note that a sentence above the new addition remains:
> You must also set up SSH keys at :file:`/etc/flocker/id_rsa_flocker` which will allow each Flocker dataset agent node to authenticate to all other Flocker dataset agent nodes as root.
Please advise if this needs sentence needs to change, or be amended/removed.
=> [FLOC 2670] Document "Enable root login between nodes for ZFS data transfer" 

benchmark/_driver.py, benchmark/operations/__init__.py, benchmark/operations/no_op.py, benchmark/operations/read_request.py, benchmark/operations/test/test_wait.py, benchmark/operations/wait.py, benchmark/script.py, benchmark/test/test_operations.py, docs/gettinginvolved/benchmarking.rst
Add an operation to benchmarks to wait for 10 seconds between measurements.
This allows us to take better measurements for idle cluster conditions.  CPU time, for example, has a resolution of 1 second, so we need to run for 10 seconds just to get the nearest 10% of CPU load for each process.
This is probably a precursor to running operations repeatedly for a period of time, in order to ensure measurements are useful in general.
To test with a Flocker cluster, run:
```
$ benchmark/benchmark --control=${FLOCKER_ACCEPTANCE_CONTROL_NODE} --certs=${FLOCKER_ACCEPTANCE_API_CERTIFICATES_PATH} --operation wait-10
```
This uses the wallclock time metric and shows that each sample runs for at least (and very close to) 10 seconds.
To test the CPU time metric:
```bash
$ git merge …
```
=> [FLOC-3504] Benchmark wait operation

benchmark/_driver.py, benchmark/operations/no_op.py, benchmark/operations/read_request.py, benchmark/test/test_operations.py
To add an operation that waits 10 seconds, we need to access a Twisted `IReactorTime`. Pass the reactor as an explicit parameter to operations.
This copies the situation for benchmark scenarios and metrics, which get both the clock and the Flocker client.
=> [FLOC-3512] Add reactor to benchmark operations constructor

flocker/node/agents/blockdevice.py, flocker/node/agents/test/test_blockdevice.py
We have a list of volumes that we think exist. Rather than checking to see if anybody reported that a dataset with a given id exists, just check if there is a volume that exists, before deciding to create a volume.
=> FLOC-3487] Dont create volumes found to exist.

build.yaml, jobs.groovy.j2
https://clusterhq.atlassian.net/browse/FLOC-3531
The changes introduced by the flaky decorator increased the overal time of the acceptance tests as they retry failed steps.
Jenkins was configured to abort any jobs that took longer than 30minutes, as we assumed those jobs to be stuck.
Now as the jobs take longer due to @flaky, normal running tests were being aborted by jenkins as they exceeded the 30 minutes window.
The initial goal of FLOC-3531 was to introduce an elastic timeout, where Jenkins would abort builds based on the average time taken over the last 'n' builds. 
This data is however related to a single job, and we configure different jobs for each branch. 
This means that any new PR branch being tested doesn't contain any valid data from previous builds.
We could still configure …
=> Update timeout logic to work with new flaky retries FLOC-3531

dev-requirements.txt, flocker/node/agents/functional/logging.py, flocker/node/agents/functional/test_cinder.py, flocker/node/agents/functional/test_cinder_behaviour.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-3530
This will let us compare logs and volumes that got leaked into the cloud and see how often these tests are the culprit.
http://build.clusterhq.com/boxes-flocker?branch=log-cinder-volume-id-FLOC-3530
=> [FLOC-3530] Log the Cinder volume id in some of the Cinder functional tests

flocker/node/agents/functional/test_cinder.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-3544
Skips the tests that depend on virsh before they make a bunch of OpenStack API calls.
http://build.clusterhq.com/boxes-flocker?branch=skip-cinder-functional-tests-faster-FLOC-3544
=> [FLOC-3544] Skip virsh-requiring cinder functional tests faster

build.yaml
This changes adds support for testing the `benchmark` module on Jenkins. This change results in two `run_trial_*` jobs which can now be seen on Jenkins: [CentOS 7](http://ci-live.clusterhq.com:8080/job/ClusterHQ-flocker/job/test-benchmark-on-jenkins-FLOC-3503/job/run_trial_on_AWS_CentOS_7_benchmark/) and [Ubuntu Trusty](http://ci-live.clusterhq.com:8080/job/ClusterHQ-flocker/job/test-benchmark-on-jenkins-FLOC-3503/job/run_trial_on_AWS_Ubuntu_Trusty_benchmark/).
=> [FLOC-3503] Test benchmark directory on Jenkins

benchmark/metrics/__init__.py, benchmark/metrics/cputime.py, benchmark/metrics/test/test_cputime.py, benchmark/metrics/wallclock.py, benchmark/operations/read_request.py, benchmark/script.py, docs/gettinginvolved/benchmarking.rst
Add CPU time as a metric for benchmarking.
SSH to each node in the cluster, and run a `ps` command to see the elapsed cpu time of named processes (the Flocker services). Perform some operation, and then repeat the `ps` command to see how much the elapsed CPU time has increased for each service.
If you have Flocker cluster available, this allows you to run
```
benchmark/benchmark --control=${FLOCKER_ACCEPTANCE_CONTROL_NODE} --certs=${FLOCKER_ACCEPTANCE_API_CERTIFICATES_PATH} --metric cputime
```
to get output like:
```
{
"scenario": "no-load", 
"timestamp": "2015-11-20T15:52:15.126751", 
"metric": "cputime", 
"client": {
"username": "jon", 
"platform": "Linux-3.13.0-68-generic-x86_64-with-Ubuntu-14.04-trusty", 
"working_directory": "/home/jon/projects/clusterhq/flocker", 
"nodename": …
```
=> [FLOC-3290] Add CPU time metric to benchmark

jobs.groovy.j2
This change adds support for updating a commit status with the build result from Jenkins.
After being unable to provide this support using Jenkins plugins, I have chosen to update the commit status using build steps within the configuration for the __main_multijob project. When the __main_multijob project on Jenkins is triggered for a branch, the commit that is being tested will be updated with the status that the build has started. Two conditional post-build steps have been added to update the commit status with the build result of the __main_multijob. This means the status will not be updated until all the builds within this project have been completed.
To update the status on GitHub, we need to obtain the correct SHA for the commit. This is usually available as an environment variable …
=> [FLOC-3336] Update commit status on GitHub with Jenkins build result

build.yaml, jobs.groovy.j2
Jenkins wasn't retrieving the remote acceptance node logs from the jenkins slaves when the acceptance tests were executed.
This PR sets jenkins to grab those artifacts so that they are available after the Slave is deleted.
build here:
http://ci-live.clusterhq.com:8080/job/ClusterHQ-flocker/job/ADD_REMOTE_LOGS_FLOC-3552/
=> [FLOC-3552] make sure we collect the logs from the acceptance nodes

jobs.groovy.j2
use release-flocker-1.n instead of release/flocker-1.n in the job name
fixes error:
```
00:00:02.732 Processing DSL script jobs.groovy
00:00:04.213 creating ClusterHQ-flocker...
00:00:04.216 iterating over branch... release/flocker-1.7.0
00:00:04.216 found branch... release/flocker-1.7.0
00:00:04.216 creating ClusterHQ-flocker/release-flocker-1.7.0...
00:00:07.192 ERROR: Could not create item, unknown parent path in "ClusterHQ-flocker/release/flocker-1.7.0/_run_docker_build_ubuntu_vivid_fpm"
00:00:07.195 Finished: FAILURE
```
jenkins jobs:
http://ci-live.clusterhq.com:8080/job/ClusterHQ-flocker/job/unable_to_build_release_branches_FLOC-3436/
=> fix for FLOC-3436

build.yaml, jobs.groovy.j2
This adds multiple tabs at the top of the job list to help with the large number of jobs in the branch.
It filters jobs based on:
Cloud Provider
Client
Acceptance
Trial
OperatingSystem
other bits and pieces
view with the added tabs:
http://ci-live.clusterhq.com:8080/job/ClusterHQ-flocker/job/split-jobs-into-different-tabs-FLOC-3556/
=> [FLOC-3556] split jobs into tabs

build.yaml
Fixes https://clusterhq.atlassian.net/browse/FLOC-3563
This removes colorization.  The console output is sufficiently complex that a simple awk-based parser is probably not feasible.  We can re-introduce this functionality later on with a parser that's up to the job.
=> [FLOC-3563] Remove the awk-based color-coding

docs/gettinginvolved/example-acceptance.yml
Fixes 2280
Adds the zone item to the AWS provider section in the gettinginvolved/appendix document.
=> [FLOC 2280] add zone to AWS provider in Appendix

docs/install/index.rst, docs/introduction/get-started.rst
Fixes 3577
Due to TA not working, it has been taken offline to be updated. While this is down, this PR suppresses 2 locations in the documentation which referenced it.
=> [FLOC 3577] Temporarily remove the TrueAbility links from the documentation

admin/test/test_packaging.py
This probably fixes the failing Jenkins test at http://ci-live.clusterhq.com:8080/job/ClusterHQ-flocker/job/master/job/run_trial_on_AWS_Ubuntu_Trusty_admin/lastCompletedBuild/testReport/admin.test.test_packaging/LintPackageTests/test_rpm/
It does so by skipping the test on Ubuntu, which is unsatisfactory, but might lead to us having passing Jenkins builds on master.
The next step is to actually understand and fix the problem.
=> Skip test_rpm on Ubuntu

build.yaml
Fixes https://clusterhq.atlassian.net/browse/FLOC-3590
Note only the removal is needed because `flocker.acceptance` is already listed as a unit test module elsewhere and is so is already run by one of the regular "trial" jobs.
=> [FLOC-3590] Remove the unit test module from the list of acceptance test modules.

docs/gettinginvolved/functional-testing.rst
Fixes https://clusterhq.atlassian.net/browse/FLOC-3545
The instructions for setting up functional tests was missing key environment variables, and then the instructions for each backend were thin.
Working with @jongiddy, we've added the extra environment variables, and provided the commands necessary to run the tests on each backend.
=> [FLOC 3545] Add missing content from Functional Test doc

flocker/node/agents/ebs.py, flocker/restapi/_error.py, flocker/restapi/test/test_infrastructure.py, requirements.txt
1. Upgrade Eliot, and therefore Pyrsistent, so we can get access to new Eliot feature.
2. use the new Eliot feature to make sure all BadRequest exceptions get logged with machine readable response code.
3. Improve default string rendering of a few exceptions so they get logged more informatively by Eliot.
=> [FLOC-3455] Better exception logging

docs/concepts/architecture.rst, docs/introduction/flocker-plugin.rst
Fixes 3348
The Flocker Cluster Architecture content was quite out of date, and didn't include the plugin. This has been updated with the following: 
Remove ZFS example
Replace the use of Convergence Agents with Flocker Agents
Add a section about the Flocker plugin for Docker
Note - FLOC 3598 will add an architecture diagram to this page. This was separated out due to the requirement of getting the image designed and built.
=> [FLOC 3348] Update the Flocker Cluster Architecture document

docs/install/install-client.rst
Fixes 3599
The installing pages used inconsistent style on similar headers in the Client installation page, and the Node installation page. This is a fix.
=> [FLOC 3599] Ensure header style is consistent

docs/releasenotes/index.rst, flocker/apiclient/__init__.py, flocker/dockerplugin/_api.py, flocker/dockerplugin/test/test_api.py
Get rid of a hack that likely caused issues with e.g. deleted datasets.
Builds on #2262 and #2225.
=> [FLOC-2963] No more choosing dataset_id via hashing

flocker/common/test/test_retry.py
Fixes FLOC-3574 where I rolled my own instead of using the twisted provided built-in.
=> Use failureResultOf to verify failed Deferred in tests.

benchmark/_driver.py, benchmark/benchmark.yml, benchmark/metrics/test/test_cputime.py, benchmark/metrics/test/test_wallclock.py, benchmark/metrics/wallclock.py, benchmark/operations/no_op.py, benchmark/operations/read_request.py, benchmark/operations/test/test_wait.py, benchmark/operations/wait.py, benchmark/script.py, benchmark/test/test_script.py, docs/gettinginvolved/benchmarking.rst
It is useful to perform the same benchmark for a series of parameters (e.g. measured with 10, 20, 30 request/sec). Command line options for benchmarking make it difficult to parametrize the various options. 
This PR allows the scenarios, operations, and metrics provided to the benchmarking script to be read from a YAML file, allowing each one to contain additional fields for parameterization.
An example YAML file is added, in which the `wait` operation has been parameterized to wait 10 seconds.
This can be tested by running:
```
./benchmark --control ${FLOCKER_ACCEPTANCE_CONTROL_NODE} --certs ${FLOCKER_ACCEPTANCE_API_CERTIFICATES_PATH} --operation wait-10 --metric cputime
```
The options to the command now name a scenario, operation, or metric in the YAML file, which maps to a type, which …
=> [FLOC-3514] YAML configuration of benchmark scenarios, operations, and metrics

flocker/node/agents/functional/test_cinder.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-3606
The reason it didn't work before is that the directly-created volume didn't appear to belong to the `IBlockDeviceAPI` implementation being used for cleanup and so it wasn't cleaned up.
You can verify this is fixed by running the test and then looking for the created blockdevice_id in the test log and then using the Rackspace Storage web UI to search for it.  On master, you'll always find it.  With the branch, you never should.
Downside is that the test takes twice as long now because it actually has to destroy the volume. :wink: 
Perhaps also noteworthy is that this change should also cause the periodic batch cleanup to be capable of cleaning up this volume should the test runner itself somehow fail to clean it up (because the destroy …
=> [FLOC-3606] Cleanup volume created by test_destroy_timesout

flocker/control/_persistence.py, flocker/control/test/test_persistence.py, flocker/node/_loop.py
Structured information is easier to pretty print, e.g. with json formatting tools or `eliot-prettyprint` (the latter requires some follow up coding though).
=> [FLOC-2997] Log structured information rather than strings for configuration and state

build.yaml
Removes the now obsolete:
http://ci-live.clusterhq.com:8080/job/ClusterHQ-flocker/job/master/job/_run_docker_build_ubuntu_vivid_fpm/
as we no longer support ubuntu vivid
=> [FLOC-3617] remove obsolete _run_docker_build_ubuntu_vivid_fpm

flocker/common/_thread.py, flocker/common/test/test_thread.py
This should allow us to see in the logs the logged Cinder or EBS operations as children of the IStateChange running in the main Twisted thread.
=> Eliot contexts now preserved across threads using our auto-threading support

flocker/node/agents/blockdevice.py, flocker/node/agents/blockdevice_manager.py, flocker/node/agents/test/test_blockdevice.py, flocker/node/agents/test/test_blockdevice_manager.py
Make an explicit interface out of the existing system calls surrounding mounting and formatting disks. This will be useful to have a smaller interface to test and verify as we move to doing fancier mount tricks in the interest of protecting dataset paths in FLOC-3254.
It might also provide a nice abstraction layer to inject mount failures for testing.
The goal is not for this to be a particularly pretty interface at this point, merely just a no-op change that re-slices our code to explicitly call out the interface with the system. Tests are added to help define the interface a little better.
=> Move system interactions with block devices to an Interface

flocker/dockerplugin/__init__.py, flocker/dockerplugin/_script.py, flocker/dockerplugin/test/test_api.py, flocker/restapi/testtools.py
When the `Host` header was empty or missing the the address is used to calculate the host ... and `UNIXAddress` has no `host` attribute. Apparently Docker 1.10 (dev release) stops sending the `Host` header in HTTP requests, or maybe sends it as empty string, triggering this bug; haven't actually looked at Docker source code.
This addresses user-reported issue #2284.
=> [FLOC-3618] Fix another incompatibility between UNIX sockets and Twisted's HTTP implementation

flocker/provision/_aws.py
We are making two calls right after the instance creation,
`boto.ec2.instance.update()` and `boto.ec2.connection.create_tags()`,
so these could be affected by the problem.
Now, if we get `InvalidInstanceID.NotFound` error we simply retry the
affected calls.
https://clusterhq.atlassian.net/browse/FLOC-3537
=> aws may transiently refuse to recognize a new pending instance

benchmark/metrics/cputime.py, benchmark/metrics/test/test_cputime.py
Add wallclock times to CPU time samples to enable calculation of CPU load % from raw CPU times.
Wallclock times are calculated per node, to handle any delays for an individual node's network.
The wallclock time is measured at the start of parsing the output. This would seem to be the point on the local side with the fewest opportunities for added latency from external conditions.
=> [FLOC-3628] Add elapsed wallclock time to CPU time samples.

benchmark/_driver.py, benchmark/cluster.py, benchmark/metrics/cputime.py, benchmark/metrics/test/test_cputime.py, benchmark/metrics/wallclock.py, benchmark/operations/no_op.py, benchmark/operations/read_request.py, benchmark/operations/test/test_no_op.py, benchmark/operations/test/test_read_request.py, benchmark/operations/wait.py, benchmark/scenarios/no_load.py, benchmark/script.py, benchmark/test/test_cluster.py, benchmark/test/test_driver.py, benchmark/test/test_script.py, docs/gettinginvolved/acceptance-testing.rst, docs/gettinginvolved/benchmarking.rst
This PR:
- adds a BenchmarkCluster class that describes the cluster being benchmarked.
- replaces the command line options `--control` and `--certs` with a `--cluster` option to specify the location of cluster description created by the Quick Start Flocker installer.
- creates a BenchmarkCluster from either the files created by the Quick Start Flocker installer, or from the environment variables displayed by `run-acceptance-tests --keep`.
- passes the BenchmarkCluster as a parameter to each benchmark scenario, operation, and metric class, rather than passing the control service.
In particular, this change allows the private to public IP mapping to be made available to the parameter classes.  Hence, the "hack" that reads an environment variable has been removed from the `CPUTime` metric.
=> [FLOC-3557] Read cluster description from YAML file

flocker/provision/_aws.py
So now we wait until the instance is running and its ip_address attribute
is not None.
https://clusterhq.atlassian.net/browse/FLOC-3538
=> [FLOC-3538] sometimes ec2 instance gets public ip address _after_ becoming running

flocker/provision/_aws.py
Previously we would wait until the terminated instance is completely
removed (could take a long time) and then failed with an exception.
Now we retry the creation of an instance.
For additional convenience _wait_until_running() returns True if the
instance has become running, False otherwise.
=> [FLOC-3541] pending aws instance may transition to terminated without running

build.yaml, dev-requirements.txt, flocker/testtools/_base.py, flocker/testtools/_flaky.py, setup.py
It's taking days to get patches landed in testtools and these delays are having a direct & significant impact on our development velocity (flaky tests; debugging info from failing tests). This patch circumvents  that by using a temporary, dedicated fork: ClusterHQ/testtools#clusterhq-fork
The trade-off is that we'll probably have to do some rework in exchange for advancing our learning from the future to today.
The fork currently incorporates the latest versions of testing-cabal/testtools#165 and testing-cabal/testtool#171.
The astute will note that we've _already_ learned something, which is that testing-cabal/testtools#165 isn't enough for a `RunTest` implementation to be able to run a test case twice. I plan to address that in a follow-up patch on testtools, since 165 is already huge.
=> [FLOC-3498] Use ClusterHQ fork of testtools

flocker/apiclient/_client.py, flocker/apiclient/test/test_client.py, flocker/common/_retry.py, flocker/common/test/test_retry.py, flocker/dockerplugin/_api.py
The Docker plugin, and utilities it relied on, don't preserve Eliot context. Fix that so it's easier to read a trace of what happened.
=> [FLOC-3641] Improve Docker plugin logs

build.yaml
Fixes https://clusterhq.atlassian.net/browse/FLOC-3670
Maybe also puts less load on cloud providers to run our acceptance tests since it cuts the number of jobs from 9 to 3.
=> [FLOC-3670] Define acceptance testing jobs more broadly

docs/config/generate-api-certificates.rst
Fixes 3650
The current wording allowed the user to believe that generating API User Cert was optional. This PR rewords the intro to make it clear all users must do this step.
=> [FLOC 3650] Update the intro to the API User Cert doc

docs/install/index.rst
Fixes 3632
The current wording allowed the user to believe that the installation of the plugin was a separate page - this is no longer true, as the Plugin installation is now an optional step in the node services instructions.
=> [FLOC 3632] Update the Full Install information 

docs/concepts/security.rst, docs/config/configuring-authentication.rst, docs/config/generate-api-certificates.rst, docs/config/generate-api-plugin.rst, docs/control/cli/usage.rst, docs/introduction/flocker-plugin.rst, docs/labs/volumes-gui.rst
Fixes 3652
"API User" was identified as implying a human user, whereas the API can actually be invoked by either a real user, or a machine. Renamed our use of the API user as the API client. 
In a few situations I specified "the API client, or end user"
=> [FLOC 3652] Rename the API User to API Client

tox.ini
You can test by running `tox -e py27`, `tox -e sphinx`, `tox -e admin` - previously they'd blow up because they couldn't find forked testtools.
=> [FLOC-3678] Fix tox to work with forked testtools.

docs/concepts/architecture.rst, docs/concepts/leases.rst, docs/concepts/security.rst, docs/config/configuring-nodes-storage.rst, docs/config/enabling-control-service.rst, docs/config/generate-api-certificates.rst, docs/control/administering/debugging.rst, docs/control/administering/upgrading.rst, docs/control/cli/usage.rst, docs/gettinginvolved/benchmarking.rst, docs/install/setup-aws.rst, docs/introduction/flocker-basics.rst, docs/labs/installer-getstarted.rst, docs/labs/volumes-gui.rst
Fixes 3651
Identified in the Generating API certificates documentation, we refer to "the control service" throughout the docs, but in most cases this should be "the Flocker control service", which can be linked to the control service description in the concepts section.
This PR amends these instances, and adds the link in key places.
=> [FLOC 3651] Update how we refer to the control service in the docs

benchmark/benchmark.yml, benchmark/operations/read_request.py, benchmark/operations/test/test_read_request.py, docs/gettinginvolved/benchmarking.rst
This PR allows the user to select a method to be called during a benchmark read request operation.  The allowed methods are the zero-parameter methods of the interface `IFlockerAPIV1Client`.
The default method is the relatively simple `version` method, but other methods can be set to observe if they behave differently during the benchmarks.
=> [FLOC-3291] Benchmark read request parametization

flocker/testtools/_flaky.py, flocker/testtools/test/test_flaky.py
Fixes two issues in `@flaky` decorator where test names would not be reported until they were finished (FLOC-3511), and where the reported duration of the test would be very very low (FLOC-3499).
The fix for both issues is the same thing, because they have the same underlying cause: we were only calling `startTest` after the test had actually run.
I didn't write tests for the symptoms because that involves pulling in large amounts of Trial infrastructure. Testing the cause + useful test docstring seemed sufficient to me.
=> [FLOC-3499,FLOC-3511] Call startTest as soon as the test starts

CONTRIBUTING.rst, dev-requirements.txt, docs/gettinginvolved/infrastructure/packaging.rst, flocker/testtools/_base.py, flocker/testtools/_flaky.py, flocker/testtools/test/test_base.py, setup.py
Re-enables logging in acceptance tests to go to _trial_temp/test.log. 
Uses the latest version of our fork of testtools (which applies testing-cabal/testtools#172) to disable the automatic suppression & capture of Twisted logs, and then manually invokes the fixture to capture the logs.
This means that the logs will appear as the `twisted-log` detail, and _also_ in `test.log`.
I couldn't think of a non-awful automated test for the latter, but I did a manual test and it appeared to work.
I've also added a couple of exceptions which I hope will do something to mitigate the awfulness of using the testtools fork.
=> [FLOC-3663] Restore Twisted log to _trial_temp/test.log

flocker/common/script.py, flocker/node/agents/blockdevice.py, flocker/node/agents/ebs.py, flocker/node/script.py, flocker/node/test/test_script.py
Fixes FLOC-3461. Gives error messages in the logs for incorrect AWS region or zone config, e.g.:
```
Dec 11 16:54:18 ip-172-31-8-201 flocker-dataset-agent[23631]: {"task_uuid": "478c2863-c875-47a9-87d5-c3a772ddd907", "error": false, "timestamp": 1449852858.826969, "message": "Log opened.", "message_type": "twisted:log", "task_level": [1]}
Dec 11 16:54:26 ip-172-31-8-201 flocker-dataset-agent[23631]: {"task_uuid": "77afedae-ed6c-4ed1-8cba-e20edc6243a0", "error": true, "timestamp": 1449852866.720357, "message": "(u'Configuration error', u'The specified AWS region is not valid', 'us-west-9')", "message_type": "twisted:log", "task_level": [1]}
Dec 11 16:54:26 ip-172-31-8-201 flocker-dataset-agent[23631]: {"task_uuid": "5d36dd5f-63d4-4e19-aa12-3a0047fe8c94", "error": false, "timestamp": …
```
=> [FLOC-3461] EBS validate region

flocker/node/agents/test/test_blockdevice.py
Fixes FLOC-3711 by passing number of iterations through in the Exception and using that count in the error message.
=> [FLOC-3711] Fix count of iterations in failure message.

benchmark/cluster.py, benchmark/metrics/test/test_cputime.py, benchmark/operations/test/test_read_request.py, benchmark/test/test_cluster.py, benchmark/test/test_script.py
In order to introduce a "create dataset" operation, it is useful to have a size for the dataset. Since valid sizes differ by clouds platform, it is great if the user gives us this information.
If we use the acceptance test environment variables (currently our preferred solution), an appropriate value is available in one of the environment variables.
If we use the UFT Flocker Installer, there is no value provided. However, the API allows `None` to be provided as this parameter.  We can live with this, as benchmarking is an internal process, and if it causes problems, we may find them before someone else.
=> [FLOC-3705] Add default volume size, if available, to benchmark cluster

build.yaml, docs/control/cli/application-config.rst, docs/control/cli/docker-compose-config.rst, docs/gettinginvolved/plugins/building-driver.rst
Docker probably changed their SSL configuration, which broke our links that were redirecting from http://docs.docker.com to https://docs.docker.com. Updating the links to correctly point to https://docs.docker.com removes these errors from the build. Unfortunately, it does so because we do not check https links. Fixing that problem is out of scope for this patch, since the priority is to unbreak master.
In addition, since master started breaking due to https links, we added extra failures by deleting some buildbot jobs. I've taken the liberty of updating the documentation that used those examples.
=> [FLOC-3695] Fix broken run_sphinx job by fixing broken docs links

flocker/testtools/_base.py, flocker/testtools/test/test_base.py
testtools tests can attach content that shows up when tests fail. This PR attaches the Twisted log _but_ it processes the Twisted log, separating out the `ELIOT` lines from the rest of the log and pretty prints the Eliot logs.
=> [FLOC-3676] Separate Eliot logs from Twisted logs in acceptance test failures

flocker/common/_retry.py, flocker/common/test/test_retry.py
Passing a `functools.partial` to `loop_until` fails to serialize correctly.
Add an extra exception clause to the `function_serializer` function to handle callables that are rejected by the `inspect` module functions.  In particular, handle `partial` usefully by adding the details of the wrapped function.
Although it would be possible, I have not included the partial's arguments in the logging, as they may cause further serialization problems or expose sensitive information.
=> [FLOC-3733] Serialize non-inspectable callables for loop_until logging

flocker/ca/functional/test_ca.py, flocker/common/functional/test_era.py, flocker/node/agents/blockdevice.py, flocker/node/agents/test/strategies.py, flocker/node/agents/test/test_blockdevice.py, flocker/node/functional/test_deploy.py, flocker/node/functional/test_docker.py, flocker/node/test/test_docker.py, flocker/testtools/_base.py, flocker/testtools/_flaky.py, flocker/testtools/_testhelpers.py, flocker/testtools/test/test_base.py, flocker/testtools/test/test_flaky.py, flocker/volume/functional/test_service.py
We had the `@flaky` decorator on a bunch of tests that weren't being retried, because that requires a base `TestCase` that does the retries and we wanted to fix some regression (esp. re logging) before we spread the new base TestCases around the flocker code base.
Now that the regressions are fixed, we want to start retrying everything decorated with `@flaky`. This is it.
The guts of the change are:
* Change `flocker.testtools.TestCase` to inherit from [testtools](https://testtools.rtfd.org) `TestCase`
* Share compatibility code written to work with `AsyncTestCase` to also work with `TestCase`, and update tests
* Update tests for `@flaky` retries to operate on standard `testtools.TestCase`.
* Fix ordering issue in blockdevice tests that arose out of differences in implementation in …
=> [FLOC-3483] Make sure all @flaky tests are retried

build.yaml, vagrant/dev/Vagrantfile, vagrant/tutorial/Vagrantfile
* unsets 'set -x' so that we won't leak secrets to the logs
* removes a chunk of dead code (parse_logs)
* adds a retry function, to retry the most common failures with the vagrant build jobs
* adds a few helper functions for the vagrant operations
* fixes some issues where the vagrant boxes would run out of mem
* updates the vagrant box to use centos 7.1 and not spend too much time updating the OS
* OSX client tests will now pull the latest OSX box from S3
* OSX and tutorial will now upload the nightly built box to S3
This PR will make sure our vagrant builds will upload the resulting arfifacts to a bucket in S3.
This will allows us to grown our mesos cluster and remove a dependency where the OSX client instalation tests would fail if the OSX vagrant basebox hadn't been built yet. This so …
=> [FLOC-3435] upload and consume clusterhq vagrant boxes from S3

admin/package-files/systemd/flocker-control-agent.socket, admin/package-files/systemd/flocker-control-api.socket, admin/package-files/systemd/flocker-control.service, admin/package-files/upstart/flocker-control.conf
Fixes https://clusterhq.atlassian.net/browse/FLOC-3712
This removes flocker-control socket activation.  The systemd documentation suggests that the way Twisted's systemd socket inheritance feature works makes it unreliable to use that feature to heterogeneous service configuration.
(discovered and fixed while pairing with @jml)
=> [FLOC-3712] Make flocker-control serve the right service on the right port

flocker/node/agents/test/test_blockdevice.py
Resubmission of #2347 that uses less loop devices at a time.
This was merged yesterday, but then caused errors on master (https://clusterhq.atlassian.net/browse/FLOC-3738) and was reverted.
I was easily able to reproduce those errors on Jenkins:
Builds #1 and #2 at:
http://ci-live.clusterhq.com:8080/job/ClusterHQ-flocker/job/more-carefully-enable-test-simple-transitions-FLOC-3713/job/run_trial_on_AWS_Ubuntu_Trusty_as_root_flocker.node.agents/
I believe the issue is that Ubuntu cannot handle creating ~30 loop devices, which is approximately what this test does if you don't properly clean up the loop devices after each hypothesis example.
We were destroying the loop devices, but we weren't unmounting all of the locations they were mounted to. Loop devices aren't actually destroyed until …
=> [FLOC-3713] More carefully enable test_simple_transitions.

admin/acceptance.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-3743
Ubuntu acceptance test jobs on master have empty remote logs.  Hopefully equivalent jobs for this branch will have non-empty remote logs.
Also, hopefully, the change is obviously correct.
=> [FLOC-3743] Fix a syntax error in the tail command used to capture upstart logs

flocker/provision/_ssh/_conch.py
I've observed an ssh connection getting indefinitely stuck here.
Plus a couple of small improvements in the nearby code.
=> [FLOC-3706]  place a 30 second timeout on a secureConnection() attempt 

docs/concepts/storage-profiles.rst, docs/config/convergeio-configuration.rst, docs/config/dell-configuration.rst, docs/config/hedvig-configuration.rst
Fixes 3622
Note, this content appears on 2 pages:
config/configuring-nodes-storage
concepts/storage-profiles
the wording has been chosen so the content makes sense in both locations.
=> [FLOC 3622] add a list of the backends that support profiles

build.yaml
Run Cinder and EBS acceptance tests as a nightly cron job, for now.
=> [FLOC-3668] Nightly cloud acceptance

admin/acceptance.py
Because main() is decorated with @inlineCallbacks there is no guarantee
that the control flow always returns to it after a yield statement.
In particular, that's the case if the reactor is stopped.
And that could happen, for instance, if a user presses Ctrl-C because
twisted installs a SIGINT handler which stops the reactor.
Thus, to improve the chances of the cluster clean-up being executed
the clean-up code is moved to a before-shutdown system event trigger.
Also, we now destroy the cluster if we couldn't finish its setup
even if --keep option is set.
=> [FLOC-3665] run-acceptance-tests: make cluster clean up more robust

flocker/apiclient/_client.py, flocker/apiclient/test/test_client.py, flocker/control/_model.py
The `flocker.apiclient.FlockerClient` does not contain an operation to call the `/state/containers` API.
Adding it to support the benchmarking requirement to measure creation of a container and waiting for it to start.
The code is almost a combination of the call to obtain Dataset state and obtain Container configuration.  
Code for both the fake and real containers need additional information to be transferred from configuration to state during synchronization.  The `FakeFlockerClient` copies configuration to state during synchronization.  The tests for the real `FlockerClient` copy the applications data from the persistence service to the cluster state service.
=> [FLOC-3740] Add call to obtain container state

flocker/common/_defer.py, flocker/common/test/test_defer.py, flocker/node/agents/functional/test_cinder.py, flocker/node/agents/functional/test_cinder_behaviour.py, flocker/node/agents/functional/test_ebs.py, flocker/node/agents/test/test_blockdevice.py, flocker/node/agents/test/test_cinder.py, flocker/node/agents/test/test_ebs.py, flocker/node/test/test_change.py, flocker/node/test/test_container.py, flocker/node/test/test_deploy.py, flocker/node/test/test_diagnostics.py, flocker/node/test/test_loop.py, flocker/node/test/test_p2p.py, flocker/node/test/test_script.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-3750
This also makes a change to `flocker.common.gather_deferreds`.  That function now logs failures using Eliot rather than Twisted.  This supports porting of some `flocker.node` tests which were previously using `flushLoggedErrors` (a feature of Twisted not available from testtools).
=> [FLOC-3750] Change flocker.node to use new Flocker test case base classes

flocker/acceptance/endtoend/test_benchmark.py, flocker/acceptance/integration/test_mongodb.py, flocker/acceptance/integration/test_platform.py, flocker/acceptance/integration/test_postgres.py, flocker/acceptance/integration/testtools.py, flocker/acceptance/test/test_testtools.py, flocker/testtools/_base.py
Previously, almost but not all of the acceptance tests used the new `flocker.testtools.TestCase` and `AsyncTestCase` base classes. This patch make it all.
Things to watch out for:
* Update trial `SkipTest` references to `self.skipTest`
* Use the `reactor` instance variable that's available on `AsyncTestCase`
This is part of a general migration to use the new base test cases. See [FLOC-3281](https://clusterhq.atlassian.net/browse/FLOC-3281).
=> [FLOC-3765] Use flocker base test cases in acceptance tests

flocker/common/test/test_thread.py, flocker/node/agents/functional/test_ebs.py, flocker/node/agents/test/test_blockdevice.py, flocker/node/agents/testtools.py, flocker/node/test/istatechange.py, flocker/node/test/test_deploy.py, flocker/node/test/test_testtools.py, flocker/node/testtools.py
`git grep -l 'from twisted.trial.unittest import .*TestCase'` revealed that there were still a few references to Twisted test cases after #2383. This polishes those off.
=> [FLOC-3764] Use flocker test cases in flocker.node

benchmark/scenarios/test/test_no_load.py
Fixes a non-executed test, that also contained a bug. The test passed a callback result to the `stop` method as an extraneous parameter. This was not detected because the test method did not start with the `test` prefix.
Also, changed interface test to avoid use of `globals()`, following a comment on Slack. https://clusterhqteam.slack.com/archives/flocker-benchmarking/p1450723154000373
=> [FLOC-3755] Fix benchmark no load scenario test

flocker/acceptance/endtoend/test_dockerplugin.py, flocker/node/agents/functional/test_cinder.py, flocker/node/agents/functional/test_cinder_behaviour.py, flocker/node/agents/functional/test_ebs.py, flocker/node/agents/test/blockdevicefactory.py, flocker/node/agents/test/test_blockdevice.py, flocker/node/agents/test/test_ebs.py, flocker/testtools/_base.py
Makes it easier to grep for things that are still using Trial base cases.
In particular, I want to grep with:
```
$ grep -l 'from twisted.trial.unittest import'
```
=> [FLOC-3768] Stop using Trial SkipTest

docs/_themes/clusterhq/layout_docs.html, docs/releasenotes/index.rst
Fixes 3772
This change was added as part of the ongoing updates to Documentation under FLOC 3718, however this update was seen to be a good change which is not specific to 3718.
The Release Notes were previously listed by release number, but this has grown to a long list. This PR adds sections headers and a linked menu.
=> [FLOC 3772] Update the layout of the Release Notes docs

docs/gettinginvolved/infrastructure/release-process.rst
Fixes 3773, which replaces 2 doc-dev links with the new master build from Jenkins.
=> [FLOC 3773] Fix broken doc links

build.yaml
Fixes https://clusterhq.atlassian.net/browse/FLOC-3726
Give CentOS, slower probably because of bad Docker configuration, two hours to run the acceptance tests.
Give Ubuntu, which almost always finishes in less than 45 minutes, 90 minutes to be sure we don't hit the timeout.
=> [FLOC-3726] Increase the Jenkins timeouts for running the acceptance test suite.

build.yaml
Fixes https://clusterhq.atlassian.net/browse/FLOC-3680
Give them twice as long to run on the premise that they pass most of the time now so
they should have a really, really good chance of passing all the time with twice as
long.
=> [FLOC-3680] Increase the Jenkins timeouts for running the Cinder functional test suite

flocker/apiclient/_client.py, flocker/apiclient/test/test_client.py
For benchmarking, we still require the container API. However, the `flocker.apiclient.Client` does not support volumes attached to containers, which is needed for benchmarking.
This PR adds support for stateful containers to the API client, both when creating containers, and when receiving information about container configuration and state.
Note the use of PEP 484 type annotations in the docstrings. Currently we have a variety of patterns for non-primitive docstring types (including `|`, top-level type only (`dict`), verbose descriptions, and leaving them out completely).  Despite there being no implementation support for them in Python 2, the PEP 484 type annotations work particularly well for a function like `_parse_volumes`, where they quickly make apparent the transformation taking …
=> [FLOC-3767] Container volume support in API client

build.yaml
Keep the docs at http://doc-dev.clusterhq.com/ in sync with the latest master branch. When a branch's docs are uploaded to S3, run a sync operation between `cluster-staging-docs/master` and `doc-dev.clusterhq.com`. 
The sync only copies files that have changed, so will normally only perform actions when the branch being updated is `master`.  We could use a shell conditional to restrict the sync to only when the updated branch is `master`, but I didn't want to push my Jenkins non-knowledge too far.
It appears that S3 syncs between buckets are sensitive to selecting the correct region, so code makes sure that we use the correct region.  It also sets the public read permissions, since we are setting the to-level of the bucket, so there is no parent to inherit permissions from.
I have run the …
=> [FLOC-3585] Update doc-dev to latest docs from master

flocker/apiclient/test/test_client.py
Part of the overall march of migration. 
Had to tweak one test slightly, because `Lease` object isn't ordered.
=> [FLOC-3777] Migrate apiclient tests to new base cases

admin/ci-tools/cleanup-vagrant-boxes, build.yaml
Fixes https://clusterhq.atlassian.net/browse/FLOC-3775
This introduces a step to clean up all versions of the Vagrant box used by the OS X client installation test job.  This should avoid the slave running out of disk space just from running this job repeatedly.
Stacked on top of #2398 which fixes a problem seemingly already present in master with this job.
=> [FLOC-3775] Clean up OS X Vagrant boxes

flocker/common/functional/test_ipc.py, flocker/common/functional/test_script.py, flocker/common/test/test_algebraic.py, flocker/common/test/test_defer.py, flocker/common/test/test_era.py, flocker/common/test/test_interface.py, flocker/common/test/test_ipc.py, flocker/common/test/test_openstack.py, flocker/common/test/test_retry.py, flocker/common/test/test_runner.py, flocker/common/test/test_script.py, flocker/common/test/test_thread.py, flocker/common/test/test_version.py
Mostly mechanical. Some tests have been changed to be synchronous where they weren't before.
In modules that were already using absolute imports, I used absolute imports
=> [FLOC-3788] Migrate flocker.common tests to new base cases

flocker/provision/test/test_ca.py, flocker/provision/test/test_common.py, flocker/provision/test/test_install.py, flocker/provision/test/test_ssh_conch.py, flocker/provision/test/test_ssh_keys.py
Again, straightforward migration. No tests changed synchronicity. I updated some tests that were importing the reactor to use the one provided by `AsyncTestCase` (actually just the global reactor under the hood, so no real difference).
=> [FLOC-3790] Move flocker.provision tests to new base cases

flocker/common/functional/test_script.py
Eliot uses the presence of libsystemd to decided whether journald
is available, so have the test use the same check for skipping,
rather than assume that journalctl will be present if the user
can write to journald.
https://clusterhq.atlassian.net/browse/FLOC-3735
=> [FLOC-3735] Correctly skip --journald test when libsystemd is available.

flocker/control/schema/types.yml, flocker/control/test/test_schemas.py
Docker accepts container names according to the pattern at https://github.com/docker/docker/blob/09ad1bbc5897e34c6e6d5612b0e1ba709ed28a7d/utils/names.go
`flocker-deploy` does not perform any validation of the name, but Flocker's HTTP API constrains JSON requests and responses to a more restricted pattern. This can cause status 500 errors if containers are created using `flocker-deploy` and then interrogated using the HTTP API. Update the HTTP API to match the Docker pattern.
=> [FLOC-3798] Update Docker container name constraints.

flocker/test/test_flocker.py, flocker/test/test_testtools.py, flocker/testtools/__init__.py, flocker/testtools/test/test_amp.py, flocker/testtools/test/test_cluster_utils.py
Another mechanical translation.
=> [FLOC-3793] Migrate flocker.test and flocker.testtools to new test base classes.

flocker/node/agents/test/test_blockdevice.py
This enhances the previously created test to actually use docker to write to dataset paths from flocker which more specifically tests for the bad behavior we want to protect against in FLOC-3254.
=> [FLOC-3796] Test protecting datasets using real docker

flocker/control/test/test_httpapi.py, flocker/restapi/docs/test/test_publicapi.py, flocker/restapi/test/test_infrastructure.py, flocker/restapi/test/test_schema.py, flocker/restapi/testtools.py
This change was entirely mechanical.
Thanks,
James
=> [FLOC-3792] Migrate restapi tests to flocker.testtools base classes

benchmark/metrics/test/test_cputime.py
The current code for testing the cputime benchmark requires knowledge of an always present process name, and assumes that Ubuntu uses `init` and CentOS uses `systemd`. However, Ubuntu 15.10 uses `systemd`.  Rather than update the current distribution detection, make it more robust by getting the name of process 1, and using that.
This has been tested on Ubuntu 14.04, 15.10, and OS X (where it skips the tests that use `_standard_process`).
=> [FLOC-3806] More reliable way to find always-present process name

docs/config/emc-configuration.rst, docs/introduction/flocker-supports.rst, docs/releasenotes/index.rst
Fixes 3809
EMC have provided a flocker driver for VMAX. This PR adds the link to our list of community provided backends.
=> [FLOC 3809] add EMC VMAX driver to configuration doc

benchmark/_driver.py, benchmark/benchmark.yml, benchmark/operations/__init__.py, benchmark/operations/_common.py, benchmark/operations/create_container.py, benchmark/operations/create_dataset.py, benchmark/operations/test/test_create_container.py, benchmark/operations/test/test_create_dataset.py, benchmark/script.py, benchmark/test/test_driver.py, docs/gettinginvolved/benchmarking.rst, flocker/apiclient/__init__.py
Add a benchmark operation to create a stateful container and wait for it to start.
This performs the following actions:
1. create a container and then delete it, to ensure the image will not need to be pulled later, during the measured part of the benchmark;
2. create a dataset;
3. create a container attached to the dataset;
4. wait for the container to be running;
5. delete the container and dataset.
Steps 3 and 4 are in the `run` method of the probe, and hence are the operations that are measured by the benchmark.
If you have a Flocker cluster handy, and the acceptance test environment variables set, change to the `benchmark` directory and run:
```
./benchmark --operation create-container
```
which creates output like:
```
{
"scenario": {
"type": "no-load", 
"name": "default"
}, …
```
=> [FLOC-3294] Benchmark container creation

flocker/node/agents/blockdevice_manager.py, flocker/node/agents/test/test_blockdevice_manager.py
To do some of the fancy bind mounts, remounts, and tmpfs mounts that are required for FLOC-3254, we'll have to expand the interface with the kernel.
Putting this behind an interface because we've noticed that it behaves slightly different on CentOS and Ubuntu, so I'll probably be writing verified fakes for each of those, and I need some interface in order to be able to inject the different verified fakes.
=> [FLOC-3685] Expand blockdevice manager for upcoming work protecting our dataset mounts.

flocker/ca/test/test_script.py, flocker/cli/test/test_cli_script.py, flocker/cli/test/test_deploy_script.py, flocker/common/test/test_script.py, flocker/control/test/test_script.py, flocker/testtools/__init__.py, flocker/volume/test/test_script.py
As requested in the Jira ticket, replaces inheritence based classes with a class generator.
=> [FLOC-3794] replace FlockerScriptTestsMixin should follow the make_foo_tests pattern

admin/acceptance.py, docs/gettinginvolved/acceptance-testing.rst, docs/gettinginvolved/example-acceptance.yml, flocker/provision/_aws.py
AWS acceptance and benchmark tests always use an `m3.large` instance.  This patch allows the `aws` configuration stanza to contain an `instance_type` entry to override this.
The field is optional. If missing, it default to the current behavior.
To test, add `instance_type: m3.xlarge` (or any other AWS instance type) to your acceptance testing configuration file and start a cluster using `admin/run-acceptance-tests` or `admin/setup-cluster`. Using the AWS console, you can see the instance types for the cluster nodes.
=> [FLOC-3812] Allow specification of AWS instance type for acceptance/benchmark tests

benchmark/script.py, benchmark/test/test_script.py, docs/gettinginvolved/benchmarking.rst
Provide the ability to supply additional data for the JSON output of the benchmark script.  This is useful to provide data about the benchmark run that cannot easily be determined automatically by the script.
The particular use-case is to supply the Git branch for the benchmark cluster. While the Git SHA is easily obtained through the version number, it is difficult (and, in general, impossible) to determine the intended branch name.  This PR allows that information to be provided by the caller of the benchmark script, who has more information about the cluster, including which branch they deployed.
=> [FLOC-3760] Benchmark userdata option

benchmark/_driver.py, benchmark/script.py, benchmark/test/test_driver.py, benchmark/test/test_script.py, docs/gettinginvolved/benchmarking.rst
Allow the number of benchmarking samples to be provided as a command line parameter, rather than fixed at 3.
A particular use case is to help with generating benchmarks that are specified as meeting a limit in X% of cases. Running 100 samples can generate results to easily check such benchmarks.
=> [FLOC-3823] Parametrize number of benchmark samples to take

flocker/node/agents/functional/test_ebs.py
The build failures we're seeing for this test are most likely AWS' eventual consistency biting us - the logs for the test indicate Flocker is attempting to do the right things it's supposed to be doing, but not getting the expected volume states from EC2. So this PR just adds the flaky decorator to allow us to accept at least 1 out of 3 runs passing.
=> [FLOC-3832] Add flaky decorator for affected test

benchmark/_method.py, benchmark/benchmark.yml, benchmark/operations/read_request.py, benchmark/operations/test/test_read_request.py, benchmark/scenarios/read_request_load.py, benchmark/scenarios/test/test_read_request_load.py, benchmark/test/test_method.py, docs/gettinginvolved/benchmarking.rst
Allow the operation used in the benchmarking read load scenario to be set as a parameter.
FLOC-3399 specifies a particular operation to be used for benchmarking, which was different to the existing operation.  The read request /operation/ already allowed the method to be specified as a parameter.
This PR adds the same ability to the read load scenario. Major changes include the extraction of common code for validating the method name into a separate file, and modifying the fake benchmark clients for testing to handle any method, not just the original one.
Also, there was no documentation for the write load scenario, so this was added while updating the read load scenario docs.
=> [FLOC-3833] Allow the method used by read request scenario to be set as a parameter.

docs/config/emc-configuration.rst
EMC recently changed the URLs for their backend storage drivers.
This PR updates our documentation to point at the right GitHub repositories.
=> [FLOC 3837] Fix broken EMC links

jobs.groovy.j2
Fixes https://clusterhq.atlassian.net/browse/FLOC-3799
This removes the separate `copyArtifact`-calling loop over some of the jobs (all except the cron jobs) and replaces it with a `copyArtifact` call in the `build_steps` method that is called for every job.
This has two consequences:
* The `CopyArtifact` configuration is now part of each job rather than all of the `CopyArtifact` configuration being part of the main multijob (incidental but, I think, an improvement).
* Cron-style jobs now have `CopyArtifact` configuration if they define artifacts that should be copied (the actual point of this PR).
Visual inspection of the generated configuration xml suggest these are actually the consequences achieved by this PR.
=> [FLOC-3799] Collect artifacts (logs) from cron-triggered acceptance test jobs

admin/release.py
Fixes [FLOC-3842](https://clusterhq.atlassian.net/browse/FLOC-3842).
After initialising the release flocker repository, the remote refs are fetched. The first available ref is pulled and the local `master` branch is updated to this point. If the first available ref is not `master`, this can result in a merge conflict when `origin master` is pulled later. The first pull is not necessary. We can simply fetch, checkout `master` and then pull `origin master`.
=> [FLOC-3842] Remove unnecessary git pull from initialize-release script

admin/release.py
To install our forked version of testtools, we need to specify `--process-dependency-links` when performing `pip install`. This flag was missing from the script which sets up the release environment.
=> [FLOC-3840] Add `--process-dependency-links` to the release `pip install` step

docs/releasenotes/index.rst, flocker/node/_change.py, flocker/node/_container.py, flocker/node/_deploy.py, flocker/node/_loop.py, flocker/node/_p2p.py, flocker/node/agents/blockdevice.py, flocker/node/agents/test/test_blockdevice.py, flocker/node/test/test_change.py, flocker/node/test/test_container.py, flocker/node/test/test_loop.py, flocker/node/test/test_p2p.py, flocker/node/testtools.py
*How we got here:*
When the convergence loop is sleeping and gets an update of configuration or cluster state it runs calculate_changes on the deployer with cached local state to see if it should wake up. If a remote node has a volume we want attached, we would return ActionNeeded to indicate we wanted to wake up. Originally ActionNeeded was never run.
After Tom refactored the block device deployer, ActionNeeded ended up actually being run, which resulted in an exception in the logs. Moreover, the ability to sleep until the remote node detached volume we're supposed to move locally went away (temporarily, it'll return eventually). So the choices were either "sleep for 60 seconds, then check if remote detached" or "poll every 0.1 seconds" which hits the cloud API pretty hard. The latter …
=> [FLOC-3781] Replace broken ActionNeeded wakeup placeholder with polling

admin/acceptance.py, docs/gettinginvolved/acceptance-testing.rst, flocker/provision/_aws.py
The AWS benchmarking account uses roles to allow main account users access.  Roles use temporary credentials, which are like normal credentials, but add a session token.
This PR allows the session token to be provided as an additional property in the YAML configuration file for acceptance and benchmark tests.
The token is optional. If not supplied in the YAML file, it defaults to `None`, which indicates that no session token is being provided.
=> [FLOC-3839] AWS session token support for acceptance and benchmark tests

benchmark/_driver.py, benchmark/_interfaces.py, benchmark/scenarios/_rate_measurer.py, benchmark/scenarios/_request_load.py, benchmark/scenarios/no_load.py, benchmark/scenarios/read_request_load.py, benchmark/scenarios/test/test_rate_measurer.py, benchmark/scenarios/test/test_read_request_load.py, benchmark/test/test_driver.py
Add benchmark to provide statistics for request time for the read and write request load scenarios.  This is the final benchmark required for January/March benchmark tests.
The statistics for these benchmarks were already being generated in the `RateMeasurer` object used for the scenarios that generate requests, so this PR focusses on extracting the information and providing them to the user.
Normally a benchmark measures a specific operation, with a scenario running outside the measurement to provide the required load. Since the metric, which measures the operation, does not even know about the scenario, the PR adds a `scenario_metrics` output to the usual measured samples.  This keeps the scenario and metric independent of each other.
The output for the scenario now contains additional …
=> [FLOC-3820] Benchmark latency count

benchmark/_interfaces.py, flocker/__init__.py, flocker/ca/__init__.py, flocker/ca/_script.py, flocker/cli/__init__.py, flocker/common/__init__.py, flocker/common/algebraic.py, flocker/common/script.py, flocker/common/test/test_algebraic.py, flocker/common/version.py, flocker/control/_model.py, flocker/control/test/test_model.py, flocker/control/test/test_model_change.py, flocker/node/_container.py, flocker/node/_docker.py, flocker/node/agents/blockdevice.py, flocker/node/agents/ebs.py, flocker/node/agents/test/test_blockdevice.py, flocker/node/exceptions.py, flocker/node/functional/test_docker.py, flocker/node/script.py, flocker/node/test/istatechange.py, flocker/restapi/_error.py, flocker/restapi/_logging.py, flocker/restapi/_schema.py, flocker/restapi/testtools.py, flocker/route/__init__.py, flocker/route/functional/iptables.py, flocker/testtools/__init__.py, flocker/testtools/_flaky.py
These lint problems are mostly:
1. imports appearing after other code
2. assigned lambdas
3. operators appearing after newline rather than before.
Most of the fixes are to shuffle code around a bit, and convert lambdas to functions.
In `flocker/node`, there was a circular import which worked previously because one of the imports was after the definition of an Exception object.  The exception was moved to its own file to break the circular import.
=> [FLOC-3869] Fix lint problems

docs/config/aws-configuration.rst, flocker/node/agents/ebs.py
In FLOC-3839, support for AWS session tokens was added to the `aws` stanza used to start cluster nodes.
However, the nodes themselves use AWS for managing volumes, so the AWS backend also needs to use session tokens where appropriate.
Session tokens typically only last for an hour, but Flocker agents are likely to last longer than that. So, under the circumstances where they are needed, session tokens will need to be generated by the backend.  FLOC-3857 has been created to solve this.
In the meantime, this PR uses the same solution from FLOC-3839 for short-lived tests.
=> [FLOC-3854] AWS session token support for backend

jobs.groovy
Fixes https://clusterhq.atlassian.net/browse/FLOC-3865
Follow-up for apparently incomplete https://clusterhq.atlassian.net/browse/FLOC-3799
Co-testing with https://clusterhq.atlassian.net/browse/FLOC-3199 / https://github.com/ClusterHQ/flocker/pull/2191 - http://ci-live.clusterhq.com:8080/job/ClusterHQ-flocker/job/better-random-port-assignment-FLOC-3199/view/cron/
=> [FLOC-3865] Configure Jenkins cron jobs with publishers as well

jobs.groovy
Release builds shouldn't merge in to master before running. Firstly
this will sometimes fail for good reason, but more importantly
the merge isn't the code we want to test.
Any branch that named release/* will get a second set of jobs
generated that don't do the merge.
=> [FLOC-3873] Generate a second set of jobs for release builds that don't merge master.

flocker/testtools/__init__.py, flocker/testtools/_base.py, flocker/testtools/_testhelpers.py, flocker/testtools/matchers.py, flocker/testtools/strategies.py, flocker/testtools/test/test_base.py, flocker/testtools/test/test_matchers.py
Adds new helper methods to our base test cases:
* `make_temporary_path` – like `mktemp`, but returns a `FilePath`
* `make_temporary_directory` – returns a temporary directory as a `FilePath`
* `make_temporary_file` – returns a temporary file, with optional content
Adds a new `flocker.testtools.matchers` module that provides `FilePath`-related matchers:
* `path_exists` – matches if a `FilePath` exists on disk
* `dir_exists` – matches if a `FilePath` exists and is a directory
* `file_exists` – matches if a `FilePath` exists and is a file
* `file_contents` – matches on the contents of a file if it exists
Note that `file_contents` is analogous to `testtools.matchers.FileContains` but different in that it _always_ takes a matcher and has a name that reflects this.
In order to make writing the …
=> [FLOC-3883] FilePath matchers and temporary helpers

flocker/common/_retry.py, flocker/common/test/test_retry.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-3895
=> [FLOC-3895] Count timeout for effect retry from the first effect failure

jobs.groovy
This reverts 31c881ccda449a3961896148f80093f853709c89 which moved the
copyArtifacts steps to the invidual jobs, rather than the multijob.
This means that after a build each job tries to copy the artifacts from the
previous run of the job to the current one. The intention is to copy the
results from the current build to the multijob so that they can be examined
in aggregate with the other jobs.
In order to do that the copy needs to be run in the multijob, as it's
"copy <files> to here" operation.
The original intent of the change was to have the artifacts published for
the cron jobs. That is in fact done by defining publishers, and was done in
a followup commit b245c5f7387285db60545f33d29336d2af78f3a2.
=> [FLOC-3896] Move the copyArtifacts tasks back the multijob.

flocker/node/agents/test/test_blockdevice_manager.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-3893
Unfortunately I had could only reproduce the issue on an AWS Ubuntu instance. See the following gist for the logs of my run of the test that convinced me the issue is fixed:
https://gist.github.com/sarum90/db5e48b613f07678d887
=> [FLOC-3893] Add a cleanup of the bind mount.

flocker/common/__init__.py, flocker/common/_filepath.py, flocker/common/test/test_filepath.py, flocker/testtools/_base.py, flocker/testtools/matchers.py, flocker/testtools/strategies.py
Adds new helpers in `flocker.common`:
* `make_file` – create a file with content and permissions
* `make_directory` – create a directory, or do nothing when a directory already exists
Similar code is repeated a lot throughout the code base, so I thought it might be nice to have something more intent-revealing.
Further:
* generators for Unix permissions
* matcher for Unix permissions
* `make_temporary_file` now takes optional permissions
This answers an in-person question asked by @avg-I.
=> [FLOC-3891] Helpers for making files and directories 

admin/cluster_setup.py
This is useful for the easy re-use of the cluster nodes for a new cluster.
Along with `managed.yaml` we also now save a `environment.env` file that contains all the
environment variables needed for running acceptance tests on the cluster
(and potentially interacting with it in other useful ways).
=> [FLOC-3885] generate and save managed config for a newly created cluster

jobs.groovy
Rather than relying on constructing the same or similar strings in several
places use functions to encapsulate the details to reduce the chance of a
mismatch.
Unify some of the job definition as indicated by XXX comments.
Extract the code to trigger a sub job from a multijob without failing the
multijob in to a function.
Migrate from using "job" to trigger a sub job from a multijob as that is
deprecated in favour of using phaseJob. This is currently showing the
deprecation warning on the live instance.
=> [FLOC-3901] Refactor some of the groovy code to reduce duplication.

LICENSE, docs/releasenotes/index.rst
The build results for this branch: http://ci-live.clusterhq.com:8080/job/ClusterHQ-flocker/job/release-flocker-1.9.0/
One job is still failing:  http://ci-live.clusterhq.com:8080/job/ClusterHQ-flocker/job/release-flocker-1.9.0/job/run_lint/1/
This was decided to be an non-blocking issue for the release and was due to [FLOC-3869](https://clusterhq.atlassian.net/browse/FLOC-3869). This issue has now been fixed in master.
=> [FLOC-3816] Release Flocker 1.9.0

build.yaml
We are hoping that more verbose vagrant logging may point to
why we are seeing failures.
=> [FLOC-3911] Add verbose logging to vagrant commands.

flocker/dockerplugin/_api.py, flocker/dockerplugin/schema/types.yml, flocker/dockerplugin/test/test_api.py, flocker/dockerplugin/test/test_schemas.py
`Err` in success cases is supposed to be empty string, not null/None.
https://github.com/docker/docker/commit/cc62a88524b623c8f86075d9ed220196cf5e92da
=> [FLOC-3904] Match Docker plugin API docs

docs/releasenotes/index.rst, flocker/acceptance/endtoend/test_dockerplugin.py, flocker/dockerplugin/_api.py, flocker/dockerplugin/schema/endpoints.yml, flocker/dockerplugin/schema/types.yml, flocker/dockerplugin/test/test_api.py, flocker/dockerplugin/test/test_schemas.py
`docker volume ls` and `docker volume inspect` now use the Docker volume plugin API.
This adds support for the two new calls:
https://github.com/docker/docker/blob/master/docs/extend/plugins_volume.md#volumedriverget
Note that at some point Docker changed their docs to say one should return `"Err": ""` for non-errors; it used to say `"Err": null`. I will do follow up branch to address this for existing commands, but did the new way for the new commands.
I ran the new acceptance tests with an experimental Docker build (`1.10.0-dev`):
```
$ trial flocker.acceptance.endtoend.test_dockerplugin.DockerPluginTests.test_{listed,inspect}
flocker.acceptance.endtoend.test_dockerplugin
DockerPluginTests
test_listed ...                                                        [OK]
test_inspect ... …
```
=> [FLOC-3882] Docker plugin: add support for VolumeDriver.List and VolumeDriver.Get

benchmark/operations/create_container.py, benchmark/operations/test/test_create_container.py
The benchmark script waits for datasets and containers to be created. Occasionally, this may fail, either due to incorrect configuration or Docker getting into a bad state.  Rather than have the benchmark script hang indefinitely, have it timeout.
The timeout is set to 10 minutes, which is a reasonable first guess for a liveable value.  It is not configurable at this stage.
=> [FLOC-3841] Add timeout to benchmark container and dataset creation.

build.yaml
The test is more of an acceptance test, and is also unlikely
to be broken by any particular change, so running it nightly
is reasonable.
In addition it is currently failing often, perhaps related
to parallel versions of the job, so running once a day will
avoid us having to diagnose the root cause of that.
=> [FLOC-3804] Move the OSX installation test to run nightly.

build.yaml
Unfortunately this means increasing the timeout for
all trial tests, or defining new stanzas for just the
test_docker module.
test_docker is currently timing out fairly frequently
because the tests are slow to run. Increasing the
timeout will allow more green runs to happen (if slower)
while we look in to whether we can speed up the tests,
or parallelise them to get the complete suite faster.
=> [FLOC-3920] Increase timeout on node.functional.test_docker tests

jobs.groovy
Report to github the status of individual jobs rather than the multijob.
This means that the information on the github page will be more useful,
as you can see which tests failed without clicking through and
searching. In addition, when a job is retried it will update its status
again, so a passing run will show all green on github even if it
required a job to be retried.
This commit changes the "pending" notifications to be for each test
we intend to run, and then each job does the successful/failing
notifications itself.
The github_status.sh script with the auth details isn't available
on the slaves, so this now embeds it in the script step.
=> Report to github the status of individual jobs rather than the multijob.

admin/find-flaky-tests, admin/flaky.py
New script to dump all of the flaky tests in Flocker.
```
find-flaky-tests --report=tree flocker
```
Will show the flaky tests as a trial output tree. --bugs and --tests will show only bugs or only tests.
=> [FLOC-3930] Flaky audit script

admin/acceptance.py, docs/gettinginvolved/acceptance-testing.rst, flocker/node/script.py, flocker/node/test/test_script.py, flocker/provision/_install.py, flocker/provision/_ssh/_model.py, flocker/provision/test/test_install.py, flocker/provision/test/test_ssh_conch.py
For debugging and benchmarking, it is useful to configure the logging provided by dependencies, which use the standard Python logging rather than Eliot.
This PR adds a `logging` stanza to the `agent.yml` file, which follows the PEP 391 format for specifying logging configuration.
For benchmarking AWS API calls, for example, we can add the following stanza to the YAML configuration file (`acceptance.yml` or equivalent):
```yaml
logging:
version: 1
formatters:
timestamped:
format: "%(asctime)s %(message)s"
datefmt: "%Y-%m-%d %H:%M:%S"
handlers:
boto2:
class: logging.handlers.WatchedFileHandler
level: DEBUG
filename: /tmp/boto2.log
encoding: utf-8
formatter: timestamped
boto3:
class: logging.handlers.WatchedFileHandler
level: DEBUG
filename: /tmp/boto3.log
encoding: utf-8
formatter: …
```
=> [FLOC-3927] Configure dependency logging using agent.yml

admin/acceptance.py
The AWS and the Rackspace drivers had duplicate documentation with the actual docs at http://doc-dev.clusterhq.com/. They also had links to that documentation. Removing the duplicate in favor of the reference to the official documentation.
=> [FLOC-3926] Remove duplicate documentation.

build.yaml, flocker/test/test_meta.py
This will catch some mistakes, e.g. completely omitting a new package from test run. There are many cases it won't catch, see code for caveats.
```
$ git diff
diff --git a/build.yaml b/build.yaml
index 168eeef..65cebe1 100644
--- a/build.yaml
+++ b/build.yaml
@@ -995,7 +995,7 @@ run_trial_modules: &run_trial_modules
- flocker.node.functional.test_docker
- flocker.node.functional.test_script
- flocker.node.functional.test_deploy
-  - flocker.provision
+#  - flocker.provision
- flocker.restapi
- flocker.route
- flocker.test
$ trial flocker.test.test_meta
...
Traceback (most recent call last):
File "/home/itamarst/ClusterHQ/flocker/flocker/test/test_meta.py", line 92, in test_build_yaml_includes_all_repository_tests
pformat(list(expected_tests - configured_tests))))
File …
```
=> [FLOC-3877] Safety net test: check build.yaml lists all packages

admin/acceptance.py, admin/test/test_acceptance.py
FLOC-3927 #2498 unfortunately assumed that `ManagedRunner` followed the structure of `LibcloudRunner`, and used `self.config`, which is not a valid attribute for `ManagedRunner`. @avg-I spotted that this caused an `AttributeError`
This PR changes the `ManagedRunner` class to receive the `logging_config` dictionary directly.  It's use has now been independently tested by both @avg-I and me.
=> [FLOC-3950] Fix attribute error in ManagedRunner

admin/cluster_setup.py
Because main() is decorated with @inlineCallbacks there is no guarantee
that the control flow always returns to it after a yield statement.
In particular, that's the case if the reactor is stopped.
And that could happen, for instance, if a user presses Ctrl-C because
twisted installs a SIGINT handler which stops the reactor.
Thus, to improve the chances of the cluster clean-up being executed
the clean-up code is moved to a before-shutdown system event trigger.
Also, there is no reason now to have except and finally clauses as
(a) there is no guarantee that they are executed, (b) all the except
block did was to re-raise an exception, so no reason to capture it
at all, (c) the finally block would contain only actions that should
be executed on success after the clean-up code was moved to …
=> [FLOC 3948] simplify setup cluster

admin/cluster_setup.py
To be sure that the cluster is completely ready to use after setup-cluster finishes.
=> [FLOC-3949] wait until all provisioned nodes join the newly created flocker cluster

build.yaml
The test definitions for those tests now specify the test module
directly, so don't try and use --testmodule to find it.
=> [FLOC-3958] Remove --testmodule from storage driver tests.

build.yaml
Link checking relies on external services, and is
fairly flaky. Split it out and run it nightly.
We risk landing changes that have broken links, but
we'll far more frequently avoid a red build due
to a flaky external service.
=> [FLOC-3560] Run the sphinx link checks nightly

build.yaml, flocker/test/test_meta.py, jobs.groovy
docker on CentOS runs slow in the default configuration because
it uses loop-devmapper. It's quite hard for us to change that,
but the tests seem more reliable on a slightly larger instance
with a slightly longer timeout. Give it more resources so it
more consistently passes while we find another way to improve
the situation.
=> [FLOC-3903] Give test_docker on CentOS a larger slave and timeout.

flocker/node/agents/_logging.py, flocker/node/agents/ebs.py, flocker/node/agents/functional/test_ebs.py
Line to log a message is missing the `write()` method.
This is amongst the reasons it was difficult to see what is generating the AWS RequestLimitExceeded errors.
=> [FLOC-3965] Ensure log message is written if EBS volume is not ready

benchmark/cluster_containers_setup.py, docs/gettinginvolved/cluster-setup.rst
Compose was used in the container setup script to create datasets and containers in a cluster. As it is deprecated, I have refactored the code to use the flocker client instead. That means that:
* app-template yaml file is no longer used: we only needed to know the Docker image, mountpoint, and we could specify the maximum size of the dataset. Anything else in the yaml file would be ignored, plus it didn't make sense to use a format that doesn't match with what we need to call create_dataset and create_container.
* The options that we do need have been added as command line arguments. That will, in addition, make it easier to integrate this script with the other ones, as we are aiming to have one single script that will do the benchmarking, including creating the cluster and setting up …
=> [FLOC-3889] Benchmark - remove use of compose 

flocker/node/agents/functional/test_ebs.py
The problem reported on this issue seems to be a result of AWS eventual consistency sometimes biting us. Not sure what else we can realistically do except give the tests more time to run and therefore hopefully encounter the volume state they expect to be able to proceed. There is (I think) some planned work around solving eventual consistency problems more broadly in Flocker by keeping track of state locally. See FLOC-3219
=> [FLOC-3832] EBS flaky test

dev-requirements.txt, flocker/node/agents/test/test_blockdevice.py, flocker/node/test/test_testtools.py, flocker/testtools/_base.py, setup.py
Increments the version of testtools that we use.
Practical benefits:
* `expectThat` will actually fail async tests
* new matchers for Deferreds (see http://testtools.readthedocs.org/en/latest/twisted-support.html)
* `testtools.twistedsupport` new namespace for Twisted stuff
* less weird interaction with tests in case of timeout
* slightly less boilerplate in our base cases
=> [FLOC-3933] Use testtools 1.9.0 

docs/_themes/clusterhq/static/css/docs.css
Fixes https://clusterhq.atlassian.net/browse/FLOC-3977
While I was there, fixed bottom padding for these admonitions on low width displays.
=> [FLOC-3977] Fixup labs admonition image and padding.

build.yaml
It's really rather verbose, so obscures any errors, and
will be rarely useful.
=> [FLOC-3970] Remove verbose Vagrant logging.

flocker/acceptance/integration/test_mongodb.py
Should fix https://clusterhq.atlassian.net/browse/FLOC-3500
The code for the integration tests is about as broadly reliable as it's going to get; failures are typically due to these tests having only 2 minutes to run.
=> [FLOC-3500] Disable timeout for Mongo tests

flocker/node/agents/blockdevice.py, flocker/node/agents/ebs.py, flocker/node/agents/functional/test_ebs.py, flocker/node/agents/test/test_blockdevice.py
The EBS driver was returning non-unicode compute IDs for live nodes. This resulted in pyrsistent type errors during raw state discovery and ultimately non-convergence.
Added a functional test so we don't have to rely on acceptance tests to catch this issue in the future.
=> [FLOC-3972] Ensure icloudapis have unicode lists.

admin/acceptance.py, flocker/acceptance/endtoend/test_dataset.py, flocker/acceptance/testtools.py, flocker/apiclient/_client.py, flocker/common/version.py, flocker/provision/__init__.py, flocker/provision/_effect.py, flocker/provision/_install.py, flocker/provision/_sphinx.py, flocker/provision/_ssh/_conch.py
Reverts ClusterHQ/flocker#2293
Recent evidence suggests this is broken on rackspace. I'd rather roll this back, do some testing, then re-merge rather than break the builds on master tonight.
=> [FLOC-3984] Revert "[FLOC-3525] Upgrade testing "

jobs.groovy.j2
Jenkins no longer uses the file, so we can remove the compatibility
symlink.
=> [FLOC-3763] Remove the jobs.groovy.j2 symlink.

docs/_themes/clusterhq/layout_docs.html, docs/index.rst
Changes to navigation and Installing Flocker page to make docs homepage more findable and reduce confusion when navigating Flocker integrations (based on user testing).
**Before**
Navbar and docs homepage:
Links on buttons:
**After**
Navbar and docs homepage:
Links on buttons:
=> [FLOC-3996] Improve signposting on docs.

build.yaml
The other similar jobs have publish_test_results: true, but it
was apparently missed for this one. This will mean that Jenkins
will show the tests that failed for this job like the other jobs.
=> Also publish test results from run_trial_for_ebs_storage_driver_on_CentOS_7

flocker/node/agents/_logging.py, flocker/node/agents/blockdevice.py, flocker/node/agents/ebs.py, flocker/node/agents/test/test_blockdevice.py
We often get `RequestLimitExceeded` errors on AWS.  This PR adds a count field to the logs of functions performing `boto` calls to show how often that operation has been called.  In addition, calls to the higher-level `list_volumes` function are counted, to isolate where they are coming from.
Sample log output:
```json
{"timestamp": 1453822992.761821, "task_uuid": "2e129379-1515-411c-9007-798c8aa27fe0", "action_type": "flocker:agent:discovery", "action_status": "started", "task_level": [2, 2, 1]}
{"count": 406, "task_uuid": "2e129379-1515-411c-9007-798c8aa27fe0", "timestamp": 1453822992.762302, "operation": ["_discover_raw_state", [], {}], "message_type": "flocker:node:agents:blockdevice:list_volumes", "task_level": [2, 2, 2]}
{"count": 406, "task_uuid": …
```
=> [FLOC-3975] Add counts of the most commonly called AWS API calls.

admin/acceptance.py, admin/add-cluster-nodes, admin/cluster_add_nodes.py, admin/cluster_setup.py, docs/gettinginvolved/cluster-setup.rst, flocker/provision/_ca.py, flocker/provision/_install.py, flocker/provision/test/test_ca.py
Also, `setup-cluster` now uses alternative implementation of `LibcloudRunner.start_cluster`.
The alternative implementation should be faster as it creates cloud nodes
in parallel.  Also it should be more robust as it does not fail as long
as it is able to create at least a control node for the cluster.
=> [FLOC-3947] Tool for adding new nodes to an existing Flocker cluster

flocker/provision/test/test_ssh_conch.py
When we moved to the testtools base cases the module-level
skip started being ignored, but we didn't notice because the
tests weren't failing until today.
=> [FLOC-4007] Correctly skip the conch tests.

flocker/node/script.py, flocker/node/test/dummybackend.py, flocker/node/test/test_script.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-3998
Ensures that the loaded config contains at a minimum the parameters required by the chosen backend's API factory, preventing failure with an ugly `TypeError` missing parameters traceback when the config is missing data.
=> [FLOC-3998] Flocker dataset config

docs/releasenotes/index.rst, flocker/node/agents/ebs.py, flocker/node/agents/functional/test_ebs.py, flocker/node/agents/test/test_ebs.py
Flocker currently allows only 11 volumes to be attached on a single AWS node.  This is due to Flocker code only allowing the use of the 11 device names `/dev/sdf` to `/dev/sdp`.
AWS documentation indicates that this subset should always be available on every AMI.
However, we need to support more than 11 attached volumes.
This PR adds another 10 device names (`/dev/sdq` to `/dev/sdz`), which should be available on all but "some custom kernels".
The core change is the string that had the letters `f-p` now has `f-z`.  Everything else is refactoring, mostly to make the tests easier to create.
=> [FLOC-2901] Increase maximum attached EBS volumes

build.yaml
These tests were merged to master after I branched, and I missed
them when I merged master.
=> [FLOC-4012] Notify #engineering about GCE acceptance test failures.

admin/acceptance.py
The comma turns this value into a tuple, which makes rackspace fail to be able to set metadata.
We should probably not have such a fragile API with our provisioners.
=> [FLOC-4019] Fix a regression in rackspace acceptance tests.

docs/conf.py
Fixes [FLOC-4030](https://clusterhq.atlassian.net/browse/FLOC-4030).
Our Jenkins setup is not public and as a result the linkcheck build results in 403 for any links to Jenkins so add it to the list of ignored links.
=> [FLOC-4030] Ignore Jenkins links during linkcheck build

benchmark/scenarios/_request_load.py, benchmark/scenarios/test/test_read_request_load.py, benchmark/scenarios/test/test_write_request_load.py
Cleanup deferred that returned nothing, added after the metrics results, was causing the write load scenario not to generate any output. 
The only change needed was to add the metrics generation as the last step.
=> [FLOC-4014] Fixing scenario cleanup so we don't lose the metrics output

benchmark/_interfaces.py, benchmark/scenarios/_request_load.py, benchmark/scenarios/read_request_load.py, benchmark/scenarios/test/test_request_load.py, benchmark/scenarios/test/test_write_request_load.py, benchmark/scenarios/write_request_load.py
The benchmarking load scenarios work by generating `n` requests per second in a LoopingCall.  LoopingCall can skip iterations, if a single iteration takes longer than the interval between calls.  If that happens, a `count` > 1 is passed to the next iteration.
Current code uses this count to increase the number of seconds passed in the rate measurer, but failed to increase the number of new requests generated - it should be the rate (per second) times the number of seconds passed.
This PR fixes that problem so that the number of requests generated catches up all missed intervals.
Also rename `IRequestScenarioSetup` to the simpler name `IRequest`, since it is mainly encapsulating an arbitrary request.
=> [FLOC-3846] Benchmark scenario catch up

flocker/provision/_libcloud.py
The underlying reason why the key can't be found by flocker
might be important.
In particular our tests sometimes fail with this error and we
don't know why so it will help us if that ever happens again.
=> [FLOC-3492] Include the underlying error in CloudKeyNotFound.

docs/docker-integration/index.rst, docs/kubernetes-integration/index.rst, docs/mesos-integration/index.rst
Fixes 4061
The current titles for Tutorials and Blog Articles did not test well in User Testing - this issue reverts the titles to something simple, adding an internal note that they will need to be changed when further tutorials are added.
=> [FLOC-4061] Rename titles on Integration homepage

docs/releasenotes/index.rst
https://clusterhq.atlassian.net/browse/FLOC-3980
(This is just #2587 with the branch renamed)
=> [FLOC-3980] Release Flocker 1.10

benchmark/script.py, benchmark/test/test_script.py
Add a `version` to the benchmark JSON results, to help us deal with future changes to the schema.
=> [FLOC-3759] Version for benchmark JSON output

build.yaml
Updates Jenkins jobs to add test results for acceptance jobs. This will allow us to see which tests fail rather than being restricted to a binary output
=> [FLOC-3810] Acceptance jobs junit

admin/installer/cloudformation.py
CloudFormation user can leave {AmazonAccessKeyID, AmazonSecretAccessKey, EC2KeyPair} Inputs empty, leading to failure in stack creation, and subsequent trouble in triaging cause of failure (due to stack rollback being default action).
This PR attempts to impose stricter constraints around user Inputs. The constraints are gathered from Amazon documentation.
Master copy of CloudFormation template has been updated with the changes in this PR in order to facilitate testing.
Testing:
* Manual tests passed
* Endtoend test passed:
```
ubuntu@ip-172-31-25-23:~/flocker/admin/installer$ KEEP_STACK=1 CLOUDFORMATION_TEMPLATE_URL=https://s3.amazonaws.com/installer.downloads.clusterhq.com/flocker-cluster.cloudformation.json KEY_PAIR=$KEY ACCESS_KEY_ID=$ACCESS_KEY_ID SECRET_ACCESS_KEY=$SECRET_ACCESS_KEY …
```
=> [FLOC-4085] Tighten constraints on CloudFormation user Inputs

benchmark/_flocker.py, benchmark/cluster_containers_setup.py, benchmark/operations/create_container.py, benchmark/operations/test/test_create_container.py
For large clusters, creating and destroying large numbers of datasets causes problems, due to errors like AWS's RequestLimitExceeded.  This is a problem for benchmarking, where we need to quickly create and delete large numbers of datasets.
This PR changes the benchmarking script that creates stateful containers to slow it down.  Rather than sending up a massive cluster change, we start one stateful container per node in sequence, waiting for them to be running, until all are created.
I decided not to fix the cleanup-containers script because it does work - it just behaves badly while cleaning up - e.g. the AWS console will fail to report on status.  Slowing down cleanup means we must hang around staggering calls, when we may not want to.  Also, users are more likely to try this at home …
=> [FLOC-4010] Slower container creation

dev-requirements.txt, flocker/testtools/_base.py, setup.py
testing-cabal/testtools#172 has landed & been released, so we can control our logging destiny.
=> [FLOC-4092] Use testtools 2.0.0, rather than our fork

build.yaml, jobs.groovy, setup.cfg, tox.ini
https://clusterhq.atlassian.net/browse/FLOC-4105
See http://ci-live.clusterhq.com:8080/job/ClusterHQ-flocker/job/extract-lint-output-broken/job/run_lint/1/violations/ for a demonstration ([diff](https://github.com/ClusterHQ/flocker/compare/extract-lint-output-FLOC-4105...extract-lint-output-broken))
=> [FLOC-4105] Extract the lint output in a useful way.

admin/acceptance.py, flocker/provision/_aws.py, flocker/provision/_common.py, flocker/provision/_gce.py, flocker/provision/_libcloud.py
`IProvisioner.create_nodes()` is a new interface that allows to request multiple nodes at once.
The method returns a list of Deferreds with one Deferred for each requested node.
The implementations request multiple nodes from a platform at once if the platform permits (AWS)
or one by one if not (Rackspace). But in either case the waiting for nodes to become running and accessible is done in parallel and asynchronously.
=> [FLOC-3976 ] support for batch cloud provisioning

admin/cluster_setup.py
Commit https://github.com/ClusterHQ/flocker/commit/f72dd544395a4b9317f010962f369f01ac8d3c8b added an extra parameter to the function `get_trial_environment` to pass the package versions info to subsequent stages.  The  change is very useful for the benchmarking workflow, as we are currently passing the branch name manually.
However, for benchmarking, we call the `get_trial_environment` function from `cluster_setup.py`, but it has not been changed there.
This PR fixes that omission.
=> [FLOC-4111] Add package source to get_trial_environment parameters

benchmark/cluster_containers_setup.py
The `setup-cluster-containers` script should print a final status message before exiting. To do this it uses the `eliot_output` function which maps Eliot messages to display strings.
The final log message used `action_type` instead of `message_type`, so does not get mapped correctly.
Simple change to use correct attribute.
=> [FLOC-4110] Fix log message attribute so it gets displayed correctly.

admin/installer/_images.py, admin/installer/packer/provision_ubuntu-14.04_docker.sh, admin/installer/packer/template_ubuntu-14.04_docker.json, admin/test/test_images.py
Fixes: https://clusterhq.atlassian.net/browse/FLOC-3941
I also introduced some changes to allow the version to be supplied as an environment variable when calling the script.
And modified the integration test to check the tags when the images have built.
I'll follow up with a way to specify and tag the Docker package version in 
* https://clusterhq.atlassian.net/browse/FLOC-4102
* https://github.com/ClusterHQ/flocker/compare/choose-docker-version-FLOC-4102
=> [FLOC-3941] Pre-pull Docker Swarm when building the Docker image

admin/acceptance.py, admin/testbrew.py, benchmark/cluster_containers_setup.py, flocker/common/script.py, flocker/common/test/test_script.py
Fixes FLOC-4090. Removes the three separate definitions of `eliot_output` and refactors it in to one function inside `flocker.common.script`.
=> [FLOC-4090] Refactor eliot_output

CONTRIBUTING.rst, admin/release.py, build.yaml, docs/gettinginvolved/functional-testing.rst, docs/gettinginvolved/infrastructure/packaging.rst, flocker/testtools/_flaky.py, tox.ini
Fixes FLOC-4113. Explains that cloud backend tests must be run from an instance of the cloud provider and how to set up an instance to run the functional tests.
=> [FLOC-4113] Expand functional test set up docs

admin/cleanup.py, admin/cleanup_cloud_resources, docs/gettinginvolved/acceptance-testing.rst
Fixes: https://clusterhq.atlassian.net/browse/FLOC-4118
This is a port of the code from https://github.com/ClusterHQ/build.clusterhq.com/pull/109.
It's blocking at the moment, but in a follow up I can also port the Instance cleanup code and run instance and volume cleanup in parallel threads.
Next I'll add this to a jenkins cron job.
* https://clusterhq.atlassian.net/browse/FLOC-4119
=> [FLOC-4118] A command line tool to cleanup leaked acceptance test volumes

benchmark/script.py
The option allows to specify a log file to use.
The log file is appended to.
By default the log messages still go to `stderr`.
=> [FLOC-3758]  add --log-file option to the benchmark script

benchmark/benchmark.yml, docs/administering/debugging.rst, flocker/restapi/_infrastructure.py, flocker/restapi/test/test_infrastructure.py
Profiling shows that the JSON schema validation of control service API responses causes a large proportion of CPU load on the control service for clusters containing a large number of containers. See the comments for issue FLOC-4099 for some numbers.
This PR disables validation of the responses for contexts other than unit testing.
The principle being moved towards is to validate data when it arrives at the service and then to assume it is valid from there on, including on the way out.  This should be true if 1. all input data is validated, and 2. there are no bugs.
FLOC-4121 will review and, if required, update the situation for validating all input data, and validation for unit tests is kept to detect bugs.
In addition, I updated the `benchmark.yml` file defining the benchmark scenarios …
=> [FLOC-4099] Disable API response validation

docs/releasenotes/index.rst, flocker/control/schema/types.yml, flocker/control/test/test_schemas.py
The `maximum_size` property of datasets is an integer:
- The API docs text for `maximum_size` state it is an (optional) integer.
- The Dataset PClass in `flocker.apiclient` constrins it to an integer.
- No fractional value of bytes is valid (in fact only multiples of 1024 are valid).
However, the server-side JSON schema allows the type of `maximum_size` to be `number` which permits floats. The Dataset PClass on the server side does not constrain the type.  So, a float type is not detected as an error until it is passed back to the client, after the control service data is made invalid.
The test that should have detected this fails since the value tested did not meet a different constraint (multiple of 1024).
This PR fixes the test and the constraint to only allow integers.
=> [FLOC-3862] Do not accept floats for maximum size of a dataset

docs/installation/cluster-cleanup.rst, docs/installation/index.rst, docs/installation/installer-getstarted.rst, docs/installation/installer-tutorial.rst, docs/installation/installer.rst
Fixes 4103
Several commands were pre-fixed ``uft-``. This PR removes that. Additionally, there were 2 instances of recommending use of ``flocker-deploy``, which were removed.
=> [FLOC 4103] Remove all references to uft

admin/acceptance.py, admin/cluster_add_nodes.py, admin/cluster_setup.py, admin/test/test_cluster_setup.py, dev-requirements.txt, flocker/common/script.py
eliot_to_stdout moved and it's usage in e.g. cluster_setup.py wasn't caught as there were no tests of any kind for that. This PR:
- Updates cluster_setup.py and cluster_add_nodes.py to use eliot_to_stdout (via a convenience function)
- Patches eliot_to_stdout to be less verbose when used in the cluster scripts (this was done on the advice of dwgebler)
- Added a basic test for the options parsing. Note that I chose to introduce use of mock in order to get around the fact that the option parser was embedding quite a lot of logic to connect to the cloud provider.
=> [FLOC-4124] Patch cluster management scripts to use eliot_to_stdout

docs/flocker-features/flockerctl.rst
Fixes 4146
The flockerctl document had several references to the Labs installer, and some confusing text about other Flocker tools. This issue cleans that up.
=> [FLOC 4146] Clean up references on flockerctl documentation

flocker/control/schema/types.yml, flocker/control/test/test_schemas.py, flocker/dockerplugin/test/test_schemas.py, flocker/restapi/testtools.py
FLOC-3862 PR #2621 was an error in validation that occurred partly because the test that was supposed to fail due to the value being the wrong type actually failed due to the value not being a multiple of 1024.  Since the failures were not distinguished, the bug slipped through testing.
This PR separates the tests by expected validation error. This ensures that we are testing the correct failure reason. Using this new code, the FLOC-3862 test was evidently in the wrong section.
In addition, we now have some tests which actually have multiple validation errors, but with the new structure, we can see that they are failing for the desired reason. https://github.com/ClusterHQ/flocker/blob/81dfb8d68964608e11f188e5d45812ae29c18a30/flocker/control/test/test_schemas.py#L90-L97 is an example. The …
=> [FLOC-4145] Test type of JSON schema validation errors

benchmark/metrics-parser, benchmark/metrics_parser.py, benchmark/test/test_metrics_parser.py
This changes adds a script which can be used to convert JSON results from the benchmarking tool to a set of CSV files which summarise the results. This script outputs a CSV file for each different scenario and each file contains all the results that were obtained for that scenario. The results in the file are divided by number of nodes that were used in the cluster and the number of containers started in that cluster.
This script is unfortunately not very neat or clear to read so I expect that a number of changes will need to be made :smile: The approach I took was to flatten each set of results to separate each sample that was collected. The results are then filtered and combined again before being written CSV.
=> [FLOC-3974] Convert JSON benchmarking files to CSV

benchmark/metrics/__init__.py, benchmark/metrics/test/test_cputime.py, benchmark/operations/__init__.py, benchmark/operations/test/test_read_request.py, benchmark/scenarios/__init__.py, benchmark/scenarios/_request_load.py, benchmark/scenarios/test/test_read_request_load.py, benchmark/scenarios/test/test_write_request_load.py, benchmark/submit.py, benchmark/test/test_driver.py, build.yaml, tox.ini
This PR adds the `benchmark` directory to the lint tests.
Code in the directory was changed to pass the lint tests.  Most were stylistic issues, but there was one bug where the variable `t0` was used in a closure within a loop, meaning that some elapsed time measurements may have been shorter than the actual time taken, probably by a fraction of a second.
=> [FLOC-3922] Lint benchmark directory

build.yaml
Change all builds to use the same sized instance (medium) on AWS.
The belief is a homogeneous environment should give us
- greater reuse of provisioned slaves
- faster builds 
https://clusterhq.atlassian.net/browse/FLOC-4167
=> [FLOC-4167] build all AWS flocker jobs on medium instances 

docs/reference/api.rst
Fixes 3600
@itamarst identified some key information missing from our API documentation. This PR adds it, in the same format as was originally documented in the issue (I thought this was the simplest way to present this information)
When reviewing please let me know if this could be expanded to help users understand this addition.
I also fixed the following header, which did not use title case.
=> [FLOC 3600] Add "Communicating with the API" section to API doc

benchmark/metrics/cputime.py, benchmark/metrics/test/test_cputime.py
The CPU time command used for benchmarking requires that at least one of the named processes exist, in order to distinguish an error result from an empty result.
The code uses `ps` for this extra process name, due to the command actually calling `ps`.  However, it has been observed that under heavy load (which is often seen in the benchmarks), the short-lived `ps` process doesn't see itself.  This causes a `KeyError` when we try to remove the unwanted `ps` data.
This PR uses the name of the init process (process 1) on each node instead, which should be more robust.
=> [FLOC-4177] Fix cputime error under load

admin/installer/cloudformation.py, flocker/acceptance/endtoend/test_installer.py
Reverts ClusterHQ/flocker#2638
There's a bug in the new template which means that the S3 policy value is used for the AWS secret access key.
=> Revert "[FLOC-4086] Warn users about needing access to S3 buckets during CloudFormation"

admin/installer/cloudformation.py, flocker/acceptance/endtoend/test_installer.py
Fixes: https://clusterhq.atlassian.net/browse/FLOC-4086
Based on #2638 with a bug fix.
If user's AWS account does not have a Policy that allows him/her to access S3 buckets, CloudFormation stack creation fails. Instead of wasting user's time and EC2 resources, it would be better to have user check a box during CloudFormation workflow confirming S3 access.
This PR also includes an unrelated change where user is allowed to choose from existing KeyPairs instead of typing in the name of the KeyPair.
=> [FLOC-4086] Warn users about needing access to S3 buckets during CloudFormation

admin/cleanup.py, admin/cleanup_cloud_resources, admin/publish-installer-images, build.yaml
Fixes: https://clusterhq.atlassian.net/browse/FLOC-4155
I've ported the code from build.clusterhq.com with a few modifications:
* I got rid of the ``deferToThread`` -- the operations are no longer asynchronous. @sarum90 and I discussed it and decided that it would be more straight forward and easier to maintain if the delete operations we're performed in sequence. In the future we could speed things up by running parallel cleanup operations for each cloud provider and each region. It's important that the nodes are destroyed before the volumes though.
* I was tempted to rewrite it as Effects and performers but decided that that can be done in a followup issue.
* I was also tempted to add Eliot logging to each of the actions, but  in the interests of keeping the branch small, I can do that …
=> [FLOC-4155] Cleanup leaked cloud instances from jenkins

docs/kubernetes-integration/index.rst
Fixes 4065
The CTA on the Kubernetes tutorial button wasn't clear that the tutorial was provided by Kubernetes. The wording on the button, and the intro have been amended to be clearer.
=> [FLOC 4065] Reword the CTA on the Kubernetes tutorial

docs/releasenotes/index.rst
Fixes: https://clusterhq.atlassian.net/browse/FLOC-4189
Merging 1.10.3.dev1 back into master.
See also: #2646
=> [FLOC-4189] Merge release 1.10.3.dev1

docs/releasenotes/index.rst
Fixes: https://clusterhq.atlassian.net/browse/FLOC-4189
I couldn't find any note worthy changes so I just updated the heading and moved the last release down.
The process states that I should wait for green builds, but it's taking ages so I may as well get approval of the release notes changes.
I'm still waiting for test results:
* http://ci-live.clusterhq.com:8080/job/ClusterHQ-flocker/view/releases/job/release-release-flocker-1.10.3.dev1/
Meanwhile I've fixed a bug in the ``initialize-release`` tool:
* https://clusterhq.atlassian.net/browse/FLOC-4190
=> [FLOC-4189] Release Flocker-1.10.3.dev1

docs/releasenotes/index.rst, flocker/acceptance/endtoend/test_diagnostics.py, flocker/acceptance/integration/testtools.py, flocker/acceptance/node_scripts/disable_service.py, flocker/acceptance/node_scripts/service_running.py, flocker/acceptance/obsolete/test_cli.py, flocker/acceptance/obsolete/test_containers.py, flocker/acceptance/testtools.py, flocker/node/_deploy.py, flocker/node/agents/blockdevice.py, flocker/node/agents/test/test_blockdevice.py, flocker/provision/_aws.py
Currently the container agent is required, even if one is not using Flocker's container API. This uses resources (CPU, disk, RAM) without offering any benefit. In the medium term we want to remove the agent completely, but for now it would be good to simply allow people to disable it.
The way to do that is to make sure the dataset agent no longer requires the container agent be running in order to operate. This means that if the container agent becomes unresponsive somehow for more than two minutes and a container is still using a dataset we might end up moving a dataset that is still in use. In practice this is unlikely to happen due to fact one can't unmount a filesystem that is in use, so allowing this edge case seems reasonable.
This issue does not cover documentation changes to make …
=> [FLOC-3602] Design sketch: make the container agent optional.

flocker/node/agents/functional/test_gce.py, flocker/node/agents/gce.py, flocker/provision/_gce.py
Refactors the provisioner so that it can be used by code that does not need to log into the instance. Adds a new test to the GCE functional tests that actually spins up a second instance and attaches a volume to that instance just to verify the exception raised by the BlockDeviceAPI.
There are other tests that will also use this infrastructure forthcoming.
=> [FLOC-4194] Add GCE functional test that verifies the attached to other node exception.

admin/cleanup.py, dev-requirements.txt
Fixes: https://clusterhq.atlassian.net/browse/FLOC-4188
I originally thought that the script should ignore volumes that are attached to nodes that it has decided to keep.
Instead, I've it's far simpler to only attempt to delete volumes that are available.
This should prevent the script attempting to delete volumes that are attached to non-buildbot / jenkins acceptance test nodes.
It should also prevent the errors that we see when it attempts to delete volumes that are in other transient states....eg detaching as we can see in these build results
http://ci-live.clusterhq.com:8080/job/ClusterHQ-flocker/view/master/job/master/job/_cleanup_cloud_resources/10/artifact/cleanup_cloud_resources.stderr/*view*/
```
Destroying resource.
Traceback (most recent call last):
File …
```
=> [FLOC-4188] Only cleanup available volumes

admin/test/test_installer.py, build.yaml, flocker/acceptance/endtoend/test_diagnostics.py, flocker/acceptance/testtools.py, flocker/common/functional/test_runner.py, flocker/common/runner.py, flocker/common/test/test_runner.py
Fixes: https://clusterhq.atlassian.net/browse/FLOC-4200
* Added a new ``upload`` function based on the existing ``flocker.common.runner.download`` 
* Refactored that function to share a common scp function.
* Added a new error case for parsing SCPs `lost connection` error message into an Exception that we can catch from the retry helpers.
=> [FLOC-4200] Retry scp operations in test_installer

flocker/provision/_gce.py
Once on master the first sudo to a CentOS GCE machine failed for 30 seconds claiming that you cannot sudo if you don't have a tty. This is consistent with the google init script that comes in from metadata (userData for you AWS folks) taking a long time to run (This is where we turn on sudo from non-tty).
In no other run was this even needed to retry once, so there would be fair criticism that this might not fix the problem.
However, it is cheaper than launching a deeper investigation (even improving logging would be a bit tricky), and it is a bug in provisioning code, not production code, so I wanted to try this and then wait to see if the error repeated itself.
=> [FLOC-4164] Increase retry of first run of sudo on GCE instances

docs/gettinginvolved/plugins/building-driver.rst, flocker/node/script.py, flocker/node/test/test_script.py
https://clusterhq.atlassian.net/browse/FLOC-4237
This also makes it require unicode. I don't think anybody has started using this.
=> [FLOC-4327] Use `PSet` for `required_config` in `BackendDescription`

flocker/node/agents/blockdevice.py, flocker/node/agents/functional/test_gce.py, flocker/node/agents/gce.py
Implement the ICloudAPI in the GCE IBlockDeviceAPI.
Also, actually test all of the endpoints at the functional level.
The GCE functional tests now are considerably slower to run since they actually spin up 2nd instances for some tests.  Since they are only run nightly on Jenkins this seemed reasonable.
=> [FLOC-3829] Have the GCE driver implement ICloudAPI

admin/ami-search-ubuntu, admin/ubuntu.py
Fixes: https://clusterhq.atlassian.net/browse/FLOC-4257
This is part of our effort to update CloudFormation templates during Flocker releases.
You can read our draft docs in #2672 outlining a rather manual process which calls this tool as a first step. Later it can be automated.
This PR is one way to get the AMI IDs.
It seemed like it might be simpler and more correct to directly to Ubuntu.com as the source of truth, but it wasn't as easy as i thought since there are no APIs just text files and something called `simplestreams` which turned out to be unusably slow.
* http://discourse.ubuntu.com/t/which-ami-in-aws-does-correspond-to-ubuntu-14-04-2/2195/2
The alternative is to query the AWS API for images belonging to owner `099720109477` and sort by date:
* …
=> [FLOC-4257] A tool to print the latest official regional AMI IDs for Ubuntu

flocker/acceptance/testtools.py, flocker/common/plugin.py, flocker/common/test/test_plugin.py, flocker/node/__init__.py, flocker/node/backends.py, flocker/node/script.py, flocker/node/test/test_script.py
https://clusterhq.atlassian.net/browse/FLOC-4245
=> [FLOC-4245] Factor out plugin loading.

flocker/node/_p2p.py, flocker/node/test/test_p2p.py
https://clusterhq.atlassian.net/browse/FLOC-4271
This is a follow up to #2272 for the obsolete ZFS backend.
I'm doing this so I can test the code-paths for provisioning hooks with in-tree code.
=> [FLOC-4271] Make the P2P deployer not require the container agent running.

docs/gettinginvolved/functional-testing.rst, docs/spelling_wordlist.txt, flocker/node/agents/functional/test_cinder.py, flocker/node/agents/functional/test_cinder_behaviour.py
Fixes: https://clusterhq.atlassian.net/browse/FLOC-4274
I also had to modify some of the tests that were still using `REALISTIC_BLOCKDEVICE_SIZE` .
All Cinder functional test now pass:
```
(flocker)[centos@centos7-1 flocker]$ sudo /usr/bin/env FLOCKER_FUNCTIONAL_TEST=TRUE FLOCKER_FUNCTIONAL_TEST_CLOUD_CONFIG_FILE=$PWD/acceptance.yml FLOCKER_FUNCTIONAL_TEST_CLOUD_PROVIDER=devstack-openstack $(type -p trial) --testmodule $PWD/flocker/node/agents/cinder.py
flocker.node.agents.functional.test_cinder
BlockDeviceAPIDestroyTests
test_destroy_timesout ...                                              [OK]
CinderAttachmentTests
test_get_device_path_no_attached_disks ...                             [OK]
CinderBlockDeviceAPIInterfaceTests
test_attach_attached_volume ... …
```
=> [FLOC-4274] Document how to run Cinder functional tests on Devstack

admin/installer/_images.py, admin/test/test_images.py, docs/gettinginvolved/infrastructure/maintaining-cloudformation.rst
Fixes: https://clusterhq.atlassian.net/browse/FLOC-4281
Publishing to S3 is unnecessary complication.
I've removed all that code and replaced with printing the AMI map to stdout.
We're aiming for a process that looks something like this: #2672
Here's a sample output
```
(4281)(print-image-ids-FLOC-4281 ? =)[~/.../HybridLogic/flocker]$ DOCKER_VERSION=1.10.0       SWARM_VERSION=1.1.3       ./admin/publish-installer-images         --template=docker 2>stderr.log | tee stdout.log
{"us-west-1": "ami-916b18f1"}
(4281)(print-image-ids-FLOC-4281 ? =)[~/.../HybridLogic/flocker]$ jq . stdout.log 
{
"us-west-1": "ami-916b18f1"
}
```
=> [FLOC-4281] publish-installer-images now prints image ID map

AUTHORS.rst, flocker/node/_p2p.py, flocker/node/test/test_p2p.py
Fixes: https://clusterhq.atlassian.net/browse/FLOC-4299
Based on https://github.com/ClusterHQ/flocker/pull/2685 by @zhenghc (Thank you).
With an additional test which in turn revealed a bug in the calculation of DeleteDataset changes.
=> [FLOC-4299] Ignore deleted datasets once they've been deleted

docs/docker-integration/cloudformation.rst
Fixes 4286
Following feedback from the designers, this splits the long title on the CloudFormation doc into a main header and sub header.
=> Split title on CloudFormation document [FLOC 4286]

flocker/acceptance/endtoend/test_diagnostics.py
We do not fully support the container agent anymore (and haven't for awhile),
so it is unlikely that we would even fix a bug identified by the container
agent's logs. Also, now that we start and stop the container agent a lot, there
appears to be some race conditions where the logs from the container agent are
not collected by flocker-diagnostics, ~~potentially because the container agent~~
~~has not logged it's first line of output~~ **because it is not yet reported by `initctl`**
by the time we run flocker-diagnostics.
Rather than diving in the deep end and figuring out the root cause of these
flakes, just allow the test to pass even if the container agent logs are
missing, since their presence adds little value.
=> [FLOC-4300] Centos gce container agent fix floc 4300

docs/docker-integration/cloudformation.rst
Fixes 4287
This adds a button to the 1st step in the CloudFormation instructions. The wording for the first substep has also been amended to remove the link to AWS.
Note - this is a step change as part of FLOC 4285. The next change is to add a new screenshot in step 1.1 to show users where to locate the AWS region.
=> [FLOC 4287] Add a button to open AWS in CloudFormation doc

docs/releasenotes/index.rst, requirements.txt
This fixes installing on OSX which is currently broken on El Capitan.
Verified fix manually in a VirtualBox VM on my machine. (Built an sdist, uploaded it to S3, made a new tap ruby file, uploaded that to S3, installed using brew from that file).
I do not know why the automated OSX builder did not catch this. If I was crossing all of my t's and dotting all of my i's I would look into it, but I think that's probably lower priority than getting the fix in (and some of the other work I'm working on presently).
=> [FLOC-3404] Update cffi and cryptography dependencies

flocker/acceptance/testtools.py, flocker/node/agents/gce.py
In reviewing logs, @justnoise and I noticed that we had some concurrent GCE requests that appeared to come back mangled (or hang abnormally long).
The GCE python bindings are based on httplib2, which is not threadsafe, so we either need to create 1 backend per thread or add some other serialization method.  To me it seemed most simple to just add a mutex around all calls to the GCE API.
I'm still debugging some failures that I'm seeing in the acceptance tests, but it seems as if this change does not make thing worse, so I consider this ready for review.
=> [FLOC-4309] Gce blockdevice threadsafe.

docs/kubernetes-integration/about.rst, docs/kubernetes-integration/index.rst
Fixes 4306
The URL for the Kubernetes Flocker information has changed from:
`http://kubernetes.io/v1.1/examples/flocker/`
to
`http://kubernetes.io/docs/user-guide/volumes/#flocker`
=> [FLOC 4306] fix broken link

admin/test/test_installer.py
Increase COMPOSE_HTTP_TIMEOUT for CloudFormation installer tests from default of 60 seconds to 360 seconds. This addresses intermittent test failures due to 60 second timeout being hit 18% of nightly runs on master over 30 day period.
________
COMPOSE_HTTP_TIMEOUT defintion (from https://docs.docker.com/compose/reference/envvars/ ):
Configures the time (in seconds) a request to the Docker daemon is allowed to hang before Compose considers it failed. Defaults to 60 seconds.
________
Verification: 5 out of 5 runs passed (http://ci-live.clusterhq.com:8080/job/ClusterHQ-flocker/job/set-docker-client-timeout-FLOC-4183/job/_run_admin_test_test_installer/).
Run #1: http://ci-live.clusterhq.com:8080/job/ClusterHQ-flocker/job/set-docker-client-timeout-FLOC-4183/job/_run_admin_test_test_installer/la …
=> [FLOC-4183] Increase COMPOSE_HTTP_TIMEOUT for installer tests.

flocker/acceptance/endtoend/test_dataset.py, flocker/acceptance/endtoend/test_dockerplugin.py, flocker/acceptance/obsolete/test_containers.py, flocker/acceptance/testtools.py, flocker/testtools/__init__.py
GCE unfortunately can be very slow at doing volume operations (specifically attach and detach) (O(90 seconds)). Most of our tests have to do 2 operations in series (First they have to delete old volumes, then the have to create a volume for their own test). Thus, it sort of makes sense to me to have a much larger default timeout on our acceptance tests (I had been going through 1 by 1 and identified tests that needed a longer timeout experimentally, but after seeing 1 test that had an 80 second detach in cleanup followed by a 70 second attach in the actual test itself, it seems like this will be a quicker solution.)
Decided to make the change in three places:
1) test_dataset
2) test_container
3) test_dockerplugin
removed old timeout extensions that were less than 5 minutes.
=> [FLOC-4310] Increase all acceptance test timeouts.

docs/_themes/clusterhq/static/css/docs.css, docs/index.rst
Fixes 4091
Adds new titles to both the section headers, and the buttons - this ensures the user is funnelling down into more specific information as they click into the docs.
=> [FLOC 4091] Update the CTA information on the docs homepage

flocker/provision/_aws.py, flocker/provision/_gce.py, flocker/provision/_install.py, flocker/provision/_ssh/_conch.py
This is the first in a set of two PRs that'll allow the acceptance tests to run as the default user.  Running acceptance tests without a tty cause flakes on rackspace.  Running the tests as the root user requires us to modify the root account and sshd.  This has slowed down development on GCE.
In the future these changes will be used to allow the provisioning code to be reused to build a better flocker installer.
=> Acceptance Test Provisioner: SSH Client spawns a tty

flocker/__init__.py
Fixes: https://clusterhq.atlassian.net/browse/FLOC-4330
I started some parallel builds to see if we can trigger the segfault:
* http://ci-live.clusterhq.com:8080/job/ClusterHQ-flocker/job/re-enable-pyrsistent-c-extension-FLOC-4330-parallel-testing-1
* http://ci-live.clusterhq.com:8080/job/ClusterHQ-flocker/job/re-enable-pyrsistent-c-extension-FLOC-4330-parallel-testing-2
* http://ci-live.clusterhq.com:8080/job/ClusterHQ-flocker/job/re-enable-pyrsistent-c-extension-FLOC-4330-parallel-testing-3
* http://ci-live.clusterhq.com:8080/job/ClusterHQ-flocker/job/re-enable-pyrsistent-c-extension-FLOC-4330-parallel-testing-4
* http://ci-live.clusterhq.com:8080/job/ClusterHQ-flocker/job/re-enable-pyrsistent-c-extension-FLOC-4330-parallel-testing-5
See also:
* #1891 (the PR where we disabled the C …
=> [FLOC-4330] Re-enable the Pyrsistent C extension

flocker/node/_loop.py, flocker/node/test/test_loop.py
Fixes: https://clusterhq.atlassian.net/browse/FLOC-4326
Copied from #2720 with some additional test fixes.
=> [FLOC-4326] Do not log configuration and deployment state during CONVERGE

flocker/node/agents/blockdevice.py, flocker/node/agents/test/test_blockdevice.py, flocker/node/testtools.py
Fixes: https://clusterhq.atlassian.net/browse/FLOC-4328
Copied from #2720 with a test.
It took me ages to figure out that the problem was only occurring when the deleted dataset had been attached to some other volume.
For now I've modified one of the existing tests. Perhaps this case deserves a separate test though.
=> [FLOC-4328] Don't wake up for datasets that have been deleted on other nodes

flocker/control/_persistence.py
This modifies our JSON serialization to not use the JSONEncoder scheme, and instead turns the entire Pyrsistent object into something that is serializable outside of the realm of the JSONEncoder.
This enabled us to be able to add a cache that stores the values of the encoding at the subtree level, which should lead to great speedups when serializing the configuration or the state inside flocker.
=> [FLOC-4324] Caching json serialization

flocker/common/script.py, flocker/control/script.py, flocker/node/script.py
Fixes: [FLOC-3142](https://clusterhq.atlassian.net/browse/FLOC-3142)
This changes moves the code added for [FLOC-3039](https://clusterhq.atlassian.net/browse/FLOC-3039) and allows it to be used by other flocker services.
Sending `SIGUSR1` and `SIGUSR2` to a flocker service results in a profile dump being written to `/var/lib/flocker`. The profile files are named according to which service they correspond to, one of `control`, `dataset`, or `container`.
=> [FLOC-3142] Enable profiling of agent services.

admin/packaging.py, admin/test/test_packaging.py, build.yaml, docs/gettinginvolved/client-testing.rst, docs/gettinginvolved/functional-testing.rst, docs/gettinginvolved/infrastructure/packaging.rst, flocker/control/_persistence.py, flocker/node/script.py, requirements.txt, setup.py, tox.ini
This allows us to use a forked version
of Pyrsistent. Currently, it points
to a CHQ fork that has nothing in it
but a "forking stamp". This should be
updated to a hash that has the speed-ups
we need.
=> Use forked version of Pyrsistent

docs/gettinginvolved/cluster-setup.rst, flocker/node/agents/gce.py, flocker/provision/_gce.py
Fixes: https://clusterhq.atlassian.net/browse/FLOC-4323
This puts GCE the rest of the way into our provisioning code so you can now quickly spin up instances in parallel.
The approach was to pull out code that could be re-used from the GCE provisioner, and add an async version of wait_for_operation. The API calls to GCE are still syncronous, but we wait in parallel for the nodes to be brought up.
=> [FLOC-4323] Gce benchmarking

requirements.txt
Now that we have a mechanism to use our own fork of pyrsistent, this is the commit to use the latest hash of master.
By policy this hash matches exactly a valid hash from ClusterHQ/pyrsistent/master, specifically:
https://github.com/ClusterHQ/pyrsistent/commit/5b722c3ad75ed2da414a40e6d27af373a8610018
=> [FLOC-4336] Update pyrsistent to a version with __eq__ and __hash__ optimizations

flocker/control/httpapi.py
In order to speed up response times from the control agent, this PR adds a simple cache to be used in the case where the deployment state or configuration has not changed since the last time it was requested over the API.
Note: This assumes that the callers of the caching functions are well-behaved and don't mutate the values they receive. If they mutate the values they receive they will be mutating the value in the cache. I believe this is true, and that it is fairly easy to reason about it being true in the future.
=> [FLOC-4334] Cache flocker-control responses.

flocker/testtools/_base.py
Fixes: https://clusterhq.atlassian.net/browse/FLOC-4335
=> [FLOC-4335] Only report log lines that have both timestamp and task_uuid

requirements.txt
New version we are using:
https://github.com/ClusterHQ/pyrsistent/commit/80ecd8da51ea3f7b4aff3451e6abe9a61fc1c44b
=> [FLOC-4353] Update to the latest pyrsistent.

docs/mesos-integration/index.rst
Fixes 4166
Corrects some UX issues highlighted in 4166. This includes removing the tutorial title, as we don't provide a mesos tutorial, and adding a CTA for launching the Mesos/Flocker isolator.
=> [FLOC 4166] update mesos page with better CTAs

docs/docker-integration/install-client.rst, docs/docker-integration/install-node.rst, docs/flocker-standalone/enabling-agent-service.rst, docs/flocker-standalone/install-client.rst, docs/flocker-standalone/install-node.rst, docs/installation/enabling-agent-service.rst, docs/installation/enabling-control-service.rst, docs/installation/install-client.rst, docs/installation/install-node.rst, docs/kubernetes-integration/enabling-agent-service.rst, docs/kubernetes-integration/install-client.rst, docs/kubernetes-integration/install-node.rst
Add documentation for installing flocker node and flocker cli on RHEL 7.2. Relevant sections start at http://clusterhq-staging-docs.s3-website-us-east-1.amazonaws.com/add-rhel-documentation-FLOC-4255/docker-integration/manual-install.html
Setting up RHEL CI environment will follow this PR.
=> [FLOC-4255] Add documentation for Flocker deploy on RHEL 7.2

docs/supported/index.rst
Fixes 4361
This moves RHEL before the experimental CentOS box, and removes the coming soon label.
It was noted during this work that the CTA on the supported platform links (to Learn More) directs the user to a rather unhelpful homepage destination. This has been raised as a bug (FLOC 4362)
=> [FLOC 4361] Update the label on the Supported Platforms/RHEL box 

docs/releasenotes/index.rst
Fixes: https://clusterhq.atlassian.net/browse/FLOC-4358
See: http://doc-dev.clusterhq.com/gettinginvolved/infrastructure/release-process.html#pre-tag-review-process
=> [FLOC-4358] Release Flocker 1.11.0

flocker/acceptance/testtools.py
If you don't restart the dataset agent after you reboot a node, flocker doesn't work on CentOS on Rackspace.
I did not root-cause the issue.
Should we root-cause it rather than working around it? Should we open a new FLOC to root cause, but in the meantime merge this so that we can test for other regressions? These are the questions I leave for the reviewer.
=> [FLOC-4364] Restart the dataset agent after we reboot a node.

flocker/acceptance/endtoend/test_benchmark.py, flocker/acceptance/endtoend/test_diagnostics.py, flocker/acceptance/integration/test_platform.py
Now that we restart the nodes every time we toggle running the container agent or not, our tests take a lot longer to run.
Thus, we should increase all acceptance test timeouts rather than just the ones that GCE was slow on.
=> [FLOC-4363] Increase other acceptance test timeouts

flocker/apiclient/test/test_client.py, flocker/restapi/_infrastructure.py, flocker/restapi/_logging.py, flocker/restapi/test/test_infrastructure.py
Flocker had a lot of nested logging on API requests. This drives CPU usage higher than it should be for high numbers of requests per second.
Removing one of these layers in an attempt to reduce CPU usage.
After spinning up 2 15 node clusters, one with this change and one without this change, I observed the following when I ran the 10 QPS read benchmark:
Without this PR:
flocker-control CPU: 25%
With this PR:
flocker-control CPU: 23%
This was on ubuntu rather than CentOS, but now that we neutered the JSON logs, it seems to me that these are adding no value, and getting the extra 2 percent back is sort of a big deal.
=> [FLOC-4357] Removed one of the points of logging

flocker/node/agents/functional/test_cinder.py
Fixes: https://clusterhq.atlassian.net/browse/FLOC-4368
Stacked on #2752
These tests were using region dependent, but needn't be.
Instead they now only create a keystone session, which is not tied to a region.
The tests were also broken, in so far as the "rackspace" keystone auth driver doesn't support the peer_verify or peer_ca_path options. 
I now skip the tests unless the driver supports those options.
=> [FLOC-4368] Simpler Cinder HTTPs tests

docs/reference/deprecated_api.rst, docs/supported/flockercontainers.rst
Fixes 4367
This updates this doc with a new Docker Hub link for the Docker Plugin, specifies that the Container agent is deprecated, and updates the start the plugin command (step 3)
=> [FLOC 4367] Update the flockercontainers.rst document

flocker/common/logging.py, flocker/common/test/test_logging.py, flocker/node/_loop.py
We turned a lot of logging off in order to meet Swisscom benchmarking requirements.
This turns back on only the node configuration log in the agents during convergence.
The bad news is that this does log all datasets that this node has deleted (since the beginning of time). Although from preliminary benchmarking the additional CPU usage of adding this logging back is negligible (spun up 280 containers on 20 nodes with and without this PR, and couldn't see any real difference in CPU usage with the write benchmark). Although, it is probably worth mentioning that from master I was able to delete all of them all at once, whereas with this  PR I started to get timeout errors.
Nevertheless this PR will make our acceptance tests diagnosable once more.
=> [FLOC-4331] Restore some logging

build.yaml
Fixes: https://clusterhq.atlassian.net/browse/FLOC-4376
The Ubuntu 15.10 `pip` works (with the Ubuntu packaged python-requests) until you use it to install a newer version of requests, which no longer has the required `from requests.compat import IncompleteRead` API.
See:
* https://bugs.launchpad.net/ubuntu/+source/python-pip/+bug/1306991/comments/47
My solution is to install the latest version of Pip in the package build images and never install the Ubuntu or Centos packaged `pip`.
We should probably do the same in the Jenkins slave images...except there, we'd need to install the latest version of virtualenv in order to get the latest version of pip for the slaves to install Flocker during tests.
Note that since building and pushing `clusterhqci/fpm-ubuntu-wily` here: 
* …
=> [FLOC-4376] Fix client on Ubuntu Wily tests

flocker/node/benchmark.py, flocker/node/diagnostics.py, flocker/node/test/test_diagnostics.py
Fixes: https://clusterhq.atlassian.net/browse/FLOC-4381
The problem is described here:
* https://bugs.launchpad.net/ubuntu/+source/lshw/+bug/1405873
The output is broken in various ways so doesn't seem worth attempting to fix it up.
* http://www.ezix.org/project/query?status=assigned&status=new&status=reopened&component=lshw&description=~json&order=priority
I'm also not convinced that we need to restrict the information output by the tool. 
It's probably easier to extract the information we need before it gets recorded in the benchmark results database....if we ever get around to deploying that.
I guess it may already be deployed somewhere but I don't know how to access it:
* https://github.com/ClusterHQ/benchmark-server
Any ideas @avg-I ?
=> [FLOC-4381] Work around the broken lshw encoder in flocker-benchmark hardware-report

flocker/acceptance/obsolete/test_containers.py
Fixes: https://clusterhq.atlassian.net/browse/FLOC-4379
I'm going to trigger a bunch of builds to verify that this fixes the test and to get an idea of how long they actually take.
* http://ci-live.clusterhq.com:8080/job/ClusterHQ-flocker/job/reboot-test-timeout-1/job/_run_acceptance_on_AWS_CentOS_7_with_EBS/
* http://ci-live.clusterhq.com:8080/job/ClusterHQ-flocker/job/reboot-test-timeout-2/job/_run_acceptance_on_AWS_CentOS_7_with_EBS/
* http://ci-live.clusterhq.com:8080/job/ClusterHQ-flocker/job/reboot-test-timeout-3/job/_run_acceptance_on_AWS_CentOS_7_with_EBS/
* http://ci-live.clusterhq.com:8080/job/ClusterHQ-flocker/job/reboot-test-timeout-4/job/_run_acceptance_on_AWS_CentOS_7_with_EBS/
* http://ci-live.clusterhq.com:8080/job/ClusterHQ-flocker/job/reboot-test-timeout-5/job/_run_accept …
=> [FLOC-4379] Allow more time for the stateful container reboot test

admin/packaging.py
Fixes: https://clusterhq.atlassian.net/browse/FLOC-4383
I think these warnings may have started appearing since we upgraded to pip 8.1.1 which is able to install `manylinux` wheel files.
And the `msgpack` `manylinux` wheel files are not  compiled with the CC and LDFLAGs that are expected for debian binaries (`dpkg-buildflags --export`)
This should allow the packages to be built:
* http://build.clusterhq.com/boxes-flocker?branch=lintian-FLOC-4383
And the acceptance tests to *run*:
* http://ci-live.clusterhq.com:8080/job/ClusterHQ-flocker/job/lintian-FLOC-4383/view/cron/
They may not pass until #2771 gets merged.
I merged this branch into #2771 and re-ran the Ubuntu acceptance tests:
* http://ci-live.clusterhq.com:8080/job/ClusterHQ-flocker/job/lsblk-FLOC-4382/view/cron/
Those *should* all …
=> [FLOC-4383] Ignore lintian hardening-no-relro warnings

flocker/acceptance/endtoend/test_dockerplugin.py, flocker/acceptance/scripts/lsblkhttp.py
Fixes: https://clusterhq.atlassian.net/browse/FLOC-4382
The `docker volume create` API returns immediately and the `docker create --volume-plugin=flocker ...`  && `docker start` APIs don't wait for the *existing* flocker volume to be mounted before starting the container.
The test has been failing since 2016-04-12....around the time of the Docker 1.11.0 release so perhaps that's a change in Docker behaviour.
* http://ci-live.clusterhq.com:8080/job/ClusterHQ-flocker/view/master/job/master/view/cron/job/_run_acceptance_on_AWS_CentOS_7_with_EBS/lastCompletedBuild/testReport/flocker.acceptance.endtoend.test_dockerplugin/DockerPluginTests/test_create_sized_volume_with_v2_plugin_api/
```
Failing for the past 12 builds (Since Failed#120 )
Took 8 ms.
```
And build #120 was for revision …
=> [FLOC-4382] Docker plugin tests now wait for test volumes to be mounted

flocker/control/_persistence.py, requirements.txt
In profiling the control agent I got to a point where it was clear that using a secure hashing function to attempt to uniquely identify a configuration was consuming a significant amount of our time. This specifically happens in workloads with a lot of configuration changes (like deleting all datasets at the end of a benchmarking run). These might not be particularly relevant workloads in the real world, but one could make an argument that since the flocker control node requires making individual requests for creating or deleting datasets there are situations where this should be faster; if anyone wants to delete N disks, they have to make N requests in quick succession.
Given that our specific use case does not require that the hash be cryptographically secure, we can get a lot of CPU …
=> [FLOC-4398] use murmur hash instead of sha

flocker/control/_persistence.py
`bool(key in dict)` is one lookup in the dictionary, and `dict[key]` is another lookup.  We have already determined that looking up a large PClass in a dict is a slow operation, so we should avoid that. Using `dict.get` and then checking for None (or using `try...except IndexError`) should eliminate one of the checks.
=> [FLOC-4399] Only lookup the value once in the cache.

flocker/provision/_gce.py
This is a change that I've done locally for all of the benchmarking clusters that I've run. Decided it was probably safe to push to master and it puts GCE at par with the AWS instances that we spin up for tests.
On AWS we have the default set to m3.large, which is 2 CPU and 7.5 GiB of RAM. The n1-standard-2 on GCE is the equivalent machine. The n1-standard-1 was chosen previously because I incorrectly thought that flocker should never use more than 1 CPU. Turns out the control node on large clusters easily consumes an entire CPU and then some, and we need the spare for the agents and the journalctl daemon.
=> [FLOC-4400] Change the default machine size in GCE tests.

flocker/control/_protocol.py, flocker/control/test/test_protocol.py
This PR makes it so that the control node will only ever send updates to nodes once every second even when it is recovering from a delayed update for a node that took awhile to acknowledge the original update.
=> [FLOC-4397] Amortize updates some more

build.yaml
Fixes: https://clusterhq.atlassian.net/browse/FLOC-4405
I decided to stop using devpi.clusterhq.com for the following reasons:
* It seems to be incompatible with pip 8.1.2 and manylinux wheel files
* It's a maintenance headache
* It is not configured securely.
With manylinux wheel files now on PyPI, we may even speed up the builds by going direct to PyPI and hopefully the cloud providers will provide their own transparent Python package caches.
Let's see.
=> [FLOC-4405] Stop using  devpi.clusterhq.com

flocker/restapi/docs/publicapi.py, requirements/admin.txt, requirements/flocker-dev.txt, requirements/flocker.txt
Fixes: https://clusterhq.atlassian.net/browse/FLOC-4425
Upgraded to virtualenv-15.0.2
* https://virtualenv.pypa.io/en/latest/changes/#id1
Which has the latest version of pkg_resources (vendored into setuptools) which is able to parse the so called environment markers in package version strings e.g.
``nomenclature >= "0.1.0"; sys_platform == "linux2"``
=> [FLOC-4425] Upgrade virtualenv package requirement

flocker/control/_protocol.py
In profiling I discovered that there is a specific pyrsistent.transform call that takes quite a bit of time.
I have reason to believe that a simple guard might assist in speeding up some of the performance.
=> [FLOC-4428] Guard against a pyrsistent.tranform call.

docs/spelling_wordlist.txt
Fixes: https://clusterhq.atlassian.net/browse/FLOC-4443
* http://ci-live.clusterhq.com:8080/job/ClusterHQ-flocker/view/releases/job/release-maintenance-flocker-1.13.0-diff-spelling-FLOC-4443/job/run_sphinx/
vs
* http://ci-live.clusterhq.com:8080/job/ClusterHQ-flocker/view/master/job/master/job/run_sphinx/
I also tried to see if the `apt-get install wamerican-{large,huge,insane}` word lists package had it ...they don't.
But it does seem to be present in the  Fedora23 `words` package.
Oh well.
=> [FLOC-4443] Add diff to the spelling list

docs/docker-integration/tutorial-downloads/flocker-swarm-tutorial-node2.yml
Fixes: https://clusterhq.atlassian.net/browse/FLOC-4441
This fixes something I broke in #2778 (specifically https://github.com/ClusterHQ/flocker/pull/2778/files#diff-0bba9631d532bd8773436a553e257fe0R28)
* Start a cloudformation stack using the (as yet unreleased) 1.13.0 template: https://console.aws.amazon.com/cloudformation/home?region=us-east-1#/stacks/new?templateURL=https:%2F%2Fs3.amazonaws.com%2Finstaller.downloads.clusterhq.com%2Fflocker-cluster.cloudformation.1.13.0.json
* Follow the tutorial documentation built from this branch: http://clusterhq-staging-docs.s3-website-us-east-1.amazonaws.com/release-maintenance/flocker-1.13.0/move-postgres-too-FLOC-4441/docker-integration/tutorial-swarm-compose.html
=> [FLOC-4441] Move the postgres database to node2 along with the web container in the tutorial

docs/redirects.yaml
Fixes: https://clusterhq.atlassian.net/browse/FLOC-4445
I set up Google webmaster tools and that confirms that people are searching for "install flocker" and getting a load of ancient pages;
I considered adding a robots.txt to "Dissallow"  crawlers from finding all those  old docs, but am nervous whether that might spoil our search ranking.
* https://en.wikipedia.org/wiki/Robots_exclusion_standard
* https://support.google.com/webmasters/topic/4598466
We could just delete some of those *really* old docs. Google would then remove them from it's index.
That might have the same negative effect on our search ranking.
And finally I investigated "sitemap" files.....but that doesn't really seem to buy us much...assuming that Google can follow all our links.
* …
=> [FLOC-4445] Redirect obsolete documentation to latest

docs/docker-integration/tutorial-downloads/flocker-swarm-tutorial-node2.yml
Fixes: https://clusterhq.atlassian.net/browse/FLOC-4442 
Merging https://github.com/ClusterHQ/flocker/pull/2827 in to master.
=> [FLOC-4442] Move the postgres database to node2 along with the web container in the tutorial 

admin/build_targets/centos-7/Dockerfile, admin/build_targets/ubuntu-14.04/Dockerfile, admin/build_targets/ubuntu-15.10/Dockerfile, build.yaml, requirements/admin.txt, requirements/flocker-dev.txt, requirements/flocker.txt, requirements/flocker.txt.in
Fixes: https://clusterhq.atlassian.net/browse/FLOC-4447
This is caused by:
* https://github.com/GoogleCloudPlatform/compute-image-packages/issues/262
* https://github.com/GoogleCloudPlatform/compute-image-packages/pull/263
I've added google-compute-engine package here but in re-running the `admin/update-requirements` tool I've pulled in a few other library upgrades and a new version of setuptools. 
All good stuff I'm sure and all the tests still pass.
I had some trouble with the GCE functional tests:
* http://ci-live.clusterhq.com:8080/job/ClusterHQ-flocker/job/google-compute-engine-FLOC-4447/job/_run_trial_for_gce_storage_driver_on_CentOS_7_flocker.node.agents.functional/
* http://ci-live.clusterhq.com:8080/job/ClusterHQ-flocker/job/google-compute-engine-FLOC-4447/job/_run_trial_for_gce_s …
=> [FLOC-4447] Add google-compute-engine as a requirement

admin/build_targets/centos-7/Dockerfile, admin/build_targets/ubuntu-14.04/Dockerfile, admin/build_targets/ubuntu-15.10/Dockerfile, build.yaml, requirements/admin.txt, requirements/flocker-dev.txt, requirements/flocker.txt, requirements/flocker.txt.in
Fixes: https://clusterhq.atlassian.net/browse/FLOC-4451
Stacked on #2833 (review that one first)
We always used to bundle it but I missed  it out when I landed #2792
Unfortunately in re-running the `update-requirments` tool I've pulled in a just released version of python-novaclient.
Their release notes are non-existent but the changes I can see, look minor;
* https://github.com/openstack/python-novaclient
I'll run all the acceptance tests to ensure that it hasn't broken anything.
If I have, I'll pin to the previous version.
=> [FLOC-4451] Bundle eliot-tree in the Flocker package

flocker/control/_protocol.py, flocker/control/test/test_protocol.py
Fixes: https://clusterhq.atlassian.net/browse/FLOC-4450
Stacked on #2833 (review that one first)
I refactored the tests a little. It seemed cleaner to have all the connection ping tests together.
I'll trigger the acceptance tests and hopefully we won't see any...
```
AttributeError: 'NoneType' object has no attribute 'abortConnection' after agent disconnects from control service
```
....messages in the remote_logs.log
=> [FLOC-4450] Cancel ping timeout action when AMP connection is lost

admin/ubuntu.py
Fixes: https://clusterhq.atlassian.net/browse/FLOC-4457
I need this to get the regional AMI IDs for Ubuntu Xenial.
(see https://clusterhq.atlassian.net/browse/FLOC-4456)
There are no Xenial `ebs` images, only `ebs-ssd` , as shown by 
```
./admin/ami-search-ubuntu  --ubuntu-name xenial
{}
```
So we'll have to base the new jenkins images off ebs-ssd or instance-store images.
You can now run the tool as follows:
```
$ ./admin/ami-search-ubuntu  --ubuntu-name xenial --ec2-image-type ebs-ssd | jq . 
{
"ap-southeast-1": "ami-1932e07a",
"ap-southeast-2": "ami-bc8ba3df",
"eu-central-1": "ami-26ed0649",
"eu-west-1": "ami-3628b345",
"sa-east-1": "ami-cca431a0",
"us-east-1": "ami-47dd132a",
"us-west-1": "ami-5af9bd3a",
"us-west-2": "ami-83e82ee3"
}
```
=> [FLOC-4457] Allow ami-search-ubuntu to find non-ebs images

admin/build_targets/ubuntu-16.04/Dockerfile, admin/client.py, admin/packaging.py, build.yaml, flocker/provision/_install.py
Fixes: https://clusterhq.atlassian.net/browse/FLOC-4342
The build results are available on this staging server:
* http://52.40.233.218/boxes-flocker?branch=xenial-packages-FLOC-4342
Packages available here:
* http://52.40.233.218/results/omnibus/xenial-packages-FLOC-4342/ubuntu-16.04/
You can run the client installation tests as follows:
```
./admin/run-client-tests  --distribution ubuntu-16.04 --branch xenial-packages-FLOC-4342 --build-server http://52.40.233.218/
```
...but Jenkins should also run them for this branch....let's see.
=> [FLOC-4342] Add support for building and testing Ubuntu 16.04 packages

admin/packaging.py, requirements/admin.txt, requirements/flocker-dev.txt, requirements/flocker-dev.txt.in, requirements/flocker.txt
Fixes: https://clusterhq.atlassian.net/browse/FLOC-4464
I forgot to include pymongo and pg8000 packages when I updated everything in https://github.com/ClusterHQ/flocker/pull/2792
This should stop the 
* flocker.acceptance.integration.test_mongodb and
* flocker.acceptance.integration.test_postgres
...being skipped.
As usual, in running `admin/update-requirements` I've pulled in some unrelated updates. But they all seem to be minor or micro version changes so hopefully shouldn't cause any problems. 
Here are some of the test results, showing that the integration tests for postgres and mongo are no longer skipped:
* http://ci-live.clusterhq.com:8080/job/ClusterHQ-flocker/job/integration-tests-again-FLOC-4464/view/cron/job/_run_acceptance_on_GCE_Ubuntu_Trusty_with_GCE/lastSuccessfulBuild/test …
=> [FLOC-4464] Get the postgresql and mongodb Integration tests working again

admin/test/test_packaging.py, build.yaml
Fixes: https://clusterhq.atlassian.net/browse/FLOC-4463
This fixes a couple of `admin.tests` and updates build.yaml to run all our standard unit tests on the xenial build slave.
The lintian error is that the package description must have more than one word:
* https://lintian.debian.org/tags/description-too-short.html
Once this is merged I'll merge forward https://github.com/ClusterHQ/flocker/pull/2845 (the remaining tests) and put it up for review
=> [FLOC-4463] Run unit tests on Ubuntu 16.04

flocker/common/_retry.py, flocker/common/test/test_retry.py, flocker/dockerplugin/_script.py
Fixes: https://clusterhq.atlassian.net/browse/FLOC-4473
This change causes the `flocker-docker-plugin` process to retry the ``this_node_uuid`` procedure indefinitely.
* *All* failures will be logged and cause a retry.
*  And specifically, the ``twisted.internet.error.NoRouteError`` that was causing systemd to give up restarting the unit.
I've merged this branch into the Ubuntu 16.04 acceptance tests branch and you can see that this change has made the Ubuntu16.04 on Rackspace tests pass:
* http://ci-live.clusterhq.com:8080/job/ClusterHQ-flocker/job/xenial-acceptance-tests-FLOC-4341/view/cron/job/_run_acceptance_on_Rackspace_Ubuntu_Xenial_with_Cinder/
=> [FLOC-4473] Retry the node UUID lookup on network failure

flocker/dockerplugin/_api.py, flocker/dockerplugin/test/test_api.py, flocker/provision/_install.py
In order for one of these to pass, its needs the other. Creating one branch for both.
See:
- https://clusterhq.atlassian.net/browse/FLOC-4480
- https://clusterhq.atlassian.net/browse/FLOC-4483
NOTE- this only fixes acceptance testing for Docker >= 1.12. This will likely break acceptance tests for older versions of docker < 1.12. If we plan on fixing that we should create a seperate issue that allows us to flip flop these type of configurations based on the docker version we want to test.
=> [FLOC-4480, FLOC-4483] Fix docker systemd dropin configuration files and add docker plugin ID for Docker 1.12

flocker/node/agents/functional/test_cinder.py
Fixes: https://clusterhq.atlassian.net/browse/FLOC-4491
The original test monkey patches twisted.web.http, aiming to force the server to make all HTTP connections non-persistent.
The reason for that was to avoid lingering persistent  HTTPChannels  in the reactor after the test....leading to Unclean reactor errors in the test.
But that doesn't work because the client has negotiated a persistent connection and thinks it can re-use it.
The client interprets the empty response which results from server TCP RESET as a ``BadStatusLine`` and aborts the connection...but only if the RST is received slowly...after the client has sent a subsequent HTTP request.
I *think* that's why this test was especially flaky on my devstack environment where the host machine is over loaded and the network packets …
=> [FLOC-4491] Close the Cinder client persistent connection instead of flaky monkey patching of the server side.

flocker/node/agents/cinder.py, flocker/node/agents/functional/test_cinder.py, requirements/flocker-dev.txt, requirements/flocker-dev.txt.in
Fixes: https://clusterhq.atlassian.net/browse/FLOC-4489
Depends on: https://github.com/ClusterHQ/mimic/pull/1
I re-instated the use of detailed volume list.
This ensures that volume attachment information is returned, even when interacting with Cinder v2 API.
One of our tests attempts to hit the volumes/detail endpoint with a mimic based fake REST server.
So I also had to fork andupdate mimic to support that endpoint.
I'll post devstack based test results shortly.
=> [FLOC-4489] Use detailed volume list and update to a version of mimic that supports that endpoint

flocker/control/_protocol.py
Fixes: https://clusterhq.atlassian.net/browse/FLOC-4495
What seems to happen is that if a blocking agent operation takes too long, the AMP connection pings are not responded to this means that the unresponsive peer timeout is reached and the connection is aborted.
And in aborting the connection we attempt to cancel the timer....which has already fired.
Putting this up for review now, to see if it fixes the Ubuntu 14.04 errors and meanwhile I'll see if I can figure out a unit test for this.
This may have been caused by #2836
=> [FLOC-4495] Catch a circular call to cancel the AMP protocol inactivity timeout

flocker/common/process.py, flocker/common/test/sample_script.py, flocker/common/test/test_process.py, flocker/testtools/__init__.py
Fixes: https://clusterhq.atlassian.net/browse/FLOC-4497
I need this for running the mount and blkid commands in  #2908
We can also use this in block_device_manager which has its own, less useful sub process runner.
=> [FLOC-4497] Move run_process to a public module

flocker/acceptance/endtoend/test_dataset.py
Fixes: https://clusterhq.atlassian.net/browse/FLOC-4501
``test_upgrade`` downgrades to a version of Flocker where `compute_instance_id` fails because it can't deal with floating IP addresses on  Rackspace + Ubuntu 14.04.
The test times out and Flocker is never upgraded again and all remaining tests time out.
Once we've released 1.16.0 we can re-enable this test and also remove the skip for Ubuntu 16.04
=> [FLOC-4501] Skip upgrade tests on Openstack backends

docs/_themes/clusterhq/layout_docs.html
Fixes: https://clusterhq.atlassian.net/browse/FLOC-4528
(cherry picked from commit dd96abaf946f489cb676ffa67e522b340d3d2267)
Replaces: #2944
Rendered docs: http://clusterhq-staging-docs.s3-website-us-east-1.amazonaws.com/release-maintenance/flocker-1.15.0/remove-zendesk-FLOC-4528/
=> [FLOC-4528] Remove zendesk from flocker-docs

build.yaml, flocker/node/agents/functional/test_cinder.py
Fixes: https://clusterhq.atlassian.net/browse/FLOC-4533
In #2928 I changed the lint builder to use tox and pipe the output to a file so that the output is visible both in the console output and in an archived build result.
Problem is that the build step always exits with the return code of the tee command rather than the tox command.
Here's an example:
* http://ci-live.clusterhq.com:8080/job/ClusterHQ-flocker/job/master/view/code_quality/job/run_lint/lastSuccessfulBuild/artifact/lint.txt/*view*/
There are some bash specific tricks to have the pipeline fail with the exit code of the first failing command:
* http://www.tldp.org/LDP/abs/html/bashver3.html#PIPEFAILREF
...and to get the exit code of each pipeline component:
* http://www.tldp.org/LDP/abs/html/internalvariables.html#PIPESTATUSREF …
=> [FLOC-4533] Pipe tox output directly to file

admin/installer/cloudformation.py, admin/installer/common.sh, admin/installer/docker-swarm-ca-setup.sh, admin/installer/setup_client.sh, admin/installer/setup_docker.sh, admin/installer/setup_s3.sh, admin/installer/setup_swarm_manager.sh, admin/installer/setup_swarm_node.sh, admin/test/test_installer.py
Fixes: https://clusterhq.atlassian.net/browse/FLOC-4486
I've wrapped the apt-get commands with a retry function.
I rebuilt new cloudformation AMIs with Flocker 1.15.0 pre-installed and the latest versions of Docker and Swarm.
According to "Update the CloudFormation installer template." in https://flocker-docs.clusterhq.com/en/latest/gettinginvolved/infrastructure/release-process.html#release
```
(1.15.0) richard@richardw-pet-ubuntu1604:~/flocker$ jq < ami_map_docker.json 
{
"us-east-1": "ami-b8f6c4af",
"ap-northeast-1": "ami-d4e553b5",
"ap-southeast-2": "ami-de97a9bd",
"sa-east-1": "ami-a58618c9",
"ap-southeast-1": "ami-7d11b31e",
"ap-northeast-2": "ami-25c1164b",
"us-west-2": "ami-8d248bed",
"us-west-1": "ami-1482d674",
"eu-central-1": "ami-b74480d8",
"eu-west-1": "ami-f7085784"
} …
```
=> [FLOC-4486] Retry apt-get operations

flocker/dockerplugin/_script.py, flocker/dockerplugin/test/test_script.py
Fixes: https://clusterhq.atlassian.net/browse/FLOC-4542
=> [FLOC-4542] Convert --rest-api-port to integrer in the flocker-docker-plugin 

.travis.yml, docs/conf.py, docs/gettinginvolved/infrastructure/packaging.rst
Fixes: https://clusterhq.atlassian.net/browse/FLOC-4550
Rendered docs: http://clusterhq-staging-docs.s3-website-us-east-1.amazonaws.com/FLOC-4550-fix-sphinx-warnings/
See: 
* http://clusterhq-staging-docs.s3-website-us-east-1.amazonaws.com/FLOC-4550-fix-sphinx-warnings/administering/debugging.html#flocker-control-service
...for an example of the working intersphinx links for python module references.
=> [FLOC-4550] Fix Sphinx warnings

build.yaml, flocker/volume/test/test_filesystems_zfs.py
Fixes: https://clusterhq.atlassian.net/browse/FLOC-4546
This makes all the flocker unit tests run in a single VM for each of our supported platforms.
* http://ci-live.clusterhq.com:8080/job/ClusterHQ-flocker/job/fewer-build-slaves-FLOC-4546/view/CentOS_7/job/run_trial_on_AWS_CentOS_7_flocker/
* http://ci-live.clusterhq.com:8080/job/ClusterHQ-flocker/job/fewer-build-slaves-FLOC-4546/view/Ubuntu_Xenial_16_04/job/run_trial_on_AWS_Ubuntu_Xenial_flocker/
* http://ci-live.clusterhq.com:8080/job/ClusterHQ-flocker/job/fewer-build-slaves-FLOC-4546/view/Ubuntu_Trusty_14_04_LTS/job/run_trial_on_AWS_Ubuntu_Trusty_flocker/
The unittest builds now take 18-22 minutes but that's still much less than the loopback acceptance tests so it doesn't change the overall build time.
The advantage is that fewer …
=> [FLOC-4546] Run all the flocker unit tests on a single build slave

flocker/node/agents/_logging.py, flocker/node/agents/ebs.py, flocker/node/agents/test/test_ebs.py
Fixes: https://clusterhq.atlassian.net/browse/FLOC-4552
Based on https://github.com/ClusterHQ/flocker/pull/2973 with some extra logging and unit tests.
Thanks to @sgnn7 for reporting this issue and providing a patch.
=> [FLOC-4552] Harden EBS tag parsing

.travis.yml, .travis/script, benchmark/metrics/test/test_cputime.py, benchmark/test/test_metrics_parser.py, build.yaml, flocker/control/_persistence.py, flocker/control/test/test_persistence.py, flocker/node/agents/test/test_ebs.py, tox.ini
Fixes: https://clusterhq.atlassian.net/browse/FLOC-4553
Another step towards moving all our builds off Jenkins.
Hopefully this'll give us much faster feedback of unit test failures.
It'll also allow outside contributors to get test feedback.
=> [FLOC-4553] Run Ubuntu 14.04 unit tests on Travis-CI

build.yaml, flocker/acceptance/testtools.py, flocker/provision/_install.py
Fixes: https://clusterhq.atlassian.net/browse/FLOC-4556
Don't put package files in the repository.
Put them straight into /var/html instead.
I've also put the package repo in directory that *should* only exist for a single build.
$TRIGGERED_BRANCH/$BUILD_TAG
* https://wiki.jenkins-ci.org/display/JENKINS/Building+a+software+project#Buildingasoftwareproject-JenkinsSetEnvironmentVariables
There are a bunch of acceptance test failures caused by failure to cleanup Docker containers after the integration tests. 
I dug into the logs and found signs of this known Docker issue: https://github.com/docker/docker/issues/27381
=> [FLOC-4556] Avoid putting root owned files into the checked out repository
